// СУМІЖНЕ — 4 теми, розширена версія
module.exports = {
  title: "СУМІЖНЕ, ЩО СПИТАЮТЬ ОДНАКОВО — 4 теми",
  note: "Мережа, сховище, тести й архітектура — питають на кожній співбесіді незалежно від стека UI.",
  topics: [
    {
      p: "P0", name: "Networking: URLSession і дизайн мережевого шару",
      what: [
        "URLSession — HTTP-клієнт системи. Конфігурації: .default (кеш, куки на диску), .ephemeral (усе в памʼяті — приватні режими), .background (завантаження продовжуються після вбивства застосунку — через окремий системний процес). Сучасний API: let (data, response) = try await session.data(for: request); статус-код — у (response as? HTTPURLResponse)?.statusCode, і URLSession НЕ кидає помилку на 404/500 — це твоя робота.",
        "Дизайн шару (твоя робоча тема): Endpoint описує запит (path, method, body, headers) як значення; generic-метод request<T: Decodable> виконує і декодує; централізована обробка: mapping статус-кодів у доменні помилки (enum APIError), refresh токена на 401 з повтором запиту, логування.",
      ],
      problem: "Централізований типізований шар вирішує: розкидані по екранах URLSession.shared.dataTask з копіпастою обробки помилок; «тихі» баги від незвірених статус-кодів; неможливість глобально додати авторизацію/ретраї/логування. Одна точка входу = одне місце для всіх cross-cutting concerns.",
      where: [
        "Твій продакшн-шар в Eatery Club — розкажи на співбесіді СВОЄ: типізовані запити, централізовані помилки — це готова сильна відповідь.",
        "Скасування пошуку: тримаєш Task попереднього запиту, cancel() перед новим (або .task(id: query) у SwiftUI робить це сам).",
        "Паралельні незалежні запити екрана: async let / TaskGroup.",
        "URLCache + ETag: безкоштовний HTTP-кеш для каталогу; SSL pinning — захист від MITM (знати концепцію: перевірка сертифіката сервера у delegate).",
      ],
      code: [
        "enum APIError: Error {",
        "    case unauthorized, notFound",
        "    case server(code: Int), decoding(Error), transport(Error)",
        "}",
        "func request<T: Decodable>(_ endpoint: Endpoint) async throws -> T {",
        "    let (data, response) = try await session.data(for: endpoint.urlRequest)",
        "    guard let http = response as? HTTPURLResponse else { throw APIError.server(code: -1) }",
        "    switch http.statusCode {",
        "    case 200..<300: break",
        "    case 401: throw APIError.unauthorized      // → refresh token flow",
        "    case 404: throw APIError.notFound",
        "    default:  throw APIError.server(code: http.statusCode)",
        "    }",
        "    do { return try decoder.decode(T.self, from: data) }",
        "    catch { throw APIError.decoding(error) }",
        "}",
      ],
      traps: [
        "URLSession не кидає на 4xx/5xx — помилка транспорту ≠ помилка сервера; хто не перевіряє статус, декодить HTML-сторінку помилки як JSON.",
        "Retry на 401: онови токен ОДИН раз і повтори; два запити одночасно отримали 401 — refresh має бути дедуплікований (actor/серіалізація), інакше подвійний refresh забанить сесію.",
        "Background session вимагає delegate-API (не async), і система викликає колбеки навіть після перезапуску застосунку.",
        "Таймаути: timeoutIntervalForRequest — на тишу між пакетами, не на весь запит.",
      ],
      qs: [
        "Намалюй свій мережевий шар з роботи: шлях запиту від виклику до декодованої моделі, де ловляться помилки?",
        "Чому URLSession не кидає помилку на 500 і що буде, якщо забути перевірити статус?",
        "Як реалізувати refresh токена на 401 без подвійного refresh при паралельних запитах?",
        "Як скасувати попередній пошуковий запит при введенні нового символа?",
      ],
    },
    {
      p: "P1", name: "Persistence: UserDefaults, Keychain, Core Data / SwiftData, файли",
      what: [
        "Чотири інструменти під чотири задачі. UserDefaults — маленькі налаштування (прапорці, вибрана мова); plist-файл, НЕ шифрований, вантажиться цілком у память. Keychain — секрети (токени, паролі): шифрується системою, переживає ВИДАЛЕННЯ застосунку, доступ через Security framework (усі користуються обгортками). Core Data — обʼєктний граф зі звʼязками, запитами, міграціями, lazy-loading (faults); це НЕ «обгортка SQLite», а фреймворк керування графом обʼєктів. Файли/FileManager — блоби: картинки, кеш JSON, документи.",
        "Core Data стек: NSPersistentContainer → viewContext (main, для UI) + background contexts (newBackgroundContext / performBackgroundTask). Правило потоків: NSManagedObject живе У СВОЄМУ контексті — між потоками передається objectID, не обʼєкт. SwiftData — новий шар над тим самим ядром: @Model-макрос, @Query у SwiftUI.",
      ],
      problem: "Правильний вибір сховища — питання і безпеки, і перформансу: токен у UserDefaults читається з бекапа/джейлбрейка за секунди (провал секʼюріті-ревʼю); список з 10 000 обʼєктів у UserDefaults — секунди на кожен запуск; блокуючий запис Core Data на main — фризи UI.",
      where: [
        "Твій проєкт: access/refresh токени → Keychain; вибраний ресторан, мова, фіче-флаги онбордингу → UserDefaults; кеш меню для офлайн-старту → JSON-файл або Core Data; фото страв → диск через Kingfisher-кеш.",
        "Background import: синк каталогу з бекенда — performBackgroundTask, збереження, main context підтягує зміни через automaticallyMergesChangesFromParent.",
        "App Group + UserDefaults(suiteName:) — шаринг стану з віджетом/Live Activity (твоя фіча!).",
      ],
      code: [
        "// Токен — тільки Keychain:",
        "func saveToken(_ token: Data) {",
        "    let query: [String: Any] = [",
        "        kSecClass as String: kSecClassGenericPassword,",
        "        kSecAttrAccount as String: \"accessToken\",",
        "        kSecValueData as String: token,",
        "        kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlock",
        "    ]",
        "    SecItemDelete(query as CFDictionary)      // upsert: видалити старий",
        "    SecItemAdd(query as CFDictionary, nil)",
        "}",
        "// Core Data: масовий запис без блокування UI:",
        "container.performBackgroundTask { context in",
        "    for dto in dtos { _ = MenuItem(context: context, dto: dto) }",
        "    try? context.save()     // main context змерджить зміни автоматично",
        "}",
      ],
      traps: [
        "Токен у UserDefaults — класична причина завалу секʼюріті-питання на співбесіді. Тільки Keychain.",
        "Keychain переживає видалення застосунку — на першому запуску після перевстановлення можеш знайти старий токен; чисть за прапорцем першого запуску.",
        "NSManagedObject між потоками — креш/UB; передавай objectID.",
        "UserDefaults.synchronize() — не потрібен з iOS 12, викликати його — маркер застарілих знань.",
      ],
      qs: [
        "Що куди зберігати: токен, налаштування, кеш меню, фото — і чому саме так?",
        "Чому токен НЕ можна в UserDefaults — два конкретні ризики?",
        "Як записати 1000 обʼєктів у Core Data, не заблокувавши UI?",
        "Як шарити дані з віджетом/Live Activity (App Group) — твій робочий досвід?",
      ],
    },
    {
      p: "P1", name: "Тестування: XCTest, моки, DI",
      what: [
        "Unit-тест перевіряє одиницю логіки в ізоляції: швидкий (мілісекунди), детермінований, без мережі/диска/UI. Структура given-when-then. Async-логіка: await прямо в тесті (func test... async throws). XCTest — основний фреймворк; Swift Testing (нове покоління): @Test, #expect, параметризовані тести — знати, що існує.",
        "Мокання: залежність за протоколом → тестова реалізація з контрольованою відповіддю (stub) і записом викликів (spy). DI через init робить підміну тривіальною. Піраміда: багато unit (логіка VM, парсери, форматери) → менше integration → мінімум UI-тестів (повільні й крихкі).",
      ],
      problem: "Тести вирішують страх рефакторингу і регресії: у твоєму мультибрендовому проєкті зміна в спільному коді може зламати 5 брендів — тести ловлять це до QA. Для співбесіди: відсутність тестів у резюме — найпомітніший твій геп; вміння написати тест VM з моком мережі закриває питання.",
      where: [
        "Найвигідніші перші тести у твоєму проєкті: розрахунок кошика (CartTotals — чиста логіка, ідеальний кандидат), парсери server-driven конфігів, форматери адрес/цін.",
        "VM з моком: тест успіху, тест помилки мережі, тест порожнього стану — три тести на екран, і вже є що показати.",
        "Fixtures: static func fixture(...) з дефолтами — читабельні тестові дані без шуму.",
      ],
      code: [
        "final class MockOrderService: OrderService {",
        "    var result: Result<[Order], Error> = .success([])",
        "    private(set) var fetchCallCount = 0          // spy: перевірка взаємодії",
        "    func fetchOrders() async throws -> [Order] {",
        "        fetchCallCount += 1",
        "        return try result.get()",
        "    }",
        "}",
        "final class OrdersViewModelTests: XCTestCase {",
        "    func testLoadFailure_showsError() async {",
        "        // given",
        "        let mock = MockOrderService()",
        "        mock.result = .failure(APIError.server(code: 500))",
        "        let vm = OrdersViewModel(service: mock)",
        "        // when",
        "        await vm.load()",
        "        // then",
        "        guard case .failed = vm.state else { return XCTFail(\"expected .failed\") }",
        "        XCTAssertEqual(mock.fetchCallCount, 1)",
        "    }",
        "}",
      ],
      traps: [
        "Тести, що ходять у реальну мережу — повільні, флакі, залежні від бекенда; це НЕ unit-тести.",
        "Синглтони в коді = неможливість мокати; DI через init — передумова тестованості (тому питання про тести — це питання про архітектуру).",
        "Тестуй поведінку, не імплементацію: перевіряй стан VM, а не «викликався приватний метод».",
        "XCTestExpectation досі потрібен для callback-API; для async/await — просто await.",
      ],
      qs: [
        "Напиши тест VM: успіх і помилка мережі — з моком через протокол.",
        "Stub vs spy vs mock — різниця?",
        "Що б ти покрив тестами першим у своєму проєкті і чому (підказка: CartTotals)?",
        "Чому синглтони заважають тестуванню?",
      ],
    },
    {
      p: "P0", name: "Архітектури і SOLID — розмовна тема",
      what: [
        "MVC — Apple-дефолт: VC тримає і view-логіку, і презентаційну → «Massive View Controller». MVVM — презентаційна логіка й стан у ViewModel, який НЕ знає про UIKit/SwiftUI → тестований; природна пара для SwiftUI. MVP — presenter командує пасивною view через протокол. VIPER — + Interactor (бізнес-логіка), Router (навігація), Entity: багато файлів на екран, для великих команд із жорсткими межами. Clean Architecture — шари domain/data/presentation, залежності показують всередину (domain нічого не знає про UI і мережу).",
        "SOLID на iOS-прикладах: S — VC, що і верстає, і ходить у мережу, і парсить — розділити; O — нова секція home page додається новим типом, а не switch-ом у 10 місцях (твій server-driven UI — буквально це); L — сабклас не ламає контракт базового; I — не UITableViewDataSource+Delegate в одному гігантському протоколі, а вузькі ролі; D — VM залежить від OrderService-протоколу, не від конкретного APIClient.",
      ],
      problem: "Архітектура вирішує масштабування коду командою: де шукати баг, як не зачепити чуже, як тестувати. На співбесіді це перевірка зрілості: чи розумієш ТРЕЙДОФИ (VIPER на 3-екранному застосунку — оверінжиніринг; MVC на 50 екранах — болото), а не «яка архітектура наймодніша».",
      where: [
        "Твоя робоча відповідь: UIKit-екрани — MVC із винесеними менеджерами (CartTotalsManager, CreateOrderManager — по суті інтерактори), нові SwiftUI-екрани — MVVM; server-driven UI зверху. Сформулюй це ЯК СВОЮ архітектурну розповідь — 3 хвилини, впевнено.",
        "Server-driven UI — твоя унікальна тема: конфіг з бекенда (таби, секції, кроки checkout) → фабрики екранів/секцій за типом → одна кодова база на N брендів. Підготуй схему словами: конфіг → парсинг → реєстр фабрик → рендер.",
        "Патерни, які реально питають: Singleton (чому обережно: глобальний стан, нетестовність), Observer (NotificationCenter/Combine), Factory (твої фабрики секцій!), Coordinator, Adapter (обгортка сторонніх SDK), Facade (твої менеджери).",
      ],
      code: [
        "// D із SOLID — залежність від абстракції:",
        "protocol PaymentService {",
        "    func pay(order: Order) async throws -> PaymentResult",
        "}",
        "struct ApplePayService: PaymentService { /* PassKit */ }",
        "struct StripeService: PaymentService { /* Stripe SDK */ }",
        "final class CheckoutViewModel {",
        "    private let payment: PaymentService     // не знає, ЯКА оплата",
        "    init(payment: PaymentService) { self.payment = payment }",
        "}",
        "// O — server-driven секції: новий тип = новий кейс фабрики, не switch по коду",
        "protocol HomeSectionFactory { func makeSection(config: SectionConfig) -> UIView }",
      ],
      traps: [
        "«Яка архітектура найкраща?» — питання-пастка: правильна відповідь через тредофи і розмір команди/проєкту, не назва.",
        "Не вивчай VIPER напамʼять — вмій пояснити РОЛІ шарів і навіщо стільки межей.",
        "Singleton ≠ зло, але: приховані залежності, глобальний мутабельний стан, нетестовність — тому DI навіть для shared-обʼєктів.",
        "Готуй ВЛАСНІ приклади: SOLID без прикладів із свого коду звучить як переказ статті.",
      ],
      qs: [
        "Опиши архітектуру Eatery Club за 3 хвилини: шари, потоки даних, як server-driven конфіг керує UI.",
        "MVC vs MVVM — чому MVVM тестованіший? Покажи, ЩО саме тестуєш.",
        "Кожна літера SOLID — з прикладом із твого коду.",
        "Коли VIPER — правильний вибір, а коли оверінжиніринг?",
      ],
    },
  ],
};
