// SWIFTUI — 9 тем, розширена версія
module.exports = {
  title: "SWIFTUI — 9 тем",
  note: "Головна тема — data flow і identity: 80% питань зводяться до «чому вʼюха перемалювалась / не перемалювалась / скинула стан».",
  topics: [
    {
      p: "P0", name: "Ментальна модель: View як value, identity, rerendering",
      what: [
        "View у SwiftUI — не обʼєкт на екрані, а дешевий struct-«опис» того, що має бути на екрані. Фреймворк викликає body, порівнює новий опис зі старим і застосовує лише різницю до реального рендер-дерева (attribute graph). body може викликатись дуже часто — тому він зобовʼязаний бути дешевим і без side effects.",
        "Identity відповідає на питання «це та сама вʼюха, що й у попередньому кадрі, чи нова?». Structural identity — позиція у дереві коду (перша гілка if — одна вʼюха, друга — інша). Explicit identity — задана вручну через .id(value) або ForEach(id:). Поки identity збережена — стан (@State) живе; identity змінилась — стара вʼюха знищується разом зі станом, анімується перехід.",
      ],
      problem: "Ця модель вирішує головну проблему імперативного UI — розсинхрон стану і екрана (забув оновити лейбл після зміни моделі). У SwiftUI екран — функція від стану: змінився стан → фреймворк сам перерахував опис. Ціна — треба розуміти identity, інакше зʼявляються «магічні» баги: стан скидається, анімації не працюють, скрол стрибає.",
      where: [
        "if isLoggedIn { HomeView() } else { LoginView() } — дві РІЗНІ identity: перемикання повністю пересоздає вʼюху (з анімацією переходу).",
        "myView.opacity(isVisible ? 1 : 0) — identity ЗБЕРЕЖЕНА, стан живе; if isVisible { myView } — identity втрачається разом зі станом.",
        ".id(userID) на екрані профілю — явний спосіб СКИНУТИ стан вʼюхи при зміні користувача (перевикористання цього ж прийому — pull-to-refresh скидання).",
        "Дебаг зайвих перерендерів: let _ = Self._printChanges() у body покаже, яка залежність тригернула виклик.",
      ],
      code: [
        "struct CounterView: View {",
        "    @State private var count = 0",
        "    var body: some View {",
        "        let _ = Self._printChanges()   // дебаг: що викликало body",
        "        VStack {",
        "            Text(\"Count: \" + String(count))",
        "            Button(\"+\") { count += 1 }",
        "        }",
        "    }",
        "}",
        "// .id змінює identity → @State скидається:",
        "CounterView().id(resetToken)   // новий resetToken = новий лічильник з нуля",
      ],
      traps: [
        "Side effects у body (мережевий запит, запис у UserDefaults) — body викликається непередбачувано часто; ефекти лише в .task/.onAppear/діях.",
        "Виклик body ≠ перерисовка пікселів: SwiftUI дифить описи і чіпає лише реальні зміни. «body викликається часто» — це нормально, якщо він дешевий.",
        "AnyView стирає тип і заважає діфингу — уникай у списках; замість нього @ViewBuilder-гілки.",
        "Важкі обчислення в body — виноси у ViewModel/computed поза body або кешуй.",
      ],
      qs: [
        "Чому @State скидається при зміні identity і як цим свідомо користуватись через .id()?",
        "if/else vs opacity — у чому різниця для identity, стану й анімацій?",
        "body викликався — чи означає це перерисовку UIKit/Metal-шару? Що насправді відбувається?",
        "Як знайти, чому вʼюха перерендерюється занадто часто?",
      ],
    },
    {
      p: "P0", name: "Data flow: @State, @Binding, @StateObject, @ObservedObject, Observation",
      what: [
        "@State — джерело правди для локального value-стану вʼюхи; SwiftUI зберігає значення ПОЗА структурою (у своєму сховищі, привʼязаному до identity), тому воно переживає пересоздання struct. @Binding — посилання на чуже джерело правди ($-синтаксис створює Binding зі @State): дитина читає і пише, але не володіє.",
        "@StateObject — вʼюха СТВОРЮЄ і володіє ObservableObject: обʼєкт створюється один раз на життя identity. @ObservedObject — вʼюха лише СПОСТЕРІГАЄ за чужим обʼєктом: якщо батько перерендериться і створить новий обʼєкт — стан загубиться. Правило: створюєш тут → @StateObject; передали ззовні → @ObservedObject.",
        "Observation (iOS 17+): макрос @Observable на класі замінює ObservableObject/@Published. Головна перевага — гранулярне відстеження: вʼюха перерендерюється, лише якщо змінилась властивість, яку вона РЕАЛЬНО читала в body (з ObservableObject — при зміні будь-якого @Published). @Bindable дає біндинги до @Observable-обʼєкта.",
      ],
      problem: "Це відповідь SwiftUI на питання «де живе стан і хто кого оновлює». Класичний баг, який вирішує @StateObject: ViewModel через @ObservedObject у вʼюсі, яку батько часто перебудовує → VM пересоздається, запити перезапускаються, стан зникає. Observation вирішує проблему зайвих перерендерів великих екранів (один @Published тригерив усіх підписників).",
      where: [
        "@State — прапорці UI: showsSheet, введений текст, вибраний таб.",
        "@Binding — переюзабельні компоненти: кастомний пікер/поле, яке редагує значення власника (твої SwiftUI-компоненти в Eatery Club).",
        "@StateObject var vm = CheckoutViewModel(...) на екрані оформлення; дочірнім секціям — @ObservedObject/параметри.",
        "@EnvironmentObject/@Environment — наскрізні залежності: сесія користувача, тема, DI-контейнер через дерево без прокидання параметрами через 5 рівнів.",
        "@AppStorage(\"isDarkMode\") — налаштування напряму з UserDefaults з автооновленням вʼюхи.",
      ],
      code: [
        "@Observable final class CheckoutViewModel {   // iOS 17+",
        "    var items: [CartItem] = []",
        "    var isPlacingOrder = false",
        "    private let service: OrderService",
        "    init(service: OrderService) { self.service = service }",
        "}",
        "struct CheckoutView: View {",
        "    @State private var vm: CheckoutViewModel   // з @Observable — просто @State",
        "    init(service: OrderService) {",
        "        _vm = State(initialValue: CheckoutViewModel(service: service))",
        "    }",
        "    var body: some View {",
        "        List(vm.items) { CartRow(item: $0) }    // читає items → підписка лише на items",
        "    }",
        "}",
      ],
      traps: [
        "Класика: @ObservedObject var vm = MyVM() (створення на місці) — VM пересоздається при кожному перерендері батька. Ліки: @StateObject.",
        "@StateObject ініціалізується один раз — параметри, передані пізніше, не оновлять його; для залежностей, що змінюються, продумай init або .id().",
        "@EnvironmentObject без .environmentObject(...) вище по дереву — креш у рантаймі.",
        "З ObservableObject зміна @Published з фонового потоку — фіолетовий warning; @MainActor на VM вирішує системно.",
      ],
      qs: [
        "@StateObject vs @ObservedObject: хто володіє життєвим циклом? Відтвори класичний баг.",
        "Чому @Observable ефективніший за ObservableObject + @Published — що саме відстежується?",
        "Де фізично зберігається значення @State, якщо View — struct, який постійно пересоздається?",
        "Три способи прокинути стан на 3 рівні вниз — тредофи кожного?",
      ],
    },
    {
      p: "P0", name: "Layout system",
      what: [
        "Однопрохідний протокол із трьох кроків: (1) батько ПРОПОНУЄ дочірній вʼюсі розмір (proposal); (2) дитина ОБИРАЄ власний розмір (може проігнорувати пропозицію — Text не стиснеться нижче за читабельність без явного дозволу); (3) батько РОЗМІЩУЄ дитину у своїх координатах. Розмір дитини — її рішення; позиція — рішення батька.",
        ".frame(width:height:) — не «сеттер розміру», а вʼюха-обгортка, яка пропонує дитині вказаний розмір і сама займає його. fixedSize() — «стань ідеальним розміром, ігноруй пропозицію» (багатострочний Text перестає обрізатись). layoutPriority — кому зі стеку віддавати простір останнім.",
      ],
      problem: "Вирішує проблему двонаправлених обмежень AutoLayout (конфлікти, unsatisfiable constraints, дебаг рівнянь) — тут конфліктів не буває за побудовою: протокол завжди завершується якимось розміром. Ціна — треба розуміти переговори «пропозиція-відповідь», інакше несподівані обрізання і розтягування.",
      where: [
        ".frame(maxWidth: .infinity) — «розтягнись на всю пропозицію» — стандарт для кнопок на всю ширину.",
        "GeometryReader — коли потрібні реальні розміри/координати (прогрес-бар у частках ширини, паралакс при скролі). Але він жадібний — займає ВСЕ запропоноване, тому обгортай точково.",
        "iOS 17+: containerRelativeFrame (частка контейнера без GeometryReader), onGeometryChange (реакція на зміну розміру) — сучасніші точкові інструменти.",
        "Двa лейбли в HStack, місця мало: заголовок .layoutPriority(1) — обріжеться підзаголовок.",
      ],
      code: [
        "HStack {",
        "    Text(title).layoutPriority(1)     // отримає простір першим",
        "    Spacer()",
        "    Text(subtitle).lineLimit(1)       // стиснеться перший",
        "}",
        "Text(\"Довгий текст\")",
        "    .frame(width: 50)                 // Text обріжеться: він ОБИРАЄ бути",
        "                                      // читабельним, frame лише пропонує",
        "Button(\"Оплатити\") { }",
        "    .frame(maxWidth: .infinity)       // на всю ширину пропозиції",
      ],
      traps: [
        "GeometryReader усередині рядка списку розтягує рядок — обгортай мінімально або бери onGeometryChange.",
        ".frame(width: 50) НЕ гарантує, що Text стане 50pt: дитина може обрати інше (обрізання з «...»).",
        "Порядок модифікаторів = вкладеність вʼюх: .padding().background(...) ≠ .background(...).padding().",
        "Spacer у ScrollView не працює як очікуєш: пропозиція по осі скролу нескінченна.",
      ],
      qs: [
        "Опиши три кроки layout-протоколу. Хто вирішує розмір, хто — позицію?",
        "Що станеться з Text при .frame(width: 50), якщо текст ширший — і чому?",
        "Чому GeometryReader «жадібний» і які iOS 17-альтернативи?",
        "Чому padding-background і background-padding дають різні результати?",
      ],
    },
    {
      p: "P1", name: "Lists, ForEach, lazy-контейнери, performance",
      what: [
        "List — готовий скрол-список з reuse (під капотом UICollectionView), стилями, swipe actions, секціями. LazyVStack у ScrollView — ліниве створення рядків без стилів List (повний контроль верстки), але БЕЗ reuse у класичному сенсі. VStack — створює ВСІ дочірні вʼюхи одразу — тільки для малих наборів.",
        "ForEach — не цикл, а вʼюха-фабрика, яка вимагає стабільної identity елементів (Identifiable або id:). За identity SwiftUI розуміє: цей елемент пересунувся (анімація), цей зник (видалення), цей новий (вставка).",
      ],
      problem: "Lazy-контейнери вирішують памʼять і час старту: стрічка з 1000 позицій меню створює лише видимі рядки. Стабільні ID вирішують правильність diff-а: з id: \\.self на індексах видалення елемента з середини SwiftUI сприймає як «змінились усі елементи після нього» — зламані анімації, загублений стан рядків, стрибки скролу.",
      where: [
        "Каталог/меню/стрічка замовлень — List або LazyVStack + ForEach(items) (Order: Identifiable за server id — стабільний ID).",
        "Пагінація: .task(id: items.last?.id) або .onAppear останнього рядка → підвантаження сторінки.",
        "Горизонтальні карусельки (промо-банери в home page): ScrollView(.horizontal) + LazyHStack.",
        "Async-картинки у рядках: Kingfisher/AsyncImage з плейсхолдером — не вантаж у body синхронно.",
      ],
      code: [
        "struct MenuList: View {",
        "    let items: [MenuItem]                  // MenuItem: Identifiable (id з бекенда)",
        "    var body: some View {",
        "        List(items) { item in",
        "            MenuRow(item: item)",
        "                .onAppear {",
        "                    if item.id == items.last?.id { loadNextPage() }",
        "                }",
        "        }",
        "        .listStyle(.plain)",
        "    }",
        "}",
        "// НЕ РОБИ: ForEach(0..<items.count, id: \\.self) — індекси нестабільні",
      ],
      traps: [
        "ForEach(0..<count) з мутабельним масивом — креш або зламаний diff при зміні розміру; діапазонна форма лише для констант.",
        "id: \\.self на елементах, що повторюються (два однакові рядки) — конфлікт identity, «дивні» анімації.",
        "Важкий body рядка (форматування дат, обчислення) множиться на кількість видимих рядків — форматуй заздалегідь у VM.",
        "AnyView у рядках списку руйнує оптимізації диффінгу.",
      ],
      qs: [
        "List vs LazyVStack vs VStack — коли що і чому?",
        "Який конкретно баг створює ForEach(0..<items.count) при видаленні елемента з середини?",
        "Як зробити пагінацію у List двома способами?",
        "Чому стабільний server-side ID кращий за UUID(), згенерований у init моделі?",
      ],
    },
    {
      p: "P1", name: "Navigation",
      what: [
        "NavigationStack (iOS 16+) — стек з навігацією за ДАНИМИ: NavigationLink(value: order) кладе значення, navigationDestination(for: Order.self) каже, який екран для цього типу. NavigationPath — типостертий масив-шлях: маніпулюєш ним программно (push/pop/popToRoot = append/removeLast/removeAll).",
        "Модальні: .sheet(isPresented:)/.sheet(item:) — item-варіант звʼязує показ із даними (nil = закрито, значення = показано з цими даними) і прибирає розсинхрон «прапорець true, а даних ще нема». fullScreenCover, presentationDetents (половинні шторки).",
      ],
      problem: "NavigationStack вирішує головний біль NavigationView: неможливість програмної навігації на N рівнів і крихкі isActive-біндинги. Навігація за даними означає: стан навігації — це просто значення, його можна зберегти, відновити, побудувати з дип-лінка.",
      where: [
        "Дип-лінк «відкрий замовлення №42 з пуша»: розпарсив URL → path.append(OrderRoute.details(id: 42)) — екран відкрився програмно (твій робочий кейс з universal links).",
        "Checkout-флоу: enum CheckoutStep у path — кроки оформлення як дані (сумісно з твоїм server-driven checkout).",
        "sheet(item: $selectedProduct) — картка товару: вибір елемента списку відкриває шторку з ним.",
        "Роутер-обʼєкт: клас Router з @Published var path — інʼєктиться через environment, будь-який екран може навігувати без звʼязності.",
      ],
      code: [
        "enum Route: Hashable {",
        "    case orderDetails(id: String)",
        "    case restaurant(id: String)",
        "}",
        "struct RootView: View {",
        "    @State private var path = NavigationPath()",
        "    var body: some View {",
        "        NavigationStack(path: $path) {",
        "            HomeView()",
        "                .navigationDestination(for: Route.self) { route in",
        "                    switch route {",
        "                    case .orderDetails(let id): OrderDetailsView(id: id)",
        "                    case .restaurant(let id): RestaurantView(id: id)",
        "                    }",
        "                }",
        "        }",
        "        .onOpenURL { url in",
        "            if let route = DeepLinkParser.parse(url) { path.append(route) }",
        "        }",
        "    }",
        "}",
      ],
      traps: [
        "navigationDestination усередині lazy-контейнера (рядка List) — може не зареєструватись; вішай на контейнер/зовнішню вʼюху.",
        "sheet(isPresented:) + окрема опціональна властивість — гонка «шторка відкрилась, дані nil»; sheet(item:) вирішує атомарно.",
        "NavigationPath типостертий — «прочитати» маршрути назад не можна; потрібен інтроспект — тримай свій [Route] замість NavigationPath.",
        "NavigationView deprecated: дві колонки на iPad несподівано, isActive-хаки — на співбесіді згадай, що мігрував би на Stack.",
      ],
      qs: [
        "Як відкрити екран на 3 рівні вглиб із дип-лінка? Покажи шлях від URL до path.",
        "Чим sheet(item:) кращий за sheet(isPresented:)?",
        "Як організувати роутер, щоб ViewModel не знав про вʼюхи?",
        "Розкажи свій робочий флоу universal links → екран.",
      ],
    },
    {
      p: "P1", name: "Animations і transitions",
      what: [
        "Анімація у SwiftUI — інтерполяція між старим і новим значенням стану, яку фреймворк робить сам. Implicit: .animation(.spring, value: count) — анімувати зміни, спричинені зміною value. Explicit: withAnimation { state = new } — анімувати все, що змінилось від цієї мутації. Transition — як вʼюха ЗʼЯВЛЯЄТЬСЯ/ЗНИКАЄ (зміна identity): .opacity, .move(edge:), asymmetric.",
        "matchedGeometryEffect — «hero»-анімація: два різні вʼюхи з одним id у одному namespace морфяться одна в одну (мініатюра → повноекранна картка). iOS 17: phaseAnimator (циклічні фази), keyframeAnimator (таймлайн).",
      ],
      problem: "Вирішує ручне керування анімаціями UIKit (UIView.animate з узгодженням станів, скасуваннями): у SwiftUI анімації interruptible і retargetable з коробки — нове значення посеред анімації плавно перенаправляє поточну, без стрибків.",
      where: [
        "Розгортання картки товару, показ/приховання фільтрів — withAnimation + transition.",
        "Стан кнопки «Оплатити» → лоадер: transition(.opacity.combined(with: .scale)).",
        "Промо-банери: matchedGeometryEffect для переходу мініатюра → деталі.",
        "Скелетони завантаження: phaseAnimator для пульсації (твій SkeletonView-аналог нативно).",
      ],
      code: [
        "struct ExpandableCard: View {",
        "    @State private var expanded = false",
        "    var body: some View {",
        "        VStack {",
        "            header.onTapGesture {",
        "                withAnimation(.spring(duration: 0.35)) { expanded.toggle() }",
        "            }",
        "            if expanded {",
        "                details.transition(.move(edge: .top).combined(with: .opacity))",
        "            }",
        "        }",
        "    }",
        "}",
      ],
      traps: [
        "transition не працює без анімації: зміна умови має бути в withAnimation (або .animation з value) — інакше просто зникне.",
        "transition спрацьовує лише при зміні IDENTITY (if/else, ForEach вставки) — не при зміні властивостей.",
        ".animation(.spring) БЕЗ value — deprecated: анімував усе підряд, включно з layout при повороті; завжди вказуй value.",
        "Анімація в List/скролі може конфліктувати з анімаціями системи — тестуй на пристрої.",
      ],
      qs: [
        "transition vs animation — що анімує кожен і коли спрацьовує transition?",
        "Чому .animation без value був deprecated?",
        "Як зробити hero-перехід між списком і деталями?",
        "Що означає interruptible/retargetable і чим це краще за UIView.animate?",
      ],
    },
    {
      p: "P1", name: "Life cycle і side effects: task, onAppear, App protocol",
      what: [
        "Точка входу — struct з @main: App → Scene (WindowGroup) → кореневий View. @Environment(\\.scenePhase) — active/inactive/background — реакція на згортання (аналог sceneDidEnterBackground).",
        ".task { } — асинхронна робота, привʼязана до життя вʼюхи: стартує при появі, АВТОМАТИЧНО СКАСОВУЄТЬСЯ при зникненні. .task(id:) — перезапуск при зміні значення (новий пошуковий запит при зміні тексту). .onAppear — синхронний хук появи; може викликатись кілька разів (повернення назад по навігації).",
      ],
      problem: ".task вирішує дві проблеми onAppear + Task {}: (1) витік роботи — запит продовжується після закриття екрана (а .task скасується сам); (2) повторні запити при кожній появі — у .task зручно guard-ити стан. UIApplicationDelegateAdaptor вирішує інтеграцію: пуші, Firebase, deep links вимагають AppDelegate — його підключають у SwiftUI-app без переписування.",
      where: [
        ".task { await vm.loadMenu() } на екрані меню — завантаження з автоскасуванням.",
        ".task(id: searchText) з debounce — живий пошук: новий текст скасовує попередній запит (try await Task.sleep + перевірка).",
        "scenePhase == .background → зберегти чернетку кошика.",
        "@UIApplicationDelegateAdaptor(AppDelegate.self) — реєстрація пушів, конфіг Firebase (твій робочий сетап).",
      ],
      code: [
        "struct SearchView: View {",
        "    @State private var query = \"\"",
        "    @State private var results: [Restaurant] = []",
        "    var body: some View {",
        "        List(results) { RestaurantRow(restaurant: $0) }",
        "            .searchable(text: $query)",
        "            .task(id: query) {                         // перезапуск на кожну зміну",
        "                try? await Task.sleep(for: .milliseconds(300))  // debounce",
        "                guard !Task.isCancelled, !query.isEmpty else { return }",
        "                results = (try? await api.search(query)) ?? []",
        "            }",
        "    }",
        "}",
      ],
      traps: [
        "onAppear НЕ аналог viewDidLoad: викликається при КОЖНІЙ появі (повернення зі стека) — одноразову ініціалізацію guard-и прапорцем або роби в init VM.",
        "Task { } всередині onAppear не скасовується сам — витік роботи; .task робить це за тебе.",
        "На iPad/багатовіконність onAppear/onDisappear можуть приходити несподівано — не привʼязуй критичну логіку сесії тільки до них.",
      ],
      qs: [
        "Чому мережевий запит краще у .task, ніж в onAppear + Task {}? Дві причини.",
        "Як зробити debounce живого пошуку через .task(id:)?",
        "Скільки разів може викликатись onAppear і чим це відрізняється від viewDidLoad?",
        "Навіщо UIApplicationDelegateAdaptor у SwiftUI-застосунку — твій реальний приклад?",
      ],
    },
    {
      p: "P0", name: "Interop із UIKit",
      what: [
        "UIViewRepresentable / UIViewControllerRepresentable — обгортка UIKit у SwiftUI. makeUIView — створити (один раз на identity); updateUIView — синхронізувати зі SwiftUI-станом (викликається на кожне оновлення — має бути ідемпотентним і дешевим); makeCoordinator — створити обʼєкт-міст для делегатів/target-action (Coordinator живе стільки ж, скільки representable, і зазвичай тримає звʼязок «UIKit-подія → SwiftUI Binding»).",
        "UIHostingController — зворотний напрямок: SwiftUI-вʼюха всередині UIKit-флоу. Це UIViewController, який можна пушити, презентувати, вбудовувати як child.",
      ],
      problem: "Вирішує головну проблему реальних проєктів — поступову міграцію: не переписувати десятки UIKit-екранів разом, а додавати нові екрани у SwiftUI всередину наявної навігації (твоя щоденна робота в Eatery Club). І навпаки: використовувати те, чого у SwiftUI немає або воно слабше (карти зі складною поведінкою, WKWebView, кастомні контроли).",
      where: [
        "Нові екрани у SwiftUI пушаться в наявний UINavigationController через UIHostingController — твій робочий патерн.",
        "MapLibre/Google Maps у SwiftUI-екрані — UIViewRepresentable з Coordinator-делегатом карти.",
        "UITextField/UITextView зі специфічною поведінкою (маски вводу, тулбари) — representable з Binding тексту.",
        "sizingOptions/розміри hosting controller — щоб SwiftUI-контент правильно самовимірювався у клітинках UIKit (UIHostingConfiguration для клітинок iOS 16+).",
      ],
      code: [
        "struct MapView: UIViewRepresentable {",
        "    @Binding var selectedPlace: Place?",
        "    func makeUIView(context: Context) -> MLNMapView {",
        "        let map = MLNMapView()",
        "        map.delegate = context.coordinator     // делегат — Coordinator",
        "        return map",
        "    }",
        "    func updateUIView(_ map: MLNMapView, context: Context) {",
        "        // синхронізація SwiftUI-стану → карта (дешево, ідемпотентно)",
        "    }",
        "    func makeCoordinator() -> Coordinator { Coordinator(self) }",
        "    final class Coordinator: NSObject, MLNMapViewDelegate {",
        "        var parent: MapView",
        "        init(_ parent: MapView) { self.parent = parent }",
        "        // подія карти → parent.selectedPlace = ... (назад у SwiftUI)",
        "    }",
        "}",
        "// SwiftUI-екран у UIKit-навігації:",
        "let vc = UIHostingController(rootView: PromoView(viewModel: vm))",
        "navigationController?.pushViewController(vc, animated: true)",
      ],
      traps: [
        "Створення UIView у updateUIView — він викликається постійно; створення ТІЛЬКИ в make.",
        "Coordinator тримає parent за значенням (struct) — оновлюй посилання: context.coordinator.parent = self в update, або тримай binding напряму.",
        "Retain cycle: UIKit-обʼєкт → strong delegate → Coordinator → ... — стеж за посиланнями як у чистому UIKit.",
        "Розмір hosting-контенту: SwiftUI хоче самовимірюватись — у UIKit-верстці дай констрейнти або sizingOptions, інакше нульова висота.",
      ],
      qs: [
        "За що відповідають makeUIView / updateUIView / Coordinator? Чому створення — тільки в make?",
        "Навіщо Coordinator і хто ним володіє?",
        "Розкажи свій робочий кейс: як SwiftUI-екрани вбудовані в UIKit-флоу Eatery Club?",
        "Як дані ходять в обидва боки між SwiftUI і обгорнутим UIKit-вʼю?",
      ],
    },
    {
      p: "P1", name: "Архітектура у SwiftUI: MVVM, DI, тестованість",
      what: [
        "Розподіл: View — лише декларація UI і привʼязка до стану (без бізнес-логіки в body); ViewModel (@Observable/@MainActor) — стан екрана + логіка + виклики сервісів; Services — мережа, сховище, аналітика за протоколами. Стан екрана — enum (idle/loading/loaded/failed), щоб неможливі комбінації не існували.",
        "DI: залежності приходять через init (явно, тестовано) або через Environment (наскрізні). ViewModel залежить від протоколів сервісів — у тестах підставляється мок без мережі.",
      ],
      problem: "Вирішує «Massive View»: коли запити, форматування і навігація звалені в body — це нетестовано і нечитабельно. MVVM робить логіку тестованою БЕЗ UI: тест створює VM з моком, викликає load(), перевіряє стан. Це прямий шлях закрити твій геп у тестуванні — покрий 2-3 своїх VM юніт-тестами і зможеш предметно про це говорити.",
      where: [
        "Кожен новий SwiftUI-екран у твоєму проєкті: CheckoutViewModel зі станом, протокол OrderService, мок у тестах.",
        "Environment для DI-контейнера: сесія, тема, фіче-флаги (ривок до твого server-driven UI — конфіг як залежність).",
        "TCA — знати ідеї оглядово: єдиний стор, редюсери, ефекти; НЕ обовʼязково для співбесід твого рівня, але згадка «знаю концепцію» — плюс.",
      ],
      code: [
        "@MainActor @Observable",
        "final class OrdersViewModel {",
        "    enum State { case loading, loaded([Order]), failed(String) }",
        "    private(set) var state: State = .loading",
        "    private let service: OrderService          // протокол!",
        "    init(service: OrderService) { self.service = service }",
        "    func load() async {",
        "        state = .loading",
        "        do    { state = .loaded(try await service.fetchOrders()) }",
        "        catch { state = .failed(error.localizedDescription) }",
        "    }",
        "}",
        "// Тест без мережі:",
        "func testLoadSuccess() async {",
        "    let vm = OrdersViewModel(service: MockOrderService(stub: [.fixture()]))",
        "    await vm.load()",
        "    guard case .loaded(let orders) = vm.state else { return XCTFail() }",
        "    XCTAssertEqual(orders.count, 1)",
        "}",
      ],
      traps: [
        "Логіка в body — нетестовано; body лише читає стан.",
        "VM, який знає про View/UIKit-типи — залежність у неправильний бік; VM повертає дані, View вирішує як малювати.",
        "Синглтони сервісів усередині VM (Service.shared) — не підмінити в тестах; передавай через init.",
        "Один гігантський EnvironmentObject на весь застосунок — перерендери всього дерева на кожен чих.",
      ],
      qs: [
        "Що лежить у View, що у ViewModel, що в Service? Де межа?",
        "Як протестувати VM, що ходить у мережу — покажи мок і тест.",
        "Навіщо @MainActor на ViewModel?",
        "Як би ти виніс server-driven конфігурацію екранів у залежність для VM?",
      ],
    },
  ],
};
