// SWIFT — 17 тем, розширена версія
module.exports = {
  title: "SWIFT — 17 тем",
  note: "Мова — це 50–60% технічної співбесіди. Особливо памʼять і конкурентність: саме тут відсіюють між junior і middle.",
  topics: [
    {
      p: "P0", name: "Value vs Reference types, struct vs class",
      what: [
        "Value-типи (struct, enum, tuple) при присвоєнні та передачі у функцію копіюються — кожна змінна володіє власним незалежним значенням. Reference-типи (class, closure, actor) передаються за посиланням: кілька змінних вказують на один обʼєкт у купі (heap), і зміна через одне посилання видна всім.",
        "Стандартні колекції (Array, String, Dictionary, Set) — value-типи з оптимізацією Copy-on-Write: фізичне копіювання буфера відбувається лише в момент першої мутації, а не при присвоєнні. Тому передати масив на 100 000 елементів у функцію — дешево, доки функція його не змінює.",
      ],
      problem: "Головна проблема, яку вирішують value-типи — спільний мутабельний стан (shared mutable state): коли два шматки коду тримають один обʼєкт і несподівано змінюють його один одному «під ногами». З value-типами про шматок коду можна міркувати локально: ніхто ззовні твою копію не змінить. Це також безкоштовна потокобезпечність — копії незалежні.",
      where: [
        "Моделі даних і DTO з бекенда — майже завжди struct (у твоєму проєкті LocationAddress, моделі замовлення тощо). Codable + struct — стандартна пара.",
        "SwiftUI: кожна View — struct. Уся ідеологія фреймворку побудована на дешевих value-«описах» інтерфейсу.",
        "class — коли потрібна ідентичність та спільний стан: мережевий менеджер, кеш, сесія користувача, ViewModel (ObservableObject), усе успадковане від UIKit (UIViewController, UIView — класи, бо їм потрібна саме ідентичність конкретного обʼєкта на екрані).",
        "enum — для станів і скінченних варіантів: стан екрана, тип оплати, маршрути дип-лінків.",
      ],
      code: [
        "struct Point { var x = 0 }",
        "var a = Point(); var b = a",
        "b.x = 10                    // a.x == 0 — незалежна копія",
        "",
        "final class Counter { var value = 0 }",
        "let c1 = Counter(); let c2 = c1",
        "c2.value = 10               // c1.value == 10 — один обʼєкт",
        "// let для класу фіксує ПОСИЛАННЯ, не вміст!",
      ],
      traps: [
        "Struct, який містить class-властивість: копіюється struct, але посилання всередині вказує на той самий обʼєкт — «value-семантика» ламається.",
        "let класу не робить обʼєкт незмінним — лише забороняє переприсвоїти посилання. let структури — заморожує все.",
        "mutating-метод структури неможливо викликати на let-змінній — і це фіча, а не обмеження.",
        "Дуже великий struct, який часто копіюється у гарячому коді, може програти класу за перформансом — міряй Instruments, а не вгадуй.",
      ],
      qs: [
        "Що виведе код, де struct присвоєно у дві змінні і одну змінили?",
        "Чому Apple рекомендує struct за замовчуванням?",
        "Як COW впливає на продуктивність передачі великого масиву у функцію? Як перевірити, що копія відбулась?",
        "Наведи приклад зі свого проєкту, де value-семантика врятувала від бага (або де потрібен був саме class).",
      ],
    },
    {
      p: "P0", name: "Optionals",
      what: [
        "Optional<T> — це звичайний enum з двома кейсами: .some(T) і .none. Синтаксис T? — лише цукор. Optional вбудовує «відсутність значення» у систему типів: компілятор змушує явно обробити кейс nil ще до запуску.",
        "Способи роботи: if let / guard let (безпечне розгортання), оператор ?? (значення за замовчуванням), optional chaining user?.address?.city (ланцюг обривається на першому nil), map/flatMap на Optional, force unwrap ! (крешить на nil).",
      ],
      problem: "Вирішує проблему «мільярдної помилки» — null pointer. В Objective-C виклик методу на nil мовчки нічого не робив (приховані баги), у Java NPE валив програму в рантаймі. Swift переносить цю помилку на етап компіляції: тип String і String? — різні типи, і забути перевірку неможливо.",
      where: [
        "Відповіді API: поля, яких може не бути у JSON — var promoCode: String? у моделі замовлення. Codable сам ставить nil для відсутніх ключів, якщо поле опціональне.",
        "UI-стан «ще не завантажено»: var user: User? = nil до приходу відповіді.",
        "Повернення з пошуку: dictionary[key], array.first, Int(\"abc\") — усе повертає Optional, бо результату може не бути.",
        "guard let — стандарт на початку методу: перевірили вхідні дані й далі працюємо з не-опціоналами (early exit).",
      ],
      code: [
        "func handle(response: Data?) {",
        "    guard let data = response else {",
        "        showError(); return   // early exit — далі data гарантовано є",
        "    }",
        "    let order = try? decoder.decode(Order.self, from: data)",
        "    // try? повертає Order? — помилка перетворилась на nil",
        "    label.text = order?.address?.city ?? \"—\"",
        "}",
      ],
      traps: [
        "Force unwrap (!) у продакшні — креш, який знайде користувач. Легітимні винятки: IBOutlet (система гарантує звʼязування), ресурси в бандлі, які точно існують.",
        "try? + функція, що повертає Optional = подвійний optional T?? — легко заплутатись.",
        "if let x = x всередині кожного if — «піраміда»; краще один guard з комою: guard let a, let b else.",
        "map vs flatMap на Optional: map загортає результат ще раз (може дати T??), flatMap сплющує.",
      ],
      qs: [
        "Що таке Optional під капотом? Напиши його оголошення як enum.",
        "Чим map на Optional відрізняється від flatMap?",
        "Чому force unwrap — червоний прапорець і які винятки прийнятні?",
        "guard let vs if let — коли що і чому guard покращує читабельність?",
      ],
    },
    {
      p: "P1", name: "Properties: stored, computed, lazy, observers, wrappers",
      what: [
        "Stored — зберігає значення в памʼяті обʼєкта. Computed — не зберігає нічого, обчислюється при кожному звертанні (get, опційно set). lazy — stored, який ініціалізується при першому звертанні, а не при створенні обʼєкта. Observers willSet/didSet — хуки навколо запису у stored property.",
        "Property wrapper — тип із var wrappedValue, який інкапсулює логіку зберігання; @State, @Published, @AppStorage — усе це property wrappers. projectedValue (доступ через $) дає додаткове представлення — наприклад, Binding у SwiftUI.",
      ],
      problem: "lazy вирішує проблему дорогої ініціалізації, яка може не знадобитись (важкий DateFormatter, обчислення на великих даних). Observers — проблему «тримати щось синхронним зі значенням» без ручних викликів (оновити UI при зміні моделі). Wrappers — проблему копіпасти навколо зберігання (та сама логіка UserDefaults для 20 налаштувань — один wrapper замість 20 однакових get/set).",
      where: [
        "lazy var formatter: DateFormatter — класика: формуттери дорогі, створюємо один раз при першому використанні.",
        "didSet на властивості ViewModel/клітинки: var order: Order? { didSet { updateUI() } } — типовий патерн конфігурації UITableViewCell.",
        "@UserDefault(\"onboarding_shown\") var shown: Bool — свій wrapper для налаштувань (поширене питання «напишіть property wrapper»).",
        "Computed для похідних даних: var fullPrice: Decimal { items.reduce(0) { $0 + $1.price } } — завжди актуальне, немає ризику розсинхрону.",
      ],
      code: [
        "@propertyWrapper struct UserDefault<T> {",
        "    let key: String; let defaultValue: T",
        "    var wrappedValue: T {",
        "        get { UserDefaults.standard.object(forKey: key) as? T ?? defaultValue }",
        "        set { UserDefaults.standard.set(newValue, forKey: key) }",
        "    }",
        "}",
        "struct Settings {",
        "    @UserDefault(key: \"isDark\", defaultValue: false) static var isDark: Bool",
        "}",
      ],
      traps: [
        "lazy НЕ потокобезпечний: два потоки при першому звертанні можуть ініціалізувати двічі. І lazy — тільки var.",
        "willSet/didSet не викликаються під час init (пряме присвоєння у сховище) — частий сюрприз.",
        "Computed property обчислюється при КОЖНОМУ звертанні — дорогий обрахунок у ньому в циклі = просідання.",
        "didSet, який присвоює цю ж властивість — рекурсії не буде (спрацює лише раз), але код заплутаний.",
      ],
      qs: [
        "Чим lazy var відрізняється від computed property за кількістю обчислень і памʼяттю?",
        "Чому didSet не викликається з ініціалізатора і як усе-таки виконати логіку?",
        "Напиши property wrapper @Clamped(0...100) для відсотків.",
        "Що таке projectedValue і що повертає $ у @Published/@State?",
      ],
    },
    {
      p: "P0", name: "Closures і capture semantics",
      what: [
        "Closure — блок коду першого класу, який можна зберігати і передавати. Це reference-тип: він живе в купі й захоплює (capture) змінні з контексту створення. var захоплюється за посиланням — closure бачить актуальне значення і може його змінювати. Capture list ([x], [weak self]) — копіює значення/послаблює посилання В МОМЕНТ СТВОРЕННЯ closure.",
        "@escaping — closure переживає виклик функції (зберігається, викликається пізніше — completion handlers). Non-escaping (за замовчуванням) виконується до повернення функції, тому не вимагає self і не створює циклів.",
      ],
      problem: "Closures вирішують проблему «передати поведінку як дані»: колбеки завершення асинхронних операцій, конфігурація (map/filter), відкладене виконання. Capture list вирішує дві проблеми: retain cycle (closure тримає self, а self тримає closure) і «захоплення останнього значення» у циклах.",
      where: [
        "Completion handlers мережевих запитів (до async/await, і досі в legacy): fetchOrders { [weak self] result in ... }.",
        "Колбеки UI: кнопка в клітинці повідомляє контролер через var onTap: (() -> Void)? — стандартний патерн у твоєму UIKit-коді.",
        "Функціональні операції: orders.filter { $0.isActive }.map(\\.id).",
        "DispatchQueue.main.async { }, анімації UIView.animate — усюди closures.",
      ],
      code: [
        "var handlers: [() -> Void] = []",
        "for i in 1...3 {",
        "    handlers.append { print(i) }          // 1 2 3 — for створює нову константу i",
        "}",
        "var x = 0",
        "let a = { print(x) }                      // захоплення за посиланням",
        "let b = { [x] in print(x) }               // копія на момент створення",
        "x = 99",
        "a() // 99        b() // 0",
      ],
      traps: [
        "Retain cycle: self.completion = { self.doSomething() } — self тримає closure, closure тримає self. Розрив: [weak self].",
        "[weak self] робить self опціональним усередині — guard let self else { return } на початку.",
        "unowned self — креш, якщо closure викличеться після смерті self. Тільки коли життя closure гарантовано коротше за self.",
        "[weak self] не потрібен там, де closure не зберігається надовго: разовий DispatchQueue.main.async лише відкладе звільнення на мить — це не цикл.",
      ],
      qs: [
        "Що виведе код вище і чому a() та b() дають різні результати?",
        "Чому @escaping вимагає явного self? Що перевіряє компілятор?",
        "Namaлюй retain cycle через closure і два способи розірвати.",
        "Коли [weak self] зайвий і лише додає шуму?",
      ],
    },
    {
      p: "P0", name: "ARC, memory management, retain cycles",
      what: [
        "ARC (Automatic Reference Counting) — компілятор на етапі збірки вставляє retain/release виклики. Кожен обʼєкт має лічильник сильних посилань; коли він падає до нуля — deinit і звільнення. На відміну від garbage collection: детерміновано (обʼєкт помирає одразу), без пауз збирача, але не вміє розривати цикли — це відповідальність розробника.",
        "weak — не збільшує лічильник, автоматично стає nil після смерті обʼєкта (тому завжди optional var). unowned — не збільшує лічильник, але НЕ обнуляється: звертання після смерті = креш. strong — за замовчуванням.",
      ],
      problem: "Вирішує проблему ручного керування памʼяттю (retain/release руками в старому Obj-C — джерело крешів і ліків). Retain cycle — головна ціна: два обʼєкти тримають один одного сильно, лічильники ніколи не впадуть до нуля, память тече. У великому застосунку типовий симптом — контролер не деінітиться і продовжує слухати нотифікації/оновлювати дані.",
      where: [
        "delegate завжди weak var delegate: SomeDelegate? — інакше цикл: VC тримає tableView, tableView тримає delegate (VC).",
        "closure + self — див. тему closures; це 90% реальних ліків.",
        "Timer.scheduledTimer(target: self) — RunLoop тримає таймер, таймер СИЛЬНО тримає target. Не інвалідував таймер — VC живе вічно.",
        "Батько-дитина: батько тримає дітей strong, дитина батька — weak (view ієрархії, координатори).",
      ],
      code: [
        "final class OrderVC: UIViewController {",
        "    var timer: Timer?",
        "    override func viewDidLoad() {",
        "        super.viewDidLoad()",
        "        timer = Timer.scheduledTimer(withTimeInterval: 5, repeats: true) { [weak self] _ in",
        "            self?.refreshStatus()     // block-based API + weak — циклу немає",
        "        }",
        "    }",
        "    deinit { timer?.invalidate(); print(\"OrderVC deinit\") } // лог = перевірка ліків",
        "}",
      ],
      traps: [
        "weak тільки для класів (reference-типів) — на struct не повісиш.",
        "NotificationCenter.addObserver(forName:...) з closure повертає токен — його треба зберігати і знімати; сам closure легко захоплює self.",
        "unowned виглядає «чистіше» (без optional), але один неправильний прогноз часу життя = креш у проді. Сумніваєшся — weak.",
        "Пошук ліків: Debug Memory Graph (кнопка в Xcode) показує, ХТО тримає обʼєкт; Instruments → Leaks/Allocations; найпростіше — print у deinit.",
      ],
      qs: [
        "Як ARC відрізняється від garbage collection — плюси й мінуси?",
        "Таблиця strong/weak/unowned: чи тримає, чи optional, що при звертанні до мертвого?",
        "Чому delegate — weak? Що станеться, якщо зробити strong?",
        "Як ти шукав/шукав би memory leak у реальному проєкті — покроково?",
      ],
    },
    {
      p: "P0", name: "GCD і класична багатопотоковість",
      what: [
        "GCD (Grand Central Dispatch) — API черг задач поверх пулу потоків. Serial черга виконує задачі по одній у порядку додавання; concurrent — кілька одночасно. main — serial черга головного потоку (весь UI). Global-черги — concurrent, з рівнями QoS: userInteractive > userInitiated > utility > background — система розподіляє ресурси за пріоритетом.",
        "async — «поклади задачу і не чекай»; sync — «поклади і заблокуйся до завершення». DispatchGroup — дочекатися групи задач; barrier — задача-«шлюз» у concurrent черзі: чекає всі попередні, виконується сама, потім пускає наступні (патерн readers-writers).",
      ],
      problem: "Вирішує дві проблеми: (1) не блокувати main thread важкою роботою — інакше фризи UI і креш від watchdog; (2) керувати паралелізмом без ручного створення потоків. Race condition — коли результат залежить від порядку виконання потоків; data race — одночасний неатомарний доступ до памʼяті (мінімум один запис) — це UB, ловиться Thread Sanitizer.",
      where: [
        "Класичний сендвіч: DispatchQueue.global().async { важка робота } → DispatchQueue.main.async { оновити UI }.",
        "Декодування великого JSON, ресайз картинок, робота з диском — усе поза main.",
        "DispatchGroup: зібрати 3 запити (меню + промо + профіль) і показати екран, коли ВСІ готові — твій реальний кейс на home page.",
        "Serial черга як памʼятка синхронізації: усі звертання до спільного кеша через одну serial чергу = потокобезпечність без локів.",
      ],
      code: [
        "let group = DispatchGroup()",
        "var menu: Menu?; var promos: [Promo] = []",
        "group.enter(); api.fetchMenu   { menu = $0;   group.leave() }",
        "group.enter(); api.fetchPromos { promos = $0; group.leave() }",
        "group.notify(queue: .main) { self.render(menu, promos) }",
        "",
        "// Потокобезпечний доступ: concurrent + barrier",
        "queue.async(flags: .barrier) { self.cache[key] = value }  // запис — ексклюзивно",
        "queue.sync { return self.cache[key] }                     // читання — паралельно",
      ],
      traps: [
        "DispatchQueue.main.sync { } з main thread = миттєвий deadlock: main чекає задачу, яка чекає main. Питання №1 на співбесідах.",
        "sync на будь-якій serial черзі зсередини неї самої — той самий deadlock.",
        "Забутий group.leave() (наприклад, у гілці помилки) — notify не спрацює ніколи.",
        "GCD не скасовує задачі, що вже виконуються; DispatchWorkItem.cancel() — лише прапорець isCancelled. Потрібне справжнє скасування/залежності — OperationQueue або Swift Concurrency.",
      ],
      qs: [
        "Що станеться при DispatchQueue.main.sync {} з main thread — і чому саме?",
        "Serial vs concurrent, sync vs async — чотири комбінації, поясни кожну.",
        "Як завантажити 3 ресурси паралельно і оновити UI, коли всі готові — GCD і async/await варіанти?",
        "Race condition vs data race — різниця? Як ловити (TSan)?",
      ],
    },
    {
      p: "P0", name: "Swift Concurrency: async/await, actors, Sendable",
      what: [
        "async/await — синтаксис для асинхронності без колбеків: await позначає suspension point, де функція може «заснути», звільнивши потік для іншої роботи (кооперативний пул потоків ≈ кількість ядер; потоки не блокуються). Task { } — міст із синхронного світу в асинхронний; structured concurrency (async let, TaskGroup) — дочірні задачі не переживають батьківську область, скасування поширюється автоматично.",
        "actor — reference-тип, який серіалізує доступ до свого стану: одночасно всередині виконується лише один виклик, data race неможливий за визначенням. @MainActor — глобальний актор головного потоку: вішається на клас/метод, і компілятор гарантує виконання на main. Sendable — маркер «тип безпечно передавати між потоками»; у Swift 6 strict concurrency компілятор перевіряє це на етапі збірки.",
      ],
      problem: "Вирішує: (1) callback hell і забуті completion(...) у гілках помилок — лінійний код з try/await читається як синхронний; (2) data races — actors та Sendable переносять помилки конкурентності з рантайму (найважчі в дебагу баги) у compile time; (3) скасування — Task.cancel() поширюється деревом задач, GCD такого не має.",
      where: [
        "Мережевий шар: let (data, response) = try await session.data(for: request) — сучасний стандарт, у тебе на роботі так.",
        "Паралельні незалежні запити: async let menu = api.menu(); async let promos = api.promos(); let page = try await (menu, promos).",
        "@MainActor на ViewModel — усі @Published/стан оновлюються на main без ручних DispatchQueue.main.async.",
        "AsyncStream — обгортка над делегатами/нотифікаціями: стрім оновлень геолокації, статусів замовлення (твої Live Activities поруч із цим).",
        "withCheckedThrowingContinuation — обгортання старого callback-API (Firebase, сторонні SDK) в async.",
      ],
      code: [
        "func loadImages(urls: [URL]) async throws -> [UIImage] {",
        "    try await withThrowingTaskGroup(of: UIImage.self) { group in",
        "        for url in urls {",
        "            group.addTask { try await self.download(url) }   // паралельно",
        "        }",
        "        var result: [UIImage] = []",
        "        for try await image in group { result.append(image) }",
        "        return result",
        "    }",
        "}",
        "",
        "actor ImageCache {",
        "    private var storage: [URL: UIImage] = [:]",
        "    func image(for url: URL) -> UIImage? { storage[url] }   // доступ серіалізовано",
        "    func insert(_ img: UIImage, for url: URL) { storage[url] = img }",
        "}",
      ],
      traps: [
        "Actor reentrancy: під час await усередині actor-метода інший виклик може зайти і змінити стан — інваріанти перевіряй ПІСЛЯ await заново.",
        "Task { } успадковує актор-контекст місця створення; Task.detached — ні (і пріоритет теж). Detached — майже завжди неправильний вибір.",
        "Скасування кооперативне: якщо код не перевіряє Task.isCancelled / не викликає try Task.checkCancellation() — він виконається до кінця попри cancel().",
        "async let без await результату — задача все одно виконається і буде скасована при виході з області; try await обовʼязково для throwing.",
        "Блокувати потік з async-контексту (semaphore.wait, sleep) — забирає потік з кооперативного пулу, ризик starvation.",
      ],
      qs: [
        "Чим async let відрізняється від послідовних await і від TaskGroup — коли що?",
        "Що таке actor reentrancy і який баг вона може створити? Приклад.",
        "Як мігрувати метод з completion handler на async/await через continuation?",
        "Чому await у actor-методі — «діра» для зміни стану і як з цим жити?",
        "Що перевіряє Swift 6 strict concurrency і що таке Sendable?",
      ],
    },
    {
      p: "P0", name: "Protocols і Protocol-Oriented Programming",
      what: [
        "Протокол — контракт вимог (методи, властивості, associated types). Protocol extension дає реалізації за замовчуванням — так будується POP: спільна поведінка через композицію протоколів замість ієрархії класів. Струкrypи можуть підкорятися багатьом протоколам — «множинне успадкування поведінки» без класів.",
        "some Protocol (opaque type) — конкретний тип, відомий компілятору, але прихований від читача: статичний dispatch, нуль накладних витрат. any Protocol (existential) — «коробка», у якій може лежати будь-який тип, що підкоряється: динамічний dispatch, боксинг, повільніше. Правило: some де можливо, any де потрібна справжня гетерогенність.",
      ],
      problem: "Вирішує жорсткість класового успадкування: один базовий клас, глибокі ієрархії, «god object» нагорі. І головне для практики — розвʼязування залежностей: код залежить від абстракції (протоколу), а не конкретного типу, що робить його тестованим (підміна мока) і замінюваним (переїхали з одного SDK на інший — переписали одну реалізацію).",
      where: [
        "DI + тестування — головний практичний кейс: protocol OrderServiceProtocol { func fetchOrders() async throws -> [Order] }; ViewModel приймає протокол, у тестах — MockOrderService. Це закриває твій геп у тестуванні.",
        "Твій мережевий шар: типізовані запити — це протокол Endpoint з associated type відповіді.",
        "Delegate-патерн UIKit — протоколи (UITableViewDataSource).",
        "Стандартна бібліотека: Equatable, Hashable, Codable, Sequence — усе протоколи; кастомний тип у Set вимагає Hashable.",
      ],
      code: [
        "protocol OrderService {",
        "    func fetchOrders() async throws -> [Order]",
        "}",
        "struct APIOrderService: OrderService { /* реальні запити */ }",
        "struct MockOrderService: OrderService {",
        "    var stub: [Order] = []",
        "    func fetchOrders() async throws -> [Order] { stub }",
        "}",
        "// Пастка static dispatch у extension:",
        "protocol Greeter { }               // метод НЕ оголошений у протоколі",
        "extension Greeter { func hi() -> String { \"proto\" } }",
        "struct Kyiv: Greeter { func hi() -> String { \"kyiv\" } }",
        "let g: Greeter = Kyiv()",
        "g.hi()   // \"proto\"! — метод не в вимогах → static dispatch за типом змінної",
      ],
      traps: [
        "Класика-пастка (у коді вище): метод, оголошений ТІЛЬКИ в extension протоколу, диспатчиться статично за типом змінної. Додай метод у вимоги протоколу — стане динамічним і поверне \"kyiv\".",
        "any Protocol має ціну: existential container, непрямі виклики. У гарячих місцях і колекціях краще generic constraint.",
        "Протокол з associated type до Swift 5.7 не можна було використовувати як тип — тільки як constraint; тепер any/some це помʼякшили (primary associated types).",
        "Протокол для делегата має бути AnyObject (class-only) — інакше weak не повісиш.",
      ],
      qs: [
        "Пастка: метод тільки в extension протоколу — що викличеться через змінну типу протоколу і чому?",
        "some vs any: різниця в dispatch, перформансі, можливостях? Чому SwiftUI повертає some View?",
        "Як протоколи роблять ViewModel тестованим — покажи на прикладі мока мережі.",
        "POP vs успадкування: наведи приклад рефакторингу ієрархії на протоколи.",
      ],
    },
    {
      p: "P1", name: "Generics",
      what: [
        "Generics — параметризація коду типами: func max<T: Comparable>(_ a: T, _ b: T) -> T працює для будь-якого порівнюваного типу, зберігаючи типобезпеку (на виході саме T, не Any). Constraints (T: Codable, where Element == String) звужують можливості до потрібних. Компілятор спеціалізує generic-код під конкретні типи — на виході швидкий мономорфний код без боксингу.",
        "Conditional conformance: «масив Equatable-елементів сам Equatable» — extension Array: Equatable where Element: Equatable. Primary associated types (Swift 5.7): some Collection<String>.",
      ],
      problem: "Вирішує дилему «дублювати код під кожен тип чи втратити типи через Any». До generics контейнери або писались під один тип, або повертали Any з кастами в рантаймі (і крешами). Generics дають одночасно перевикористання І compile-time безпеку І перформанс.",
      where: [
        "Твій мережевий шар — найкращий приклад на співбесіді: func request<T: Decodable>(_ endpoint: Endpoint) async throws -> T — один метод декодує будь-яку модель.",
        "Уся стандартна бібліотека: Array<Element>, Dictionary<Key, Value>, Optional<Wrapped>, Result<Success, Failure>.",
        "Generic-репозиторій/сховище: save<T: Encodable>(_ value: T, key: String).",
        "SwiftUI повсюдно: ForEach<Data, ID, Content>, Button<Label>.",
      ],
      code: [
        "struct Endpoint<Response: Decodable> {",
        "    let path: String",
        "    let method: HTTPMethod",
        "}",
        "extension Endpoint {",
        "    static var orders: Endpoint<[Order]> { .init(path: \"/orders\", method: .get) }",
        "}",
        "func request<R>(_ endpoint: Endpoint<R>) async throws -> R {",
        "    let (data, _) = try await session.data(for: makeURLRequest(endpoint))",
        "    return try decoder.decode(R.self, from: data)",
        "}",
        "let orders = try await request(.orders)   // тип виведено: [Order]",
      ],
      traps: [
        "Generic-параметр фіксується на момент виклику — не можна в один [T] покласти різні типи (для цього existential any).",
        "Занадто загальні констрейнти → нечитабельні сигнатури; іноді простіше два перевантаження.",
        "Стирання типів: коли треба зберегти «будь-який Endpoint» у масиві — потрібен type erasure або any.",
      ],
      qs: [
        "Напиши generic-функцію пошуку максимального елемента з constraint.",
        "Чим generic параметр відрізняється від any Protocol за перформансом (спеціалізація vs existential)?",
        "Розкажи, як влаштований типізований запит у вашому мережевому шарі.",
        "Що таке conditional conformance? Приклад зі стандартної бібліотеки.",
      ],
    },
    {
      p: "P1", name: "Enums, pattern matching, error handling",
      what: [
        "Swift enum — повноцінний тип: методи, computed properties, generic-параметри. Associated values прикріплюють дані до кейса — case loaded([Order]), case failed(APIError); switch змушує обробити ВСІ кейси (exhaustiveness) — додав кейс, компілятор покаже всі місця, які треба оновити.",
        "Error handling: функція позначається throws, помилка кидається throw, ловиться do/catch. try? перетворює помилку на nil, try! — на креш. rethrows — функція кидає, лише якщо кидає передане їй closure (map, filter). defer — блок, що виконається при БУДЬ-ЯКОМУ виході з області (кілька defer — у зворотному порядку).",
      ],
      problem: "Enum з associated values вирішує проблему неможливих станів: замість isLoading: Bool + error: Error? + data: [Order]? (де можливі безглузді комбінації «і завантажується, і помилка») — один enum, де стан рівно один. Це прибирає цілий клас багів ще на етапі моделювання.",
      where: [
        "Стан екрана: enum ScreenState { case idle, loading, loaded([Order]), failed(String) } — і SwiftUI/UIKit рендерить switch-ом.",
        "Помилки API: enum APIError: Error { case unauthorized, server(code: Int), decoding } — твій мережевий шар з централізованою обробкою помилок робить саме це.",
        "Маршрути дип-лінків: enum DeepLink { case order(id: String), restaurant(id: String), promo(code: String) } — парсинг URL в enum, далі типобезпечна навігація (твій робочий кейс).",
        "Result<T, E> — там, де async/await недоступний: колбеки, збереження результату для повторної обробки.",
      ],
      code: [
        "enum ScreenState {",
        "    case loading",
        "    case loaded([Order])",
        "    case failed(message: String)",
        "}",
        "func render(_ state: ScreenState) {",
        "    switch state {",
        "    case .loading: showSpinner()",
        "    case .loaded(let orders) where orders.isEmpty: showEmptyView()",
        "    case .loaded(let orders): show(orders)",
        "    case .failed(let message): showError(message)",
        "    }",
        "}",
        "if case .loaded(let orders) = state { print(orders.count) } // один кейс без switch",
      ],
      traps: [
        "@unknown default для системних enum (нові кейси в нових iOS — код не зламається, але warning підкаже).",
        "Indirect enum для рекурсивних структур (дерево категорій меню) — без indirect не скомпілюється (нескінченний розмір).",
        "try? ковтає ПРИЧИНУ помилки — для дебагу продакшн-багів краще do/catch з логуванням.",
        "raw value vs associated value — взаємовиключні; rawValue зручний для парсингу з бекенда (enum Status: String, Codable).",
      ],
      qs: [
        "Змоделюй стан екрана через enum — чому це краще за три окремі властивості?",
        "Що робить rethrows і де він у стандартній бібліотеці (map)?",
        "Порядок виконання трьох defer у функції?",
        "Як ти парсиш дип-лінки — розкажи про enum маршрутів.",
      ],
    },
    {
      p: "P2", name: "Method dispatch: static, table, message",
      what: [
        "Три механізми виклику методу. Static (direct) — адреса відома на компіляції: усі методи struct/enum, final-методи, private, методи в extension. Найшвидший, дозволяє інлайнінг. Table (vtable/witness table) — адреса береться з таблиці за індексом у рантаймі: звичайні методи класів (можливий override), вимоги протоколів. Message dispatch — пошук селектора через Objective-C runtime: @objc dynamic методи; найповільніший, але дає магію — KVO, method swizzling, target-action.",
      ],
      problem: "Розуміння dispatch пояснює «дивну» поведінку (пастка з extension протоколу), чому final/private прискорюють код (компілятор девіртуалізує та інлайнить), і чому KVO вимагає @objc dynamic (KVO в рантаймі підміняє клас і перехоплює сеттер — можливо лише з message dispatch).",
      where: [
        "final class / final func на класах, які не успадковуються — безкоштовна оптимізація і явний намір.",
        "@objc dynamic — коли потрібен KVO (спостереження за AVPlayer.status), UIAppearance.",
        "Розуміння пастки protocol extension (див. тему протоколів) — це питання саме про dispatch.",
      ],
      code: [
        "class Animal {",
        "    func sound() { }          // table dispatch — можна override",
        "    final func id() { }       // static — override заборонено, інлайниться",
        "    @objc dynamic var name = \"\" // message — видно KVO і swizzling",
        "}",
        "extension Animal {",
        "    func walk() { }           // static! override у нащадку НЕ спрацює як очікуєш",
        "}",
      ],
      traps: [
        "Метод у extension класу — static dispatch: «перевизначення» у сабкласі не викличеться через посилання на базовий тип.",
        "Той самий ефект у protocol extension без оголошення методу в протоколі.",
        "dynamic без потреби — втрата оптимізацій на рівному місці.",
      ],
      qs: [
        "Чому KVO вимагає @objc dynamic — що робить рантайм?",
        "Який dispatch у методу з extension класу і яку проблему це створює?",
        "Як final допомагає компілятору оптимізувати?",
      ],
    },
    {
      p: "P1", name: "Колекції та функціональні операції",
      what: [
        "map — перетворити кожен елемент (O(n)); compactMap — map + викинути nil; flatMap — map + сплющити вкладені колекції; filter — відібрати; reduce — згорнути в одне значення; sorted — O(n log n). Ланцюги операцій читаються як опис «що зробити», а не «як ітерувати».",
        "Sequence — можна ітерувати (можливо, одноразово і нескінченно); Collection — багаторазова, з індексами і count. .lazy відкладає обчислення: ланцюг lazy.map.filter не створює проміжних масивів і обчислює лише те, що спожито — виграш на великих даних з first(where:).",
        "Складності: Array — доступ за індексом O(1), insert(at: 0) O(n); Set/Dictionary — contains/lookup O(1) середнє (хешування); Array.contains — O(n).",
      ],
      problem: "Функціональні операції вирішують проблему «шумних» циклів з мутабельними акумуляторами: менше місць для off-by-one і забутих умов, наміри видно одразу. Знання складностей вирішує проблеми перформансу: перевірка входження в Array у циклі — O(n²), яка на 10 000 елементів вже помітна; заміна на Set — O(n).",
      where: [
        "Трансформація DTO → доменні моделі: response.items.map(Order.init).",
        "compactMap для «безпечного» парсингу: strings.compactMap(URL.init) — невалідні просто відпадають.",
        "reduce для агрегації: сума кошика items.reduce(0) { $0 + $1.price * Decimal($1.qty) } — твій CartTotals по суті це робить.",
        "Set для швидких перевірок: обрані ресторани favoriteIDs: Set<String> замість масиву.",
      ],
      code: [
        "let ids = orders.map(\\.id)                       // KeyPath замість closure",
        "let urls = strings.compactMap(URL.init)           // невалідні відпали",
        "let total = cart.reduce(Decimal(0)) { $0 + $1.price }",
        "",
        "// lazy: перший підходящий без обробки всього масиву",
        "let first = hugeArray.lazy",
        "    .map(expensiveTransform)",
        "    .first { $0.isValid }",
      ],
      traps: [
        "flatMap на Optional-масивах історично перейменували в compactMap — на співбесіді люблять питати різницю.",
        "Ланцюг map.filter.map на великому масиві створює проміжні масиви — lazy або один прохід reduce.",
        "Hashable-контракт: рівні обʼєкти зобовʼязані мати рівний hash. Зламаєш (нестабільний hash) — Set/Dictionary поводяться непередбачувано.",
        "Мутація колекції під час ітерації — креш/UB; збирай зміни окремо.",
      ],
      qs: [
        "flatMap vs compactMap — різниця та історія?",
        "Складність contains у Array vs Set — і коли це реально важливо?",
        "Коли lazy-ланцюг виграє, а коли він марний (споживаєш все одно все)?",
        "Реалізуй reduce через цикл і суму словника через reduce.",
      ],
    },
    {
      p: "P1", name: "Codable глибоко",
      what: [
        "Codable = Decodable + Encodable. Компілятор синтезує реалізацію автоматично, якщо всі властивості Codable. CodingKeys — enum відповідності імен властивостей ключам JSON; keyDecodingStrategy = .convertFromSnakeCase — глобальна конвертація. Повний контроль — кастомний init(from decoder:): контейнери (keyed/unkeyed/singleValue), nested containers для вкладених структур.",
      ],
      problem: "Вирішує ручний парсинг JSON (гори if let json[\"key\"] as? String — багатослівно і криво з помилками). Codable дає декларативний, типобезпечний парсинг з детальними помилками (DecodingError вкаже точний шлях до поля, що не спарсилось).",
      where: [
        "Кожна модель API у твоєму проєкті. Date через dateDecodingStrategy (.iso8601 або кастомний формуттер — бекенди люблять свої формати).",
        "Поле, що буває String або Int (класика реальних бекендів) — кастомний init з послідовними спробами декодування.",
        "Стійкість до сміття в масивах: обгортка FailableDecodable, щоб один битий елемент не валив увесь список (критично для стрічок/каталогів).",
        "Кеш на диску: JSONEncoder у файл — швидкий офлайн-стан без Core Data.",
      ],
      code: [
        "struct Order: Decodable {",
        "    let id: String",
        "    let total: Decimal",
        "    let promoCode: String?          // немає в JSON → nil, без помилки",
        "    enum CodingKeys: String, CodingKey {",
        "        case id = \"order_id\", total, promoCode = \"promo_code\"",
        "    }",
        "}",
        "// String або Int в одному полі:",
        "struct FlexibleID: Decodable {",
        "    let value: String",
        "    init(from decoder: Decoder) throws {",
        "        let c = try decoder.singleValueContainer()",
        "        if let s = try? c.decode(String.self) { value = s }",
        "        else { value = String(try c.decode(Int.self)) }",
        "    }",
        "}",
      ],
      traps: [
        "Оголосив CodingKeys — автосинтез покриває лише перелічені ключі; пропустив властивість без дефолту — помилка компіляції.",
        "decodeIfPresent vs decode для optional: decode(String?.self) впаде, якщо КЛЮЧА немає; decodeIfPresent — поверне nil.",
        "DecodingError має 4 кейси (typeMismatch, valueNotFound, keyNotFound, dataCorrupted) з context.codingPath — навчись читати, це твій дебаг продакшн-парсингу.",
        "Дефолтні значення при відсутньому ключі автосинтез НЕ дає (var x = 0 не допоможе) — потрібен кастомний init або property wrapper.",
      ],
      qs: [
        "JSON з полем String-або-Int — як задекодити? Напиши init(from:).",
        "Як пропустити невалідні елементи масиву, не заваливши весь декодинг?",
        "decode vs decodeIfPresent — різниця?",
        "Як ти дебажиш DecodingError з продакшну — що в codingPath?",
      ],
    },
    {
      p: "P2", name: "Init, access control, KeyPath, type erasure",
      what: [
        "Ініціалізатори класів: designated (повна ініціалізація) і convenience (делегує designated). Two-phase init: фаза 1 — усі stored properties отримали значення знизу вгору по ієрархії; фаза 2 — можна чіпати self. failable init? повертає nil при невалідних даних. required — усі нащадки зобовʼязані реалізувати.",
        "Access control: private (тип+extensions у файлі) < fileprivate (файл) < internal (модуль, дефолт) < public (видно ззовні) < open (ще й можна успадковувати/override ззовні). private(set) — читати можна всім, писати лише всередині.",
        "KeyPath \\User.name — типізоване посилання на властивість як значення. Type erasure — приховування конкретного типу за обгорткою (AnyPublisher, AnyView): коли протокол з associated type не можна використати як тип напряму.",
      ],
      problem: "Two-phase init гарантує, що обʼєкт не використовується напівзібраним (звертання до self до ініціалізації всіх полів — помилка компіляції). Access control — інкапсуляція: private(set) var state дає читання ззовні, а мутацію лише власнику — менше місць, де стан може зламатись. Type erasure вирішує «protocol ... can only be used as a generic constraint».",
      where: [
        "init?(rawValue:) в enum; init? для валідації (User з порожнім імʼям — nil).",
        "private(set) у ViewModel: private(set) var orders: [Order] — View читає, змінює лише VM.",
        "KeyPath у API колекцій: map(\\.id), sorted(by: \\.createdAt) — і в SwiftUI (ForEach(items, id: \\.id)).",
        "open vs public — актуально для бібліотек/SDK: public клас ззовні НЕ можна сабкласити, open — можна.",
      ],
      code: [
        "final class OrderViewModel {",
        "    private(set) var orders: [Order] = []     // ззовні read-only",
        "    private let service: OrderService",
        "    init(service: OrderService) { self.service = service }  // DI через init",
        "}",
        "let names = users.map(\\.name)                 // KeyPath",
        "let adults = users.filter { $0.age >= 18 }",
      ],
      traps: [
        "У фазі 1 init класу не можна викликати методи self чи читати властивості — «self used before super.init».",
        "convenience init не може ініціалізувати stored properties напряму — тільки делегувати.",
        "private у Swift дозволяє доступ з extension того самого типу В ТОМУ Ж файлі — мʼякший за «private» в інших мовах.",
      ],
      qs: [
        "Чим open відрізняється від public — і навіщо ця різниця бібліотекам?",
        "Що таке two-phase initialization і які помилки він ловить?",
        "Що таке type erasure, навіщо AnyView/AnyPublisher? Яку проблему з associated types це обходить?",
        "Навіщо private(set) у ViewModel?",
      ],
    },
    {
      p: "P1", name: "Типи даних углиб: struct, class, enum, tuple",
      what: [
        "Struct: отримує memberwise init безкоштовно (Point(x: 1, y: 2) безписання init руками — але будь-який кастомний init в тілі структури його вимикає). Методи, що змінюють властивості, позначаються mutating — під капотом вони отримують новий self (метод неявно приймає inout self). Свій Copy-on-Write будується через клас-буфер усередині структури + isKnownUniquelyReferenced(&buffer): якщо буфер тримає хтось ще — копіюємо перед мутацією.",
        "Class: єдиний тип з успадкуванням і deinit. Ідентичність перевіряється оператором === (той самий обʼєкт у памʼяті), а рівність — == (той самий вміст, вимагає Equatable). Два різні обʼєкти можуть бути == але не ===. required init — зобовʼязує сабкласи; convenience init — делегує до designated.",
        "Tuple: легка анонімна група значень — (min: 3, max: 10). Це value-тип без імені: не може мати методів, не підкоряється протоколам (не буде Codable/Equatable у своєму API), не може бути рекурсивним. Правило: tuple — для локального повернення двох-трьох значень з функції; щойно тип перетинає межу файлу/шару або потребує логіки — перетворюй на struct.",
        "Nested types — типи всередині типів для простору імен: Order.Status краще за OrderStatus (звʼязок видно з імені). typealias — синонім типу: typealias Completion = (Result<Order, APIError>) -> Void прибирає шум у сигнатурах. Any — будь-який тип узагалі (включно зі struct і функціями), AnyObject — лише class-типи (тому протоколи делегатів позначають AnyObject, щоб можна було weak).",
      ],
      problem: "Ця тема вирішує проблему вибору інструмента: коли struct, коли class, коли вистачить tuple. Неправильний вибір коштує дорого пізніше: моделі на класах дають несподівані спільні мутації, tuple-и, що розповзлись по шарах — неможливість додати метод чи conformance без глобального рефакторингу, а Any у публічних API — втрату типобезпеки і касти в рантаймі.",
      where: [
        "Свій COW — питання на співбесідах рівня middle+: «як зробити великий value-тип дешевим у копіюванні» — показуєш буфер-клас + isKnownUniquelyReferenced.",
        "=== використовується у кастомному Equatable для класів (спершу швидка перевірка ідентичності, потім полів) і в тестах — перевірити, що це САМЕ той інстанс (наприклад, синглтон або той самий делегат).",
        "Tuple щодня: повернення пари з функції — func minMax(_ a: [Int]) -> (min: Int, max: Int), координати, результат enumerated() у циклі.",
        "Nested types у моделях: Order.Status, Order.Payment — типовий стиль чистих доменних моделей; у твоєму проєкті так природно лягають статуси замовлення.",
        "AnyObject — обмеження протоколу делегата (protocol CartDelegate: AnyObject), без нього weak var delegate не скомпілюється.",
      ],
      code: [
        "// COW своїми руками:",
        "final class Buffer { var data: [Int] = [] }",
        "struct BigValue {",
        "    private var buffer = Buffer()",
        "    var data: [Int] { buffer.data }",
        "    mutating func append(_ x: Int) {",
        "        if !isKnownUniquelyReferenced(&buffer) {",
        "            buffer = Buffer(); // копія лише коли буфер спільний",
        "        }",
        "        buffer.data.append(x)",
        "    }",
        "}",
        "",
        "// Ідентичність vs рівність:",
        "class User: Equatable {",
        "    let id: String; init(id: String) { self.id = id }",
        "    static func == (l: User, r: User) -> Bool { l === r || l.id == r.id }",
        "}",
        "",
        "// Tuple: добре локально…",
        "func minMax(_ a: [Int]) -> (min: Int, max: Int)? {",
        "    guard let f = a.first else { return nil }",
        "    return a.dropFirst().reduce((f, f)) { (Swift.min($0.0, $1), Swift.max($0.1, $1)) }",
        "}",
      ],
      traps: [
        "Кастомний init у ТІЛІ структури вимикає memberwise init; той самий init у extension — зберігає обидва. Тому кастомні ініціалізатори структур пишуть в extension.",
        "mutating-метод на let-структурі — помилка компіляції; властивість-структура всередині класу, оголошена let — теж незмінна, навіть якщо клас var.",
        "Tuple з іменами і без — сумісні за позицією: (min: 3, max: 5) можна присвоїти у (Int, Int) — імена загубляться мовчки.",
        "Порівняння tuple-ів працює лише до 6 елементів (обмеження стандартної бібліотеки) і лише якщо всі елементи Comparable/Equatable.",
        "Any ховає навіть Optional: масив [Any] може містити nil як Optional<T>.none — і as? розгортання дає сюрпризи. Побачив Any у своєму API — подумай ще раз.",
        "deinit не викликається детерміновано при крешах/exit(0) — не клади туди критичне збереження даних.",
      ],
      qs: [
        "Коли зникає memberwise init і як зберегти його разом із кастомним?",
        "Напиши COW-обгортку: що робить isKnownUniquelyReferenced і чому параметр inout?",
        "=== vs == — різниця? Чи можуть два обʼєкти бути == але не ===?",
        "Коли tuple стає боргом і його час міняти на struct? Назви три обмеження tuple.",
        "Any vs AnyObject — різниця, і чому протокол делегата має бути AnyObject?",
      ],
    },
    {
      p: "P1", name: "ООП: інкапсуляція, успадкування, поліморфізм, абстракція",
      what: [
        "Обʼєктно-орієнтоване програмування у Swift базується на принципах інкапсуляції, успадкування, поліморфізму та абстракції.",
      ],
      sections: [
        {
          title: "1. Інкапсуляція",
          text: "Обʼєднання даних (властивостей) і методів в одному типі, а також обмеження доступу до деяких компонентів обʼєкта. Приховування даних і доступ через методи або властивості. Суть: ми не даємо прямого доступу до balance, а керуємо через методи. Рівні доступу в Swift: private, fileprivate, internal (дефолт), public, open; private(set) — читати можна всім, писати лише всередині типу.",
          code: [
            "final class BankAccount {",
            "    private var balance: Decimal = 0          // прямого доступу ззовні немає",
            "    var currentBalance: Decimal { balance }   // читати можна",
            "    func deposit(_ amount: Decimal) { balance += amount }",
            "    func withdraw(_ amount: Decimal) -> Bool {",
            "        guard amount <= balance else { return false }",
            "        balance -= amount; return true",
            "    }",
            "}",
          ],
        },
        {
          title: "2. Успадкування",
          text: "Створення класів на основі інших класів. Успадкування дозволяє одному класу успадковувати властивості та методи іншого — це сприяє повторному використанню коду. У Swift успадкування підтримують лише class (не struct і не enum). Нащадок викликає super.init(...) після ініціалізації своїх полів.",
          code: [
            "class Vehicle {",
            "    var speed: Double",
            "    init(speed: Double) { self.speed = speed }",
            "    func drive() {",
            "        print(\"Їду зі швидкістю \\(speed) км/год\")",
            "    }",
            "}",
            "class Bike: Vehicle {",
            "    var type: String",
            "    init(speed: Double, type: String) {",
            "        self.type = type",
            "        super.init(speed: speed)",
            "    }",
            "    func displayBikeInfo() {",
            "        print(\"Тип велосипеда: \\(type), Швидкість: \\(speed) км/год\")",
            "    }",
            "}",
            "let myBike = Bike(speed: 15, type: \"Гірський\")",
            "myBike.displayBikeInfo()",
            "// Виведе: Тип велосипеда: Гірський, Швидкість: 15.0 км/год",
          ],
        },
        {
          title: "3. Поліморфізм",
          text: "Один і той самий метод працює по-різному для різних обʼєктів. У Swift це зазвичай реалізується через успадкування (override методів) або через протоколи. Масив [Animal] з Dog і Cat — у циклі animal.sound() викликає правильну реалізацію кожного типу.",
          code: [
            "class Animal {",
            "    func sound() { print(\"Тварина видає звук\") }",
            "}",
            "class Dog: Animal {",
            "    override func sound() { print(\"Гав!\") }",
            "}",
            "class Cat: Animal {",
            "    override func sound() { print(\"Мяу!\") }",
            "}",
            "let dog = Dog()",
            "let cat = Cat()",
            "let animals: [Animal] = [dog, cat]",
            "for animal in animals { animal.sound() }",
            "// Виведе:",
            "// Гав!",
            "// Мяу!",
          ],
        },
        {
          title: "4. Абстракція",
          text: "Протоколи (Protocols) визначають інтерфейс без обовʼязкової реалізації. Абстракція — виділення головних характеристик та поведінки обʼєкта, приховуючи деталі реалізації. Мета: працювати з «що робить обʼєкт», а не «як він це робить». У Swift — через протоколи або базові класи, які не використовуються напряму, а лише наслідуються.",
          code: [
            "protocol PaymentMethod {",
            "    func pay(amount: Decimal)",
            "}",
            "struct ApplePay: PaymentMethod {",
            "    func pay(amount: Decimal) { print(\"Оплата \\(amount) через Apple Pay\") }",
            "}",
            "struct Cash: PaymentMethod {",
            "    func pay(amount: Decimal) { print(\"Оплата \\(amount) готівкою\") }",
            "}",
            "func checkout(methods: [any PaymentMethod], total: Decimal) {",
            "    methods.forEach { $0.pay(amount: total) }  // не важливо ЯК — важливо ЩО",
            "}",
          ],
        },
      ],
      problem: "Без інкапсуляції будь-хто може зламати інваріанти обʼєкта (наприклад, встановити відʼємний balance). Без успадкування довелось би копіювати однаковий код у кожен клас. Без поліморфізму — писати if type(of: x) is Dog для кожної операції замість універсального циклу. Без абстракції код жорстко привʼязаний до конкретної реалізації і його важко тестувати чи замінювати.",
      where: [
        "Інкапсуляція: BankAccount з private var balance; ViewModel з private(set) var state — UI читає, змінює лише власник.",
        "Успадкування: UIViewController → BaseViewController зі спільною логікою; UITableViewCell → кастомна комірка. У доменних моделях Apple радить struct + протоколи замість глибоких ієрархій class.",
        "Поліморфізм: [UIView] з різними підкласами; override layoutSubviews; масив [Animal] з Dog і Cat; або [any PaymentMethod] з різними способами оплати.",
        "Абстракція: protocol OrderService — ViewModel не знає, API це чи Mock; UITableViewDataSource — UITableView не знає, який саме екран його реалізує.",
      ],
      traps: [
        "У Swift struct і enum не успадковуються — лише class. Conformance до протоколу — це не успадкування.",
        "override обовʼязковий у нащадка; без нього — помилка компіляції (або приховання методу батька).",
        "Глибокі ієрархії class (3+ рівні) — антипатерн; Swift на практиці віддає перевагу композиції та протоколам (POP).",
        "«Абстрактний клас» у Swift — не окреме ключове слово: базовий class, який не інстанціюють напряму, або протокол.",
        "Поліморфізм через протокол без оголошення методу в тілі протоколу (лише в extension) — static dispatch; див. тему «Protocols і POP».",
      ],
      qs: [
        "Назви чотири принципи ООП і поясни кожен на прикладі Swift.",
        "Інкапсуляція: чому balance — private, а не public var?",
        "Успадкування: напиши Vehicle → Bike з super.init. Навіщо super після своїх полів?",
        "Поліморфізм: що виведе цикл for animal in animals { animal.sound() }?",
        "Абстракція: чим protocol PaymentMethod відрізняється від struct ApplePay?",
        "Коли краще протокол, а коли успадкування class?",
      ],
    },
    {
      p: "P1", name: "Classes: відмінності від struct, успадкування, deinit",
      what: [
        "На перший погляд class схожий на struct: і той і той дозволяє створити новий тип з властивостями та методами. Але class додає успадкування — можливість будувати один клас на основі іншого. Це потужна фіча, і в реальних iOS-додатках (UIKit, AppKit) без класів не обійтись. Але тримай код простим: наявність фічі не означає, що її треба використовувати. Як писав Martin Fowler: «будь-хто може написати код, зрозумілий компʼютеру; хороші програмісти пишуть код, зрозумілий людям».",
        "Джерело структури теми: [Hacking with Swift — Day 10: Classes](https://www.hackingwithswift.com/100/10). Нижче — пʼять ключових відмінностей class від struct, кожна з прикладом коду.",
      ],
      sections: [
        {
          title: "1. Створення class — немає memberwise init",
          text: "На відміну від struct, class ніколи не отримує безкоштовний memberwise initializer. Якщо у class є stored properties без дефолтного значення — потрібен свій init. Три варіанти: зробити поля optional (зазвичай погано), дати дефолтні значення, або написати init вручну — це правильний шлях. init — спеціальний метод без ключового слова func; self. розрізняє параметр і властивість.",
          code: [
            "class Dog {",
            "    var name: String",
            "    var breed: String",
            "",
            "    init(name: String, breed: String) {",
            "        self.name = name",
            "        self.breed = breed",
            "    }",
            "}",
            "let poppy = Dog(name: \"Poppy\", breed: \"Poodle\")",
          ],
        },
        {
          title: "2. Class inheritance — успадкування",
          text: "Class може будуватись на іншому class: CountrySinger: Singer. Двокрапка означає «extends». Нащадок (subclass) отримує властивості й методи батька (superclass) і додає свої. У UIKit/AppKit ієрархії класів — скрізь: UIView → UILabel, UIViewController → твій екран. Не копіюй код батька вручну — зміни в батьківському класі інакше не потраплять у нащадків.",
          code: [
            "class Singer {",
            "    var name: String",
            "    init(name: String) { self.name = name }",
            "    func sing() { print(\"La la la\") }",
            "}",
            "class CountrySinger: Singer {",
            "    override func sing() {",
            "        print(\"Trucks, guitars, and liquor\")",
            "    }",
            "}",
            "let taylor = CountrySinger(name: \"Taylor\")",
            "taylor.sing()  // Trucks, guitars, and liquor",
          ],
        },
        {
          title: "3. Overriding methods — override",
          text: "Щоб змінити метод, успадкований від батька, потрібно override func. Ключове слово override робить намір явним і дозволяє компілятору перевірити: без override — не скомпілюється; override без методу в батьку — теж помилка. Якщо нащадок додає власні stored properties, init нащадка спочатку ініціалізує свої поля, потім викликає super.init(...) — передає параметри батьківському класу.",
          code: [
            "class HeavyMetalSinger: Singer {",
            "    var noiseLevel: Int",
            "    init(name: String, noiseLevel: Int) {",
            "        self.noiseLevel = noiseLevel",
            "        super.init(name: name)       // після своїх полів!",
            "    }",
            "    override func sing() {",
            "        print(\"Grrrrr rargh!\")",
            "    }",
            "}",
          ],
        },
        {
          title: "4. Final classes — заборона успадкування",
          text: "final class забороняє створювати підкласи. Це явний намір («цей клас не для розширення») і оптимізація: компілятор може застосувати static dispatch замість dynamic. Оголошуй final класи, які не плануєш наслідувати: ViewModel, сервіси, утиліти. У великих кодових базах final — дефолт, open — лише для SDK і бібліотек.",
          code: [
            "final class OrderViewModel {",
            "    private(set) var orders: [Order] = []",
            "    // ніхто не зможе зробити class EvilVM: OrderViewModel",
            "}",
          ],
        },
        {
          title: "5. Copying objects — reference semantics",
          text: "При копіюванні struct отримуєш незалежну копію (value type). При «копіюванні» class обидві змінні вказують на той самий обʼєкт у heap (reference type): зміна через одну — видна через іншу. Class дає гнучкість (спільний стан), struct — безпеку (ізольовані копії). UIKit: UI-елементи — class (ідентичність на екрані), моделі даних — struct.",
          code: [
            "class Counter { var value = 0 }",
            "let a = Counter()",
            "let b = a              // не копія обʼєкта — те саме посилання",
            "b.value = 10",
            "print(a.value)         // 10",
            "",
            "struct Point { var x = 0 }",
            "var p1 = Point(); var p2 = p1",
            "p2.x = 5",
            "print(p1.x)            // 0 — незалежна копія",
          ],
        },
        {
          title: "6. Deinitializers — deinit",
          text: "Лише class має deinit — метод, що викликається, коли останнє strong-посилання зникає (ARC → 0). Struct не має deinit — value-типи зникають разом із областю видимості. deinit — місце для cleanup: invalidate таймерів, зняття observers, логування для дебагу ліків. Не покладайся на deinit для критичного збереження даних при креші.",
          code: [
            "class Screen {",
            "    var timer: Timer?",
            "    deinit {",
            "        timer?.invalidate()",
            "        print(\"Screen deinit\")  // якщо не друкується — можливий retain cycle",
            "    }",
            "}",
          ],
        },
        {
          title: "7. Mutability — let class vs let struct",
          text: "let struct заморожує весь вміст — змінити var-поле неможливо. let class фіксує лише посилання: переприсвоїти інший обʼєкт не можна, але var-властивості всередині змінювати можна. Це одна з найчастіших пасток на співбесідах після value vs reference.",
          code: [
            "class Dog { var name = \"Rex\" }",
            "let dog = Dog()",
            "dog.name = \"Buddy\"     // OK — змінюємо вміст обʼєкта",
            "// dog = Dog()         // помилка — посилання незмінне",
            "",
            "struct Cat { var name = \"Mia\" }",
            "let cat = Cat()",
            "// cat.name = \"Leo\"   // помилка — let struct незмінний",
          ],
        },
      ],
      problem: "Class вирішує задачі, де потрібна ідентичність обʼєкта, спільний мутабельний стан, успадкування (UIKit) і детерміноване звільнення ресурсів через deinit. Без розуміння цих відмінностей від struct легко отримати несподівані спільні мутації, ліки памʼяті або помилки з init/super.init.",
      where: [
        "UIView, UIViewController, UITableViewCell — усе class з глибокими ієрархіями успадкування.",
        "ViewModel (ObservableObject), мережеві менеджери, кеші — class для спільного стану між частинами app.",
        "override — у кожному кастомному UIViewController (viewDidLoad), UITableViewCell, делегатах.",
        "final — ViewModel і сервіси, які не плануєш наслідувати.",
        "deinit — перевірка, що VC деалокується після pop (print/debug); invalidate таймерів і NotificationCenter observers.",
        "@objc / @objcMembers — коли UIKit/Objective-C runtime має викликати метод Swift-класу (селектори, #selector).",
      ],
      traps: [
        "Забув super.init у init нащадка — помилка компіляції або невизначена поведінка.",
        "override без ключового слова — не скомпілюється.",
        "Думаєш, що let class = незмінний обʼєкт — насправді незмінне лише посилання.",
        "Копіювання class-змінної — не копія обʼєкта; для справжньої копії потрібен NSCopying або власна логіка.",
        "Глибокі ієрархії (A → B → C → D) — важко підтримувати; не копіюй патерн UIKit у доменні моделі.",
      ],
      qs: [
        "Назви пʼять відмінностей class від struct. Чому struct має memberwise init, а class — ні?",
        "Що означає override і коли потрібен super.init?",
        "Навіщо final class? Що дає компілятору?",
        "Що виведе код з двома посиланнями на один Counter?",
        "Чому let dog.name = \"Buddy\" працює для class, але не для let struct?",
        "Коли викликається deinit і чому struct його не має?",
        "Class дає гнучкість чи безпеку порівняно з struct — і коли що обирати?",
      ],
    },
  ],
};
