// СУМІЖНЕ — 6 тем, розширена версія
module.exports = {
  title: "СУМІЖНЕ, ЩО СПИТАЮТЬ ОДНАКОВО — 6 тем",
  note: "Мережа, сховище, тести й архітектура — питають на кожній співбесіді незалежно від стека UI.",
  topics: [
    {
      p: "P0", name: "Networking: URLSession і дизайн мережевого шару",
      what: [
        "URLSession — HTTP-клієнт системи. Конфігурації: .default (кеш, куки на диску), .ephemeral (усе в памʼяті — приватні режими), .background (завантаження продовжуються після вбивства застосунку — через окремий системний процес). Сучасний API: let (data, response) = try await session.data(for: request); статус-код — у (response as? HTTPURLResponse)?.statusCode, і URLSession НЕ кидає помилку на 404/500 — це твоя робота.",
        "Дизайн шару (твоя робоча тема): Endpoint описує запит (path, method, body, headers) як значення; generic-метод request<T: Decodable> виконує і декодує; централізована обробка: mapping статус-кодів у доменні помилки (enum APIError), refresh токена на 401 з повтором запиту, логування.",
      ],
      problem: "Централізований типізований шар вирішує: розкидані по екранах URLSession.shared.dataTask з копіпастою обробки помилок; «тихі» баги від незвірених статус-кодів; неможливість глобально додати авторизацію/ретраї/логування. Одна точка входу = одне місце для всіх cross-cutting concerns.",
      where: [
        "Твій продакшн-шар в Eatery Club — розкажи на співбесіді СВОЄ: типізовані запити, централізовані помилки — це готова сильна відповідь.",
        "Скасування пошуку: тримаєш Task попереднього запиту, cancel() перед новим (або .task(id: query) у SwiftUI робить це сам).",
        "Паралельні незалежні запити екрана: async let / TaskGroup.",
        "URLCache + ETag: безкоштовний HTTP-кеш для каталогу; SSL pinning — захист від MITM (знати концепцію: перевірка сертифіката сервера у delegate).",
      ],
      code: [
        "enum APIError: Error {",
        "    case unauthorized, notFound",
        "    case server(code: Int), decoding(Error), transport(Error)",
        "}",
        "func request<T: Decodable>(_ endpoint: Endpoint) async throws -> T {",
        "    let (data, response) = try await session.data(for: endpoint.urlRequest)",
        "    guard let http = response as? HTTPURLResponse else { throw APIError.server(code: -1) }",
        "    switch http.statusCode {",
        "    case 200..<300: break",
        "    case 401: throw APIError.unauthorized      // → refresh token flow",
        "    case 404: throw APIError.notFound",
        "    default:  throw APIError.server(code: http.statusCode)",
        "    }",
        "    do { return try decoder.decode(T.self, from: data) }",
        "    catch { throw APIError.decoding(error) }",
        "}",
      ],
      traps: [
        "URLSession не кидає на 4xx/5xx — помилка транспорту ≠ помилка сервера; хто не перевіряє статус, декодить HTML-сторінку помилки як JSON.",
        "Retry на 401: онови токен ОДИН раз і повтори; два запити одночасно отримали 401 — refresh має бути дедуплікований (actor/серіалізація), інакше подвійний refresh забанить сесію.",
        "Background session вимагає delegate-API (не async), і система викликає колбеки навіть після перезапуску застосунку.",
        "Таймаути: timeoutIntervalForRequest — на тишу між пакетами, не на весь запит.",
      ],
      qs: [
        "Намалюй свій мережевий шар з роботи: шлях запиту від виклику до декодованої моделі, де ловляться помилки?",
        "Чому URLSession не кидає помилку на 500 і що буде, якщо забути перевірити статус?",
        "Як реалізувати refresh токена на 401 без подвійного refresh при паралельних запитах?",
        "Як скасувати попередній пошуковий запит при введенні нового символа?",
      ],
    },
    {
      p: "P1", name: "Persistence: UserDefaults, Keychain, Core Data / SwiftData, файли",
      what: [
        "Чотири інструменти під чотири задачі. UserDefaults — маленькі налаштування (прапорці, вибрана мова); plist-файл, НЕ шифрований, вантажиться цілком у память. Keychain — секрети (токени, паролі): шифрується системою, переживає ВИДАЛЕННЯ застосунку, доступ через Security framework (усі користуються обгортками). Core Data — обʼєктний граф зі звʼязками, запитами, міграціями, lazy-loading (faults); це НЕ «обгортка SQLite», а фреймворк керування графом обʼєктів. Файли/FileManager — блоби: картинки, кеш JSON, документи.",
        "Core Data стек: NSPersistentContainer → viewContext (main, для UI) + background contexts (newBackgroundContext / performBackgroundTask). Правило потоків: NSManagedObject живе У СВОЄМУ контексті — між потоками передається objectID, не обʼєкт. SwiftData — новий шар над тим самим ядром: @Model-макрос, @Query у SwiftUI.",
      ],
      problem: "Правильний вибір сховища — питання і безпеки, і перформансу: токен у UserDefaults читається з бекапа/джейлбрейка за секунди (провал секʼюріті-ревʼю); список з 10 000 обʼєктів у UserDefaults — секунди на кожен запуск; блокуючий запис Core Data на main — фризи UI.",
      where: [
        "Твій проєкт: access/refresh токени → Keychain; вибраний ресторан, мова, фіче-флаги онбордингу → UserDefaults; кеш меню для офлайн-старту → JSON-файл або Core Data; фото страв → диск через Kingfisher-кеш.",
        "Background import: синк каталогу з бекенда — performBackgroundTask, збереження, main context підтягує зміни через automaticallyMergesChangesFromParent.",
        "App Group + UserDefaults(suiteName:) — шаринг стану з віджетом/Live Activity (твоя фіча!).",
      ],
      code: [
        "// Токен — тільки Keychain:",
        "func saveToken(_ token: Data) {",
        "    let query: [String: Any] = [",
        "        kSecClass as String: kSecClassGenericPassword,",
        "        kSecAttrAccount as String: \"accessToken\",",
        "        kSecValueData as String: token,",
        "        kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlock",
        "    ]",
        "    SecItemDelete(query as CFDictionary)      // upsert: видалити старий",
        "    SecItemAdd(query as CFDictionary, nil)",
        "}",
        "// Core Data: масовий запис без блокування UI:",
        "container.performBackgroundTask { context in",
        "    for dto in dtos { _ = MenuItem(context: context, dto: dto) }",
        "    try? context.save()     // main context змерджить зміни автоматично",
        "}",
      ],
      traps: [
        "Токен у UserDefaults — класична причина завалу секʼюріті-питання на співбесіді. Тільки Keychain.",
        "Keychain переживає видалення застосунку — на першому запуску після перевстановлення можеш знайти старий токен; чисть за прапорцем першого запуску.",
        "NSManagedObject між потоками — креш/UB; передавай objectID.",
        "UserDefaults.synchronize() — не потрібен з iOS 12, викликати його — маркер застарілих знань.",
      ],
      qs: [
        "Що куди зберігати: токен, налаштування, кеш меню, фото — і чому саме так?",
        "Чому токен НЕ можна в UserDefaults — два конкретні ризики?",
        "Як записати 1000 обʼєктів у Core Data, не заблокувавши UI?",
        "Як шарити дані з віджетом/Live Activity (App Group) — твій робочий досвід?",
      ],
    },
    {
      p: "P1", name: "Тестування: XCTest, моки, DI",
      what: [
        "Unit-тест перевіряє одиницю логіки в ізоляції: швидкий (мілісекунди), детермінований, без мережі/диска/UI. Структура given-when-then. Async-логіка: await прямо в тесті (func test... async throws). XCTest — основний фреймворк; Swift Testing (нове покоління): @Test, #expect, параметризовані тести — знати, що існує.",
        "Мокання: залежність за протоколом → тестова реалізація з контрольованою відповіддю (stub) і записом викликів (spy). DI через init робить підміну тривіальною. Піраміда: багато unit (логіка VM, парсери, форматери) → менше integration → мінімум UI-тестів (повільні й крихкі).",
      ],
      problem: "Тести вирішують страх рефакторингу і регресії: у твоєму мультибрендовому проєкті зміна в спільному коді може зламати 5 брендів — тести ловлять це до QA. Для співбесіди: відсутність тестів у резюме — найпомітніший твій геп; вміння написати тест VM з моком мережі закриває питання.",
      where: [
        "Найвигідніші перші тести у твоєму проєкті: розрахунок кошика (CartTotals — чиста логіка, ідеальний кандидат), парсери server-driven конфігів, форматери адрес/цін.",
        "VM з моком: тест успіху, тест помилки мережі, тест порожнього стану — три тести на екран, і вже є що показати.",
        "Fixtures: static func fixture(...) з дефолтами — читабельні тестові дані без шуму.",
      ],
      code: [
        "final class MockOrderService: OrderService {",
        "    var result: Result<[Order], Error> = .success([])",
        "    private(set) var fetchCallCount = 0          // spy: перевірка взаємодії",
        "    func fetchOrders() async throws -> [Order] {",
        "        fetchCallCount += 1",
        "        return try result.get()",
        "    }",
        "}",
        "final class OrdersViewModelTests: XCTestCase {",
        "    func testLoadFailure_showsError() async {",
        "        // given",
        "        let mock = MockOrderService()",
        "        mock.result = .failure(APIError.server(code: 500))",
        "        let vm = OrdersViewModel(service: mock)",
        "        // when",
        "        await vm.load()",
        "        // then",
        "        guard case .failed = vm.state else { return XCTFail(\"expected .failed\") }",
        "        XCTAssertEqual(mock.fetchCallCount, 1)",
        "    }",
        "}",
      ],
      traps: [
        "Тести, що ходять у реальну мережу — повільні, флакі, залежні від бекенда; це НЕ unit-тести.",
        "Синглтони в коді = неможливість мокати; DI через init — передумова тестованості (тому питання про тести — це питання про архітектуру).",
        "Тестуй поведінку, не імплементацію: перевіряй стан VM, а не «викликався приватний метод».",
        "XCTestExpectation досі потрібен для callback-API; для async/await — просто await.",
      ],
      qs: [
        "Напиши тест VM: успіх і помилка мережі — з моком через протокол.",
        "Stub vs spy vs mock — різниця?",
        "Що б ти покрив тестами першим у своєму проєкті і чому (підказка: CartTotals)?",
        "Чому синглтони заважають тестуванню?",
      ],
    },
    {
      p: "P0", name: "Архітектури і SOLID — розмовна тема",
      what: [
        "MVC — Apple-дефолт: VC тримає і view-логіку, і презентаційну → «Massive View Controller». MVVM — презентаційна логіка й стан у ViewModel, який НЕ знає про UIKit/SwiftUI → тестований; природна пара для SwiftUI. MVP — presenter командує пасивною view через протокол. VIPER — + Interactor (бізнес-логіка), Router (навігація), Entity: багато файлів на екран, для великих команд із жорсткими межами. Clean Architecture — шари domain/data/presentation, залежності показують всередину (domain нічого не знає про UI і мережу).",
        "SOLID на iOS-прикладах: S — VC, що і верстає, і ходить у мережу, і парсить — розділити; O — нова секція home page додається новим типом, а не switch-ом у 10 місцях (твій server-driven UI — буквально це); L — сабклас не ламає контракт базового; I — не UITableViewDataSource+Delegate в одному гігантському протоколі, а вузькі ролі; D — VM залежить від OrderService-протоколу, не від конкретного APIClient.",
      ],
      problem: "Архітектура вирішує масштабування коду командою: де шукати баг, як не зачепити чуже, як тестувати. На співбесіді це перевірка зрілості: чи розумієш ТРЕЙДОФИ (VIPER на 3-екранному застосунку — оверінжиніринг; MVC на 50 екранах — болото), а не «яка архітектура наймодніша».",
      where: [
        "Твоя робоча відповідь: UIKit-екрани — MVC із винесеними менеджерами (CartTotalsManager, CreateOrderManager — по суті інтерактори), нові SwiftUI-екрани — MVVM; server-driven UI зверху. Сформулюй це ЯК СВОЮ архітектурну розповідь — 3 хвилини, впевнено.",
        "Server-driven UI — твоя унікальна тема: конфіг з бекенда (таби, секції, кроки checkout) → фабрики екранів/секцій за типом → одна кодова база на N брендів. Підготуй схему словами: конфіг → парсинг → реєстр фабрик → рендер.",
        "Патерни, які реально питають: Singleton (чому обережно: глобальний стан, нетестовність), Observer (NotificationCenter/Combine), Factory (твої фабрики секцій!), Coordinator, Adapter (обгортка сторонніх SDK), Facade (твої менеджери).",
      ],
      code: [
        "// D із SOLID — залежність від абстракції:",
        "protocol PaymentService {",
        "    func pay(order: Order) async throws -> PaymentResult",
        "}",
        "struct ApplePayService: PaymentService { /* PassKit */ }",
        "struct StripeService: PaymentService { /* Stripe SDK */ }",
        "final class CheckoutViewModel {",
        "    private let payment: PaymentService     // не знає, ЯКА оплата",
        "    init(payment: PaymentService) { self.payment = payment }",
        "}",
        "// O — server-driven секції: новий тип = новий кейс фабрики, не switch по коду",
        "protocol HomeSectionFactory { func makeSection(config: SectionConfig) -> UIView }",
      ],
      traps: [
        "«Яка архітектура найкраща?» — питання-пастка: правильна відповідь через тредофи і розмір команди/проєкту, не назва.",
        "Не вивчай VIPER напамʼять — вмій пояснити РОЛІ шарів і навіщо стільки межей.",
        "Singleton ≠ зло, але: приховані залежності, глобальний мутабельний стан, нетестовність — тому DI навіть для shared-обʼєктів.",
        "Готуй ВЛАСНІ приклади: SOLID без прикладів із свого коду звучить як переказ статті.",
      ],
      qs: [
        "Опиши архітектуру Eatery Club за 3 хвилини: шари, потоки даних, як server-driven конфіг керує UI.",
        "MVC vs MVVM — чому MVVM тестованіший? Покажи, ЩО саме тестуєш.",
        "Кожна літера SOLID — з прикладом із твого коду.",
        "Коли VIPER — правильний вибір, а коли оверінжиніринг?",
      ],
    },
    {
      p: "P0", name: "Архітектури: MVC, MVVM, MVP, VIPER, Clean, TCA — коли доречні, плюси/мінуси",
      what: [
        "Це «топ‑питання» на співбесіді: тебе оцінюють не за те, чи знаєш розшифровку абревіатур, а чи розумієш trade-offs. Правильна відповідь виглядає так: (1) яку проблему вирішує архітектура (масштаб/тестованість/розділення відповідальностей), (2) які її ролі, (3) коли вона доречна, (4) коли вона стає оверінжинірингом.",
        "Сучасний підхід в iOS найчастіше = «просте ядро + явні залежності»: UI-шар (UIKit/SwiftUI) → презентаційний шар (VM/Presenter/Reducer) → доменна логіка (Use Cases) → data layer (API/DB). Незалежно від назви архітектури, ці межі йдуть разом з DI, тестами й чіткою навігацією (Coordinator/Router).",
      ],
      sections: [
        {
          title: "0. Як вибирати архітектуру (шпаргалка рішення)",
          text: "Запитай себе: (1) команда і тривалість проєкту (1–2 dev на 2 міс чи 10 dev на 2 роки?), (2) складність стану/фіч (checkout з багатьма кроками vs статична форма), (3) потреба в тестах (чи є критичні бізнес-правила), (4) кількість інтеграцій і залежностей (SDK, платежі, аналітика). Чим більше цих факторів — тим більше сенсу в шарах (Clean) і жорсткіших межах (VIPER/TCA).",
          code: [
            "// Малий проєкт/екран: MVC або легкий MVVM",
            "// Середній: MVVM + DI + Coordinator (+ UseCases, якщо є бізнес-логіка)",
            "// Великий/довгий: Clean Architecture (шари) + MVVM/MVP у presentation",
            "// Дуже складний state: TCA (або інший unidirectional data flow)",
          ],
        },
        {
          title: "1. MVC (UIKit-дефолт) — коли доречний",
          text: "MVC в UIKit історично означає: UIViewController = Controller, UIView = View, модель = Model. Проблема: в реальному житті VC швидко стає місцем, де живе все (мережа, парсинг, бізнес-логіка, навігація) → «Massive View Controller». MVC доречний на простих екранах, у прототипах, або як «тонкий» контролер, якщо логіку винесено в окремі сервіси/менеджери (по суті, ти вже робиш MV* без назви).",
          code: [
            "// Антипатерн: VC ходить у мережу + парсить + форматує + керує навігацією",
            "// Краще: VC лише збирає UI та викликає сервіси/VM",
          ],
        },
        {
          title: "2. MVVM — сучасний мейнстрім (особливо зі SwiftUI)",
          text: "MVVM розділяє: View (UIKit/SwiftUI) показує стан і відправляє дії; ViewModel тримає стан і логіку представлення (formatting, mapping model → view state), викликає use cases / services. Плюси: тестованість без UI, менше логіки в контролері, прозорі стани (loading/loaded/error). Мінуси: ризик «Massive ViewModel», якщо тягнути туди доменну логіку; також важливо мати чітку навігацію (Coordinator/Router), щоб VM не «знала про UIKit».",
          code: [
            "enum ScreenState<T> { case idle, loading, loaded(T), failed(String) }",
            "final class OrdersVM {",
            "    private let service: OrderService",
            "    private(set) var state: ScreenState<[Order]> = .idle",
            "    init(service: OrderService) { self.service = service }",
            "    func load() async { /* state = .loading → try await → .loaded/.failed */ }",
            "}",
          ],
        },
        {
          title: "3. MVP — коли хочеш «пасивну» View",
          text: "MVP схожий на MVVM, але Presenter керує View через протокол (View стає пасивною і не містить логіки). Це зручно в UIKit, коли хочеш чіткий контракт і легке мокання View у тестах. Плюси: дуже тестовано, прозорий API між Presenter і View. Мінуси: більше бойлерплейту (протокол + presenter + адаптація), легко «перегнути» на простих екранах.",
          code: [
            "protocol OrdersView: AnyObject {",
            "    func showLoading()",
            "    func showOrders(_ orders: [Order])",
            "    func showError(_ message: String)",
            "}",
            "final class OrdersPresenter {",
            "    weak var view: OrdersView?",
            "    private let service: OrderService",
            "    init(service: OrderService) { self.service = service }",
            "}",
          ],
        },
        {
          title: "4. VIPER — «жорсткі межі» для великих команд",
          text: "VIPER розкладає екран на ролі: View (UI), Interactor (use cases/бізнес-логіка), Presenter (підготовка даних для View), Entity (моделі), Router (навігація). Плюси: сильна модульність, легко паралелити роботу в команді, прості тести Interactor/Presenter. Мінуси: дуже багато файлів і коду на один екран, високий overhead, складно підтримувати на маленькому проєкті. Доречно: великий продукт, довгий життєвий цикл, жорсткі команди/модулі.",
          code: [
            "// VIPER: View ↔ Presenter → Interactor → (Services) → Presenter → View",
            "// Router відповідає за navigation (push/present)",
          ],
        },
        {
          title: "5. Clean Architecture — не «патерн екрану», а про шари",
          text: "Clean Architecture — це про напрямок залежностей: domain всередині (Entities + Use Cases) нічого не знає про UI/мережу/БД; data layer реалізує протоколи репозиторіїв; presentation викликає use cases. Плюси: ізоляція бізнес-логіки, тести use cases без UI/мережі, легше міняти API/DB. Мінуси: більше абстракцій (репозиторії, DTO ↔ domain mapping), потребує дисципліни, може бути overkill, якщо бізнес-логіки майже нема.",
          code: [
            "// Domain:",
            "protocol OrdersRepository { func fetchOrders() async throws -> [Order] }",
            "struct LoadOrdersUseCase {",
            "    let repo: OrdersRepository",
            "    func callAsFunction() async throws -> [Order] { try await repo.fetchOrders() }",
            "}",
          ],
        },
        {
          title: "6. TCA (The Composable Architecture) — для складного state",
          text: "TCA — це unidirectional data flow: State (єдине джерело правди) + Action (всі події) + Reducer (як state змінюється) + Effects (async робота). Плюси: дуже прогнозовано, сильна тестованість редʼюсерів, композиція фіч, зрозумілий потік даних, зручно для складних екранів/флоу. Мінуси: високий поріг входу, багато «формального» коду, легко зробити overkill для простих екранів. Доречно: складні checkout/onboarding, багато синхронних/async подій, необхідність чіткої композиції фіч у великому продукті.",
          code: [
            "// Скелет TCA (псевдо):",
            "struct State { var isLoading = false }",
            "enum Action { case onAppear, loaded(Result<[Order], Error>) }",
            "// reducer: (inout State, Action) -> Effect<Action>",
          ],
        },
        {
          title: "7. «Сучасний підхід» — що сказати на співбесіді у 30–60 секунд",
          text: "Сильна відповідь: «У UIKit я зазвичай використовую MVVM (або легкий MVC) з DI через init, щоб логіка була тестована, а залежності — явні. Навігацію виношу в Coordinator/Router, щоб presentation не знала про UIKit. Для бізнес-логіки використовую use cases (Clean-підхід). VIPER — якщо дуже велика команда й потрібні жорсткі межі. TCA — якщо state дуже складний і потрібна композиція фіч та надійні тести».",
          code: [
            "// Ключові слова: DI, testability, clear boundaries, avoid Massive VC/VM, Coordinator",
          ],
        },
      ],
      problem: "Архітектура потрібна, щоб код пережив масштабування: більше фіч → більше станів → більше залежностей → більше розробників. Вона зменшує coupling, робить залежності явними (DI), дозволяє тестувати логіку без UI, і дає зрозуміле місце для навігації. Без цього проєкт деградує до «все в одному VC» або «все в одному VM».",
      where: [
        "MVC: прості екрани або legacy UIKit, де логіка винесена в сервіси/менеджери.",
        "MVVM: типові UIKit/SwiftUI екрани зі станом loading/empty/error; коли потрібні тести VM.",
        "MVP: коли хочеш пасивну View і дуже тестовану presentation-логіку в UIKit.",
        "VIPER: великі команди/модулі, де важлива паралельна розробка та чіткі межі.",
        "Clean Architecture: коли є доменна логіка і треба відʼєднати UI від data layer.",
        "TCA: складні флоу зі складним state, ефектами, композицією фіч і вимогою до тестів.",
      ],
      traps: [
        "Пастка питання «найкраща архітектура» — відповідати треба trade-offs + контекст, не назвою.",
        "MVVM без DI і без чіткої навігації часто перетворюється на Massive ViewModel.",
        "VIPER/TCA на простих екранах = оверінжиніринг і падіння швидкості розробки.",
        "Clean без реальної доменної логіки може додати зайві абстракції (репозиторії «для галочки»).",
      ],
      qs: [
        "Як би ти пояснив MVC vs MVVM одним прикладом екрана зі станом loading/error?",
        "Коли delegate/closure/NotificationCenter вписуються в MVVM/MVP/VIPER?",
        "Коли VIPER доречний, а коли MVVM достатньо? Назви 2 критерії.",
        "Clean Architecture: що таке dependency rule і чому domain не має знати про мережу?",
        "TCA: що таке state/action/reducer/effect і чому це тестовано?",
        "Дай рекомендацію «сучасного підходу» для нового UIKit-проєкту на 10+ екранів.",
      ],
    },
    {
      p: "P0", name: "Реактивність: Combine, RxSwift, @Observable, AsyncSequence",
      what: [
        "«Реактивність» у iOS — це набір інструментів, які дозволяють моделювати зміни як потік значень/подій у часі: user input, нотифікації, мережеві відповіді, таймери, стани екрана. На співбесіді важливо пояснити, що це вирішує: (1) привʼязка UI до стану без купи ручних колбеків, (2) композиція асинхронних операцій (debounce, retry, combineLatest), (3) керування життєвим циклом підписок (cancellation).",
        "Сучасний тренд у Swift: async/await як база для одноразових операцій + AsyncSequence для потоків + Observation (`@Observable` / SwiftUI) для оновлення UI. Combine і RxSwift — для складної композиції потоків і legacy/кросплатформних команд. У правильному дизайні View/VC не знає про мережу — він підписується на стан (MVVM/Reducer).",
      ],
      sections: [
        {
          title: "1. Combine — реактивність від Apple",
          text: "Combine — фреймворк Apple (iOS 13+) для publisher/subscriber. Publisher продукує значення або completion; Subscriber їх споживає. Дуже часто Combine використовують як «трубу» між ViewModel і UI: @Published state → sink → оновити таблицю/лейбл. Переваги: нативний, інтеграції з URLSession, NotificationCenter, KVO; багато операторів (map, filter, debounce, combineLatest). Мінуси: крута крива навчання, складний дебаг, інколи шумний код; у SwiftUI часто вистачає @Observable без Combine.",
          code: [
            "final class SearchVM {",
            "    @Published var query: String = \"\"",
            "    @Published private(set) var results: [String] = []",
            "    private var bag = Set<AnyCancellable>()",
            "",
            "    init(api: SearchAPI) {",
            "        $query",
            "            .debounce(for: .milliseconds(300), scheduler: RunLoop.main)",
            "            .removeDuplicates()",
            "            .flatMap { api.searchPublisher(query: $0).replaceError(with: []) }",
            "            .assign(to: &$results)",
            "    }",
            "}",
            "",
            "// UIKit:",
            "vm.$results",
            "  .receive(on: RunLoop.main)",
            "  .sink { [weak self] _ in self?.tableView.reloadData() }",
            "  .store(in: &bag)",
          ],
        },
        {
          title: "2. RxSwift — стандарт де-факто в legacy/великій кількості проєктів",
          text: "RxSwift — стороння бібліотека, але дуже поширена, особливо в старих кодових базах і великих компаніях. Концепції подібні: Observable/Observer, оператори, dispose bag. Плюси: зріла екосистема, багато прикладів, RxCocoa для UIKit binding. Мінуси: залежність + крива навчання, інтеграція з async/await вимагає мостів; у нових Swift-only проєктах часто обирають Combine або взагалі async/await + Observation.",
          code: [
            "// Скетч (псевдо, без імпорту):",
            "final class SearchVM {",
            "    let query = BehaviorRelay<String>(value: \"\")",
            "    let results = BehaviorRelay<[String]>(value: [])",
            "    let bag = DisposeBag()",
            "",
            "    init(api: SearchAPI) {",
            "        query.asObservable()",
            "            .debounce(.milliseconds(300), scheduler: MainScheduler.instance)",
            "            .distinctUntilChanged()",
            "            .flatMapLatest { api.searchObservable(query: $0).catchAndReturn([]) }",
            "            .bind(to: results)",
            "            .disposed(by: bag)",
            "    }",
            "}",
          ],
        },
        {
          title: "3. @Observable (Observation) — сучасний підхід до state для UI",
          text: "Observation (`@Observable`) — сучасний спосіб зробити модель/VM спостережуваною без Combine. Ідея: змінюється state → UI автоматично інвалідиться. Це особливо природно в SwiftUI, але можна використовувати і в UIKit (через власний адаптер/observer). Плюси: простіший код, менше «труб», фокус на state. Мінуси: це не про «оператори потоків»; для debounce/retry/combineLatest все ще потрібні AsyncSequence/Combine/Rx або ручна логіка.",
          code: [
            "@Observable",
            "final class CounterState {",
            "    var value: Int = 0",
            "    func inc() { value += 1 }",
            "}",
            "",
            "// SwiftUI (ідея): View читає state.value → автоматичний update",
          ],
        },
        {
          title: "4. AsyncSequence — «реактивність» через Swift Concurrency",
          text: "AsyncSequence — це послідовність значень у часі, яку ти споживаєш через for await. Це «нативний» спосіб для потоків подій у Swift Concurrency. Ти можеш будувати власні потоки через AsyncStream/AsyncThrowingStream (наприклад, обгортка delegate/NotificationCenter), або використовувати готові асинхронні послідовності (де доступні). Плюси: простий mental model, cancellation через Task, добре поєднується з async/await. Мінуси: менше готових операторів порівняно з Combine/Rx (хоча є AsyncAlgorithms як окрема бібліотека).",
          code: [
            "func makeTicker() -> AsyncStream<Int> {",
            "    AsyncStream { continuation in",
            "        var i = 0",
            "        let timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { _ in",
            "            continuation.yield(i); i += 1",
            "        }",
            "        continuation.onTermination = { _ in timer.invalidate() }",
            "    }",
            "}",
            "",
            "Task {",
            "    for await tick in makeTicker() {",
            "        print(\"tick \\(tick)\")",
            "    }",
            "}",
          ],
        },
        {
          title: "5. Коли що обирати (сучасна відповідь на співбесіді)",
          text: "Практичний вибір: 1) одноразові асинхронні операції (запит → відповідь) — async/await; 2) потоки подій (таймер/keyboard/input) — AsyncSequence або Combine/Rx; 3) state для UI — @Observable (SwiftUI) або MVVM з чітким state; 4) якщо в проєкті вже RxSwift — не «переписуємо все», а додаємо нове акуратно, інколи через мости. Combine доречний, якщо потрібні оператори (debounce, combineLatest) і нативні інтеграції; RxSwift — якщо екосистема проєкту на Rx.",
          code: [
            "// Interview one-liner:",
            "// async/await — для request/response",
            "// AsyncSequence — для потоків подій у Concurrency",
            "// @Observable — для UI state",
            "// Combine/Rx — коли потрібна композиція потоків і оператори",
          ],
        },
      ],
      problem: "Без реактивного/потокового підходу код деградує до «callback hell»: купа делегатів, нотифікацій і ручних оновлень UI. Combine/Rx/AsyncSequence дають композицію подій (debounce, merge), а Observation робить оновлення UI від state природним. Правильний вибір інструмента зменшує баги з життєвим циклом (відписки/скасування) і спрощує тестування.",
      where: [
        "Search: debounce введення, cancel попереднього запиту (flatMapLatest / Task cancellation).",
        "Форми: валідація полів «на льоту» (combineLatest кількох input).",
        "Реакція на системні події: NotificationCenter publishers/streams.",
        "MVVM/TCA-подібні флоу: UI підписаний на state і реагує на зміни.",
      ],
      traps: [
        "Забув зберегти AnyCancellable / dispose — підписка одразу деалокується або навпаки «тече».",
        "Retain cycle в sink/closure: завжди думай про [weak self].",
        "Rx/Combine «склеїли» UI і data layer — важко тестувати; краще підписувати UI на state VM.",
        "AsyncStream без onTermination → таймер/ресурс не інвалідиться.",
      ],
      qs: [
        "Поясни різницю між async/await і реактивними потоками (Combine/Rx/AsyncSequence).",
        "Коли Combine доречніший за AsyncSequence? А коли навпаки?",
        "Як реалізувати search з debounce + cancel попереднього запиту у Combine або Concurrency?",
        "Що таке @Observable і чим він відрізняється від @Published?",
        "DisposeBag / AnyCancellable — навіщо вони?",
      ],
    },
  ],
};
