// UIKIT — 9 тем, розширена версія
module.exports = {
  title: "UIKIT — 9 тем",
  note: "Твоя щоденна робота — тут ти маєш звучати найупевненіше. Фокус на lifecycle, AutoLayout і таблицях: це 80% UIKit-питань.",
  topics: [
    {
      p: "P0", name: "App lifecycle: AppDelegate, SceneDelegate, стани",
      what: [
        "Стани застосунку: not running → inactive (працює, не отримує події — дзвінок, шторка) → active → background (обмежений час на завершення справ) → suspended (у памʼяті, не виконується; система може вбити без попередження). Повернення з suspended — НЕ новий запуск, стан живий.",
        "AppDelegate — події рівня ПРОЦЕСУ: запуск (didFinishLaunching — конфіг Firebase, DI, пуші), токен пушів, background fetch. SceneDelegate — події рівня ВІКНА/UI (для multi-window на iPad): створення window, sceneDidBecomeActive, sceneDidEnterBackground. До iOS 13 усе було в AppDelegate.",
      ],
      problem: "Розуміння станів вирішує реальні продакшн-проблеми: де оновити застарілі дані після повернення з фону (willEnterForeground, не didFinishLaunching — його не буде при поверненні з suspended!), де зберегти стан перед смертю (didEnterBackground — гарантований момент), чому таймери/запити «зупинились» (background = виконання заморожене).",
      where: [
        "didFinishLaunching: FirebaseApp.configure(), реєстрація пушів, старт DI-контейнера — твій робочий сетап.",
        "Пуш-флоу: registerForRemoteNotifications → didRegisterForRemoteNotificationsWithDeviceToken → токен на бекенд; willPresent (пуш прийшов у foreground — показати банер?) / didReceive (юзер тапнув — дип-лінк навігація). Твоя щоденна тема.",
        "sceneWillEnterForeground: рефреш статусу замовлення, перевірка протухлого токена — юзер повернувся через годину.",
        "didEnterBackground: зберегти чернетку кошика, почати background task на дозапис.",
        "Live Activities (твоя фіча!): оновлення через ActivityKit працює З ФОНУ через пуші — гарний приклад роботи навколо lifecycle-обмежень.",
      ],
      code: [
        "func application(_ app: UIApplication,",
        "    didFinishLaunchingWithOptions opts: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {",
        "    FirebaseApp.configure()",
        "    UNUserNotificationCenter.current().delegate = self",
        "    app.registerForRemoteNotifications()",
        "    return true",
        "}",
        "func userNotificationCenter(_ c: UNUserNotificationCenter,",
        "    didReceive response: UNNotificationResponse,",
        "    withCompletionHandler done: @escaping () -> Void) {",
        "    let userInfo = response.notification.request.content.userInfo",
        "    deepLinkRouter.handle(userInfo)      // тап по пушу → екран замовлення",
        "    done()",
        "}",
      ],
      traps: [
        "Повернення з suspended НЕ викликає didFinishLaunching — ініціалізація «раз на показ» має жити у willEnterForeground/didBecomeActive.",
        "У background маєш ~секунди; довша робота — beginBackgroundTask, інакше система вбʼє процес.",
        "deviceToken може змінюватись — відправляй на бекенд при кожному didRegister, не кешуй вічно.",
        "didReceiveRemoteNotification для тихих пушів (content-available) не гарантований — система може не розбудити застосунок (низький заряд, rate limit).",
      ],
      qs: [
        "Проведи застосунок через усі стани: користувач згорнув і відкрив через годину — які колбеки і в якому порядку?",
        "Чому оновлення токена сесії — НЕ в didFinishLaunching?",
        "Розкажи повний шлях пуша: від реєстрації до відкриття екрана замовлення по тапу (твій робочий флоу).",
        "AppDelegate vs SceneDelegate — що куди і навіщо розділили?",
      ],
    },
    {
      p: "P0", name: "UIViewController lifecycle",
      what: [
        "Ланцюг: init → loadView (створює self.view; переозначають лише для повністю кастомного root view) → viewDidLoad (view створено, розміри НЕ фінальні; один раз на життя VC) → viewWillAppear (перед кожною появою) → viewWillLayoutSubviews / viewDidLayoutSubviews (після проходу AutoLayout — тут розміри ВЖЕ валідні; може викликатись багато разів) → viewDidAppear (на екрані, анімація переходу завершена) → viewWillDisappear / viewDidDisappear → deinit.",
        "Containment (child view controllers): addChild(child) → view.addSubview(child.view) → child.didMove(toParent: self) — вбудовування VC у VC (сегменти, вкладки, твої UIHostingController-вставки).",
      ],
      problem: "Знання «що і де робити» прибирає цілий клас багів: підписки в viewDidLoad без відписки → дублікати обробників після повернення; робота з frame у viewDidLoad → верстка під старий розмір; важке в viewWillAppear → лаг переходу. Правила: одноразова настройка — viewDidLoad; підписки/таймери — willAppear + зняття в didDisappear; усе залежне від розмірів — viewDidLayoutSubviews.",
      where: [
        "viewDidLoad: addSubview + констрейнти, конфіг таблиці, привʼязка VM.",
        "viewWillAppear: оновити дані, які могли змінитись, поки екран був у стеку (повернулись із деталей — список освіжити); почати спостереження.",
        "viewDidLayoutSubviews: градієнтний CALayer під розмір вʼюхи (layer не в AutoLayout!), скругления, залежні від фактичної ширини.",
        "viewDidAppear: стартувати анімації, запросити дозволи (не лякати юзера до появи екрана), почати відеоплеєр.",
      ],
      code: [
        "override func viewDidLoad() {",
        "    super.viewDidLoad()",
        "    setupSubviews()                    // один раз",
        "}",
        "override func viewWillAppear(_ animated: Bool) {",
        "    super.viewWillAppear(animated)",
        "    NotificationCenter.default.addObserver(self, selector: #selector(refresh),",
        "        name: .orderUpdated, object: nil)",
        "}",
        "override func viewDidDisappear(_ animated: Bool) {",
        "    super.viewDidDisappear(animated)",
        "    NotificationCenter.default.removeObserver(self)   // парна відписка",
        "}",
        "override func viewDidLayoutSubviews() {",
        "    super.viewDidLayoutSubviews()",
        "    gradientLayer.frame = headerView.bounds  // розміри вже фінальні",
        "}",
      ],
      traps: [
        "frame/bounds у viewDidLoad — ще від XIB/дефолту, НЕ фінальні (інші пристрої, rotation). Валідні — у viewDidLayoutSubviews.",
        "viewWillAppear без парного «зняття» у didDisappear — подвійні підписки після повернення.",
        "viewWillAppear викликався, а viewDidAppear ні — можливо: interactive pop скасовано на півдорозі (свайп назад відпущено).",
        "Пропущений didMove(toParent:) при containment — зламані appearance-колбеки дитини.",
      ],
      qs: [
        "Повний порядок колбеків від init до deinit? Що викликається один раз, що — багато?",
        "Чому frame невалідний у viewDidLoad і де валідний?",
        "Що робити в viewWillAppear vs viewDidLoad — правило?",
        "Як правильно вбудувати child VC (три кроки) — і де ти це робиш із UIHostingController?",
      ],
    },
    {
      p: "P0", name: "AutoLayout",
      what: [
        "Система лінійних рівнянь: кожен констрейнт — item1.attr = m × item2.attr + c. Solver (Cassowary) знаходить розвʼязок. Пріоритети: required (1000) — рівняння зобовʼязане виконатись; нижчі (999...1) — «побажання», яким можна поступитись. Конфлікт двох required — креш-лог «Unable to simultaneously satisfy constraints» і система викидає один констрейнт навмання.",
        "Intrinsic content size — власний розмір контенту (лейбл знає розмір тексту). Довкола нього два невидимі констрейнти з пріоритетами: content hugging (опір розтягуванню — «не хочу бути більшим за контент») і compression resistance (опір стисканню — «не дам себе обрізати»). Дефолти: hugging 251, resistance 750.",
        "Цикл верстки: setNeedsLayout — «поміть брудним, перерахуєш на наступному кадрі» (дешево, батчиться); layoutIfNeeded — «перерахуй НЕГАЙНО, якщо брудний» (синхронно); потрібен для анімації констрейнтів.",
      ],
      problem: "Вирішує адаптивність: один екран на всі розміри iPhone/iPad, динамічні шрифти, локалізації різної довжини (твої 10+ мов — німецький текст в 1.5 раза довший за англійський!). Пріоритети і hugging/resistance вирішують конфлікти «кому поступитись місцем» декларативно.",
      where: [
        "Класика «два лейбли в рядку»: назва страви + ціна. Ціна не має обрізатись: price.setContentCompressionResistancePriority(.required, for: .horizontal) — стиснеться назва (з «...»).",
        "Анімація розкриття панелі: змінити constant → UIView.animate { self.view.layoutIfNeeded() }.",
        "Self-sizing клітинки: констрейнти від верху до низу контенту + estimatedRowHeight — твоя щоденна практика в XIB.",
        "Перемикання станів: активація/деактивація масивів констрейнтів (NSLayoutConstraint.activate) — компактний/розгорнутий режими.",
      ],
      code: [
        "// Два лейбли: ціна не стискається, назва — так",
        "nameLabel.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)",
        "priceLabel.setContentCompressionResistancePriority(.required, for: .horizontal)",
        "priceLabel.setContentHuggingPriority(.required, for: .horizontal)",
        "",
        "// Анімація констрейнта:",
        "heightConstraint.constant = isExpanded ? 300 : 80",
        "UIView.animate(withDuration: 0.3) {",
        "    self.view.layoutIfNeeded()   // solver перерахує, зміни анімуються",
        "}",
      ],
      traps: [
        "translatesAutoresizingMaskIntoConstraints = false для КОЖНОЇ вʼюхи, створеної кодом — інакше автогенеровані констрейнти конфліктують з твоїми (найчастіша помилка).",
        "Анімація констрейнтів без layoutIfNeeded усередині animate-блоку — зміна стрибне без анімації.",
        "Конфлікт 1000 vs 1000 → лог з «Will attempt to recover by breaking constraint» — читай, який зламали; один з required зроби 999.",
        "Дебаг: view.constraintsAffectingLayout(for: .vertical), symbolic breakpoint UIViewAlertForUnsatisfiableConstraints, Debug View Hierarchy.",
      ],
      qs: [
        "Два лейбли в рядку, місця мало — який стиснеться? Як гарантувати, що ціна ніколи не обріжеться?",
        "hugging vs compression resistance — що кожен контролює?",
        "setNeedsLayout vs layoutIfNeeded — різниця і чому layoutIfNeeded потрібен в анімації?",
        "Як дебажиш Unable to satisfy constraints у великому XIB — покроково?",
      ],
    },
    {
      p: "P0", name: "UITableView / UICollectionView",
      what: [
        "Reuse: система тримає пул клітинок ≈ під видиму область; клітинка, що поїхала за екран, повертається в пул і видається знову через dequeueReusableCell — зі СТАРИМ вмістом. prepareForReuse — місце скинути стан (скасувати завантаження картинки, обнулити прапорці). dataSource — «що показувати» (кількість, клітинки); delegate — «як поводитись» (висоти, тапи, will/didDisplay).",
        "Diffable Data Source: описуєш НОВИЙ стан снапшотом (секції + item identifiers), система сама рахує diff і анімує вставки/видалення/переміщення. Прибирає цілий клас крешів «number of rows before update is not equal…» від ручного performBatchUpdates. Compositional Layout — декларативний опис колекції: item → group → section, кожна секція зі своєю геометрією й ортогональним скролом.",
      ],
      problem: "Reuse вирішує памʼять: стрічка з 10 000 замовлень тримає ~15 клітинок замість 10 000. Diffable вирішує коректність оновлень (креші batch updates). Compositional вирішує складні макети (горизонтальні карусельки в вертикальній стрічці — твоя home page) без вкладених collection views і їх багів.",
      where: [
        "Меню ресторану, список замовлень, каталог — базовий хліб твого проєкту.",
        "Async-картинки страв + reuse: скасування завантаження в prepareForReuse (Kingfisher робить це через cancelDownloadTask).",
        "Home page із секціями «банери / категорії / рекомендації» — compositional layout з orthogonal scrolling (природно лягає на твій server-driven UI: секції з конфіга бекенда).",
        "Diffable + server-driven: прийшов новий конфіг сторінки → новий снапшот → секції красиво анімуються.",
      ],
      code: [
        "// Класичний фікс «чужих картинок» при reuse:",
        "final class DishCell: UITableViewCell {",
        "    override func prepareForReuse() {",
        "        super.prepareForReuse()",
        "        thumbView.kf.cancelDownloadTask()   // 1) скасувати стару загрузку",
        "        thumbView.image = placeholder       // 2) плейсхолдер одразу",
        "    }",
        "}",
        "// 3) у cellForRowAt — завантаження за URL САМЕ ЦІЄЇ моделі",
        "",
        "// Diffable:",
        "var snapshot = NSDiffableDataSourceSnapshot<Section, MenuItem.ID>()",
        "snapshot.appendSections([.promo, .dishes])",
        "snapshot.appendItems(promoIDs, toSection: .promo)",
        "dataSource.apply(snapshot, animatingDifferences: true)",
      ],
      traps: [
        "«Чужі» картинки при скролі — питання №1 по таблицях: причина — reuse + асинхронне завантаження, що завершилось для вже переюзаної клітинки. Фікс: три кроки в коді вище.",
        "reloadData посеред анімацій/скролу — смикання, втрата виділень; точкові оновлення або diffable.",
        "Важке в cellForRowAt (форматування, підрахунки) — виконується на кожен показ клітинки → лаги скролу; готуй дані заздалегідь у VM.",
        "Diffable вимагає УНІКАЛЬНИХ і стабільних identifiers; дублікати = креш. ID, а не цілі моделі, у снапшоті (швидше, менше памʼяті).",
        "Self-sizing: повний ланцюг вертикальних констрейнтів у contentView + estimatedRowHeight; розриви = нульова висота.",
      ],
      qs: [
        "Чому при скролі зʼявляються «чужі» картинки і які три кроки фіксу?",
        "Навіщо prepareForReuse і що в ньому робити/не робити?",
        "Чим diffable data source кращий за reloadData і performBatchUpdates?",
        "Як би ти зверстав home page з горизонтальними каруселями — compositional layout: item/group/section?",
      ],
    },
    {
      p: "P1", name: "UIView, CALayer, rendering",
      what: [
        "Кожен UIView — обгортка над CALayer: view обробляє події (touch, responder chain) і AutoLayout, layer — малювання, геометрію, анімації. frame — прямокутник у координатах СУПЕРВʼЮХИ; bounds — власна система координат (origin зазвичай 0,0). Не збігаються: при transform (frame стає undefined — не читай його), при скролі (UIScrollView просто рухає bounds.origin!).",
        "Кадр рендериться конвеєром: layout (layoutSubviews) → display (draw/вміст layer) → композиція на GPU. Offscreen rendering — GPU змушений малювати у проміжний буфер до екрана: тригери — masksToBounds + cornerRadius на складному вмісті, тінь БЕЗ shadowPath, маски. Багато offscreen у клітинках = просідання скролу.",
      ],
      problem: "Розуміння view/layer пояснює, чому тінь і скруглення «конфліктують» (тінь малюється ЗОВНІ, clipping ріже ВСЕРЕДИНІ — на одному layer несумісні) і як анімувати те, чого немає в UIView API (CABasicAnimation по шляху). Розуміння bounds пояснює весь UIScrollView одним реченням.",
      where: [
        "Картка страви з тінню і скругленням: два шари — зовнішній layer з shadow + shadowPath, внутрішній view з cornerRadius + masksToBounds.",
        "Градієнт кнопки: CAGradientLayer, frame оновлюється у layoutSubviews/viewDidLayoutSubviews (layer не в AutoLayout!).",
        "Дебаг скролу: Simulator → Debug → Color Offscreen-Rendered Yellow; Instruments → Core Animation.",
        "layoutSubviews викликається при зміні bounds, addSubview, setNeedsLayout — ручна верстка підвʼюх без констрейнтів.",
      ],
      code: [
        "// Тінь + скруглення БЕЗ offscreen rendering:",
        "containerView.layer.shadowColor = UIColor.black.cgColor",
        "containerView.layer.shadowOpacity = 0.15",
        "containerView.layer.shadowPath = UIBezierPath(   // явний шлях = без offscreen",
        "    roundedRect: containerView.bounds, cornerRadius: 16).cgPath",
        "",
        "contentView.layer.cornerRadius = 16",
        "contentView.layer.masksToBounds = true           // ріже ВНУТРІШНІЙ вміст",
        "// containerView НЕ має masksToBounds — тінь живе зовні",
      ],
      traps: [
        "shadowPath оновлюй при зміні розмірів (layoutSubviews) — інакше тінь відстане від вʼюхи.",
        "Після transform читати/писати frame не можна — працюй з bounds + center.",
        "drawRect дорогий (CPU-растеризація) — лише коли справді потрібне кастомне малювання; частіше вистачає шарів і картинок.",
        "UIStackView сам не малюється (non-rendering) — background до iOS 14 не працював.",
      ],
      qs: [
        "frame vs bounds — коли не збігаються? Як через bounds пояснити UIScrollView?",
        "Як зробити тінь + cornerRadius без offscreen rendering?",
        "Що тригерить layoutSubviews?",
        "Чим відрізняються view і layer за відповідальністю?",
      ],
    },
    {
      p: "P1", name: "Responder chain, hit testing, gestures",
      what: [
        "Два окремі механізми. Hit testing — ПОШУК вʼюхи під пальцем: рекурсивний обхід дерева ЗВЕРХУ вниз (subviews у зворотному порядку — верхні перші) через hitTest(_:with:), який викликає point(inside:). Вʼюха випадає з пошуку: isUserInteractionEnabled=false, isHidden, alpha<0.01, точка поза bounds.",
        "Responder chain — ДОСТАВКА події, якщо ніхто не обробив: view → superview → ... → UIViewController → UIWindow → UIApplication. UIGestureRecognizer-и мають пріоритет над raw touches; конфлікти вирішуються делегатом (shouldRecognizeSimultaneouslyWith, require(toFail:)).",
      ],
      problem: "Пояснює найчастіші «містичні» баги дотиків: кнопка, що стирчить за межі батька, НЕ тапається (hit test батька відсікає точку поза його bounds до перевірки дітей); прозорий оверлей зʼїдає тапи; жест таблиці конфліктує з жестом клітинки.",
      where: [
        "Збільшення тач-зони маленької кнопки: override point(inside:) з bounds.insetBy(dx: -12, dy: -12).",
        "Кнопка за межами батька: override hitTest у батька — перевіряти дітей до відсікання.",
        "«Пропускати» тапи крізь оверлей: hitTest повертає nil для себе, але дітей перевіряє.",
        "Тап по фону закриває клавіатуру, але не блокує кнопки: tap recognizer з cancelsTouchesInView = false.",
      ],
      code: [
        "// Збільшена тач-зона:",
        "final class BigTapButton: UIButton {",
        "    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {",
        "        bounds.insetBy(dx: -12, dy: -12).contains(point)",
        "    }",
        "}",
        "// Кнопка, що виступає за межі контейнера:",
        "override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {",
        "    if let v = super.hitTest(point, with: event) { return v }",
        "    let p = overflowButton.convert(point, from: self)",
        "    return overflowButton.point(inside: p, with: event) ? overflowButton : nil",
        "}",
      ],
      traps: [
        "Порядок обходу: ОСТАННЯ додана subview перевіряється ПЕРШОЮ — верхня вʼюха перехоплює тапи нижньої.",
        "alpha < 0.01 вимикає дотики — «майже невидима» кнопка перестає працювати.",
        "Жест на superview зʼїдає тапи по клітинках таблиці — delegate + touch.view перевірка.",
        "hitTest викликається двічі на дотик — не клади туди side effects.",
      ],
      qs: [
        "Кнопка стирчить за межі батьківської вʼюхи — чому не тапається і два способи фіксу?",
        "Опиши рекурсію hitTest: порядок, умови відсікання.",
        "Hit testing vs responder chain — що шукає, що доставляє?",
        "Як розвʼязати конфлікт двох жестів (скрол + свайп клітинки)?",
      ],
    },
    {
      p: "P1", name: "Navigation: push, present, координатори",
      what: [
        "UINavigationController — стек VC: push/pop, свайп назад безкоштовно, спільний navigation bar. present — модальний показ ПОВЕРХ (окремий флоу: оформлення, авторизація); стилі: pageSheet (шторка), fullScreen (важливо: fullScreen НЕ викликає viewWillAppear у батька після dismiss — сюрприз для оновлення даних), popover.",
        "Coordinator: обʼєкт, що ВОЛОДІЄ навігацією — створює VC, тримає navigationController, вирішує «куди далі». VC лише повідомляє про події (делегат/closure) і не знає про інші екрани. Дерево координаторів: AppCoordinator → TabCoordinator → OrderFlowCoordinator.",
      ],
      problem: "Вирішує зашитість флоу у VC: коли екран сам створює і пушить наступний — його неможливо перевикористати в іншому флоу, тестувати і міняти порядок кроків. Особливо боляче у твоєму випадку server-driven checkout: порядок кроків приходить з бекенда — отже, вирішувати «куди далі» має координатор за конфігом, а не екран.",
      where: [
        "Checkout-флоу: CheckoutCoordinator читає конфіг кроків (адреса → оплата → підтвердження) і пушить екрани за ним — твій робочий патерн у чистому вигляді.",
        "Передача результату назад: closure var onAddressSelected: ((Address) -> Void)? — простіше за delegate для одного колбека.",
        "Deep link з пуша: AppCoordinator розбирає маршрут, вибирає таб, будує стек екранів.",
        "UIHostingController усередині координатора — SwiftUI-екрани в тому ж флоу без винятків.",
      ],
      code: [
        "final class CheckoutCoordinator {",
        "    private let nav: UINavigationController",
        "    private let steps: [CheckoutStep]          // server-driven конфіг!",
        "    private var index = 0",
        "    func start() { show(steps[0]) }",
        "    private func show(_ step: CheckoutStep) {",
        "        let vc = makeViewController(for: step)",
        "        vc.onCompleted = { [weak self] in self?.next() }   // екран не знає, що далі",
        "        nav.pushViewController(vc, animated: true)",
        "    }",
        "    private func next() {",
        "        index += 1",
        "        index < steps.count ? show(steps[index]) : finishOrder()",
        "    }",
        "}",
      ],
      traps: [
        "Координатори ніхто не тримає — деініт і мертві колбеки; батько тримає дітей у масиві childCoordinators, прибирає по завершенню флоу.",
        "onCompleted-closure захоплює координатор, координатор тримає VC... — [weak self] у колбеках координатора.",
        "present поверх present — «Attempt to present ... which is already presenting»; презентуй з topmost VC.",
        "Passing data: синглтони/глобальний стан замість init injection — нетестовано і звʼязує все з усім.",
      ],
      qs: [
        "Чому «VC сам пушить наступний VC» — антипатерн? Три причини.",
        "Як екран Б повертає результат екрану А — delegate, closure, async? Тредофи?",
        "Спроєктуй координатор для server-driven checkout — як конфіг визначає флоу?",
        "push vs present — семантика вибору (не технічна різниця, а КОЛИ що)?",
      ],
    },
    {
      p: "P2", name: "RunLoop, main thread, Timer",
      what: [
        "RunLoop — цикл обробки подій потоку: чекає події (тач, таймер, DisplayLink) → обробляє → спить. Main RunLoop крутить весь UI. Modes: default — звичайна робота; tracking — під час скролу; common — обʼєднання. Timer, доданий у default mode, ЗАВМИРАЄ під час скролу — RunLoop у tracking mode його не бачить.",
      ],
      problem: "Пояснює класичний баг «таймер зупиняється при скролі» (каруселька банерів перестає гортатись, поки юзер скролить меню — твій прямий кейс!) і чому «UI лише з main» — не забобон, а наслідок однопотокової моделі RunLoop/UIKit.",
      where: [
        "Автогортання промо-банерів: RunLoop.main.add(timer, forMode: .common) — працює і під час скролу.",
        "CADisplayLink — «таймер кадрів» для власних анімацій (прогрес кільця).",
        "Main Thread Checker ловить UI-виклики з фонових потоків (фіолетові варнінги).",
      ],
      code: [
        "let timer = Timer(timeInterval: 3, repeats: true) { [weak self] _ in",
        "    self?.scrollToNextBanner()",
        "}",
        "RunLoop.main.add(timer, forMode: .common)   // не завмирає при скролі",
      ],
      traps: [
        "Timer.scheduledTimer додає в default mode — банерна каруселька «зависає» при скролі; додай у .common.",
        "Timer з target: self тримає self СИЛЬНО до invalidate — block-based API + [weak self] + invalidate у deinit/didDisappear.",
        "Таймер — не точний інструмент: спрацює після поточної ітерації RunLoop; для точних кадрів — CADisplayLink.",
      ],
      qs: [
        "Чому таймер зупиняється при скролі й як полагодити?",
        "Чому Timer(target: self) створює цикл і як уникнути?",
        "Що таке RunLoop mode і навіщо common?",
      ],
    },
    {
      p: "P2", name: "XIB / Storyboard vs код",
      what: [
        "XIB — XML-опис однієї вʼюхи/екрана, вантажиться в рантаймі (Bundle.loadNibNamed); File's Owner — обʼєкт-власник, до якого чіпляються IBOutlet. Storyboard — багато екранів + segue між ними. Верстка кодом — усе явно, найкращий diff/merge.",
        "Твій проєкт (XIB + програмна верстка, БЕЗ Storyboard) — усвідомлений компроміс: XIB дає візуальний огляд і швидкість для статичних екранів/клітинок, код — контроль для динаміки; відсутність Storyboard прибирає найгірші merge-конфлікти і повільний Interface Builder на великих файлах.",
      ],
      problem: "Вибір інструмента — типове питання «як влаштований ваш проєкт». Storyboard-и в команді конфліктують на кожному PR (один XML на десятки екранів), погано ревʼюються, стрінгові ідентифікатори segue падають у рантаймі. XIB локалізує конфлікт до одного екрана. Код — єдине джерело правди, але повільніше для простих форм.",
      where: [
        "Переюзабельна вʼюха з XIB: клітинки меню, банери — registerNib + dequeue, твій щоденний пайплайн.",
        "loadNibNamed у init кастомної вʼюхи + прикріплення contentView (owner-патерн).",
        "Нові екрани — SwiftUI (у тебе так і є) — XIB лишили legacy, нове пишеться декларативно.",
      ],
      code: [
        "// Реєстрація і використання клітинки з XIB:",
        "tableView.register(UINib(nibName: \"DishCell\", bundle: nil),",
        "                   forCellReuseIdentifier: \"DishCell\")",
        "let cell = tableView.dequeueReusableCell(withIdentifier: \"DishCell\",",
        "                                         for: indexPath) as! DishCell",
      ],
      traps: [
        "IBOutlet — сучасна рекомендація strong (weak — спадок часів viewDidUnload); але weak теж працює, головне розуміти чому.",
        "Забутий registerNib → креш dequeue; стрінгові ідентифікатори — винось у константи/SwiftGen (у вас він є!).",
        "XIB + кастомний init: awakeFromNib викликається ПІСЛЯ звʼязування outlets — конфігуруй там, не в init.",
      ],
      qs: [
        "Аргументуй ваш вибір XIB + код без Storyboard — плюси, мінуси, чому не інакше?",
        "Як влаштований пайплайн переюзабельної вʼюхи з XIB у вашому проєкті?",
        "Чому великі команди тікають від Storyboard?",
      ],
    },
  ],
};
