// UIKIT — 11 тем, розширена версія
module.exports = {
  title: "UIKIT — 11 тем",
  note: "Твоя щоденна робота — тут ти маєш звучати найупевненіше. Фокус на lifecycle, AutoLayout і таблицях: це 80% UIKit-питань.",
  topics: [
    {
      p: "P0", name: "App lifecycle: AppDelegate, SceneDelegate, стани",
      what: [
        "Стани застосунку: not running → inactive (працює, не отримує події — дзвінок, шторка) → active → background (обмежений час на завершення справ) → suspended (у памʼяті, не виконується; система може вбити без попередження). Повернення з suspended — НЕ новий запуск, стан живий.",
        "AppDelegate — події рівня ПРОЦЕСУ: запуск (didFinishLaunching — конфіг Firebase, DI, пуші), токен пушів, background fetch. SceneDelegate — події рівня ВІКНА/UI (для multi-window на iPad): створення window, sceneDidBecomeActive, sceneDidEnterBackground. До iOS 13 усе було в AppDelegate.",
      ],
      problem: "Розуміння станів вирішує реальні продакшн-проблеми: де оновити застарілі дані після повернення з фону (willEnterForeground, не didFinishLaunching — його не буде при поверненні з suspended!), де зберегти стан перед смертю (didEnterBackground — гарантований момент), чому таймери/запити «зупинились» (background = виконання заморожене).",
      where: [
        "didFinishLaunching: FirebaseApp.configure(), реєстрація пушів, старт DI-контейнера — твій робочий сетап.",
        "Пуш-флоу: registerForRemoteNotifications → didRegisterForRemoteNotificationsWithDeviceToken → токен на бекенд; willPresent (пуш прийшов у foreground — показати банер?) / didReceive (юзер тапнув — дип-лінк навігація). Твоя щоденна тема.",
        "sceneWillEnterForeground: рефреш статусу замовлення, перевірка протухлого токена — юзер повернувся через годину.",
        "didEnterBackground: зберегти чернетку кошика, почати background task на дозапис.",
        "Live Activities (твоя фіча!): оновлення через ActivityKit працює З ФОНУ через пуші — гарний приклад роботи навколо lifecycle-обмежень.",
      ],
      code: [
        "func application(_ app: UIApplication,",
        "    didFinishLaunchingWithOptions opts: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {",
        "    FirebaseApp.configure()",
        "    UNUserNotificationCenter.current().delegate = self",
        "    app.registerForRemoteNotifications()",
        "    return true",
        "}",
        "func userNotificationCenter(_ c: UNUserNotificationCenter,",
        "    didReceive response: UNNotificationResponse,",
        "    withCompletionHandler done: @escaping () -> Void) {",
        "    let userInfo = response.notification.request.content.userInfo",
        "    deepLinkRouter.handle(userInfo)      // тап по пушу → екран замовлення",
        "    done()",
        "}",
      ],
      traps: [
        "Повернення з suspended НЕ викликає didFinishLaunching — ініціалізація «раз на показ» має жити у willEnterForeground/didBecomeActive.",
        "У background маєш ~секунди; довша робота — beginBackgroundTask, інакше система вбʼє процес.",
        "deviceToken може змінюватись — відправляй на бекенд при кожному didRegister, не кешуй вічно.",
        "didReceiveRemoteNotification для тихих пушів (content-available) не гарантований — система може не розбудити застосунок (низький заряд, rate limit).",
      ],
      qs: [
        "Проведи застосунок через усі стани: користувач згорнув і відкрив через годину — які колбеки і в якому порядку?",
        "Чому оновлення токена сесії — НЕ в didFinishLaunching?",
        "Розкажи повний шлях пуша: від реєстрації до відкриття екрана замовлення по тапу (твій робочий флоу).",
        "AppDelegate vs SceneDelegate — що куди і навіщо розділили?",
      ],
    },
    {
      p: "P0", name: "UIViewController lifecycle",
      what: [
        "Ланцюг: init → loadView (створює self.view; переозначають лише для повністю кастомного root view) → viewDidLoad (view створено, розміри НЕ фінальні; один раз на життя VC) → viewWillAppear (перед кожною появою) → viewWillLayoutSubviews / viewDidLayoutSubviews (після проходу AutoLayout — тут розміри ВЖЕ валідні; може викликатись багато разів) → viewDidAppear (на екрані, анімація переходу завершена) → viewWillDisappear / viewDidDisappear → deinit.",
        "Containment (child view controllers): addChild(child) → view.addSubview(child.view) → child.didMove(toParent: self) — вбудовування VC у VC (сегменти, вкладки, твої UIHostingController-вставки).",
      ],
      problem: "Знання «що і де робити» прибирає цілий клас багів: підписки в viewDidLoad без відписки → дублікати обробників після повернення; робота з frame у viewDidLoad → верстка під старий розмір; важке в viewWillAppear → лаг переходу. Правила: одноразова настройка — viewDidLoad; підписки/таймери — willAppear + зняття в didDisappear; усе залежне від розмірів — viewDidLayoutSubviews.",
      where: [
        "viewDidLoad: addSubview + констрейнти, конфіг таблиці, привʼязка VM.",
        "viewWillAppear: оновити дані, які могли змінитись, поки екран був у стеку (повернулись із деталей — список освіжити); почати спостереження.",
        "viewDidLayoutSubviews: градієнтний CALayer під розмір вʼюхи (layer не в AutoLayout!), скругления, залежні від фактичної ширини.",
        "viewDidAppear: стартувати анімації, запросити дозволи (не лякати юзера до появи екрана), почати відеоплеєр.",
      ],
      code: [
        "override func viewDidLoad() {",
        "    super.viewDidLoad()",
        "    setupSubviews()                    // один раз",
        "}",
        "override func viewWillAppear(_ animated: Bool) {",
        "    super.viewWillAppear(animated)",
        "    NotificationCenter.default.addObserver(self, selector: #selector(refresh),",
        "        name: .orderUpdated, object: nil)",
        "}",
        "override func viewDidDisappear(_ animated: Bool) {",
        "    super.viewDidDisappear(animated)",
        "    NotificationCenter.default.removeObserver(self)   // парна відписка",
        "}",
        "override func viewDidLayoutSubviews() {",
        "    super.viewDidLayoutSubviews()",
        "    gradientLayer.frame = headerView.bounds  // розміри вже фінальні",
        "}",
      ],
      traps: [
        "frame/bounds у viewDidLoad — ще від XIB/дефолту, НЕ фінальні (інші пристрої, rotation). Валідні — у viewDidLayoutSubviews.",
        "viewWillAppear без парного «зняття» у didDisappear — подвійні підписки після повернення.",
        "viewWillAppear викликався, а viewDidAppear ні — можливо: interactive pop скасовано на півдорозі (свайп назад відпущено).",
        "Пропущений didMove(toParent:) при containment — зламані appearance-колбеки дитини.",
      ],
      qs: [
        "Повний порядок колбеків від init до deinit? Що викликається один раз, що — багато?",
        "Чому frame невалідний у viewDidLoad і де валідний?",
        "Що робити в viewWillAppear vs viewDidLoad — правило?",
        "Як правильно вбудувати child VC (три кроки) — і де ти це робиш із UIHostingController?",
      ],
    },
    {
      p: "P0", name: "AutoLayout",
      what: [
        "Система лінійних рівнянь: кожен констрейнт — item1.attr = m × item2.attr + c. Solver (Cassowary) знаходить розвʼязок. Пріоритети: required (1000) — рівняння зобовʼязане виконатись; нижчі (999...1) — «побажання», яким можна поступитись. Конфлікт двох required — креш-лог «Unable to simultaneously satisfy constraints» і система викидає один констрейнт навмання.",
        "Intrinsic content size — власний розмір контенту (лейбл знає розмір тексту). Довкола нього два невидимі констрейнти з пріоритетами: content hugging (опір розтягуванню — «не хочу бути більшим за контент») і compression resistance (опір стисканню — «не дам себе обрізати»). Дефолти: hugging 251, resistance 750.",
        "Цикл верстки: setNeedsLayout — «поміть брудним, перерахуєш на наступному кадрі» (дешево, батчиться); layoutIfNeeded — «перерахуй НЕГАЙНО, якщо брудний» (синхронно); потрібен для анімації констрейнтів.",
      ],
      problem: "Вирішує адаптивність: один екран на всі розміри iPhone/iPad, динамічні шрифти, локалізації різної довжини (твої 10+ мов — німецький текст в 1.5 раза довший за англійський!). Пріоритети і hugging/resistance вирішують конфлікти «кому поступитись місцем» декларативно.",
      where: [
        "Класика «два лейбли в рядку»: назва страви + ціна. Ціна не має обрізатись: price.setContentCompressionResistancePriority(.required, for: .horizontal) — стиснеться назва (з «...»).",
        "Анімація розкриття панелі: змінити constant → UIView.animate { self.view.layoutIfNeeded() }.",
        "Self-sizing клітинки: констрейнти від верху до низу контенту + estimatedRowHeight — твоя щоденна практика в XIB.",
        "Перемикання станів: активація/деактивація масивів констрейнтів (NSLayoutConstraint.activate) — компактний/розгорнутий режими.",
      ],
      code: [
        "// Два лейбли: ціна не стискається, назва — так",
        "nameLabel.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)",
        "priceLabel.setContentCompressionResistancePriority(.required, for: .horizontal)",
        "priceLabel.setContentHuggingPriority(.required, for: .horizontal)",
        "",
        "// Анімація констрейнта:",
        "heightConstraint.constant = isExpanded ? 300 : 80",
        "UIView.animate(withDuration: 0.3) {",
        "    self.view.layoutIfNeeded()   // solver перерахує, зміни анімуються",
        "}",
      ],
      traps: [
        "translatesAutoresizingMaskIntoConstraints = false для КОЖНОЇ вʼюхи, створеної кодом — інакше автогенеровані констрейнти конфліктують з твоїми (найчастіша помилка).",
        "Анімація констрейнтів без layoutIfNeeded усередині animate-блоку — зміна стрибне без анімації.",
        "Конфлікт 1000 vs 1000 → лог з «Will attempt to recover by breaking constraint» — читай, який зламали; один з required зроби 999.",
        "Дебаг: view.constraintsAffectingLayout(for: .vertical), symbolic breakpoint UIViewAlertForUnsatisfiableConstraints, Debug View Hierarchy.",
      ],
      qs: [
        "Два лейбли в рядку, місця мало — який стиснеться? Як гарантувати, що ціна ніколи не обріжеться?",
        "hugging vs compression resistance — що кожен контролює?",
        "setNeedsLayout vs layoutIfNeeded — різниця і чому layoutIfNeeded потрібен в анімації?",
        "Як дебажиш Unable to satisfy constraints у великому XIB — покроково?",
      ],
    },
    {
      p: "P0", name: "UITableView / UICollectionView",
      what: [
        "Reuse: система тримає пул клітинок ≈ під видиму область; клітинка, що поїхала за екран, повертається в пул і видається знову через dequeueReusableCell — зі СТАРИМ вмістом. prepareForReuse — місце скинути стан (скасувати завантаження картинки, обнулити прапорці). dataSource — «що показувати» (кількість, клітинки); delegate — «як поводитись» (висоти, тапи, will/didDisplay).",
        "Diffable Data Source: описуєш НОВИЙ стан снапшотом (секції + item identifiers), система сама рахує diff і анімує вставки/видалення/переміщення. Прибирає цілий клас крешів «number of rows before update is not equal…» від ручного performBatchUpdates. Compositional Layout — декларативний опис колекції: item → group → section, кожна секція зі своєю геометрією й ортогональним скролом.",
      ],
      problem: "Reuse вирішує памʼять: стрічка з 10 000 замовлень тримає ~15 клітинок замість 10 000. Diffable вирішує коректність оновлень (креші batch updates). Compositional вирішує складні макети (горизонтальні карусельки в вертикальній стрічці — твоя home page) без вкладених collection views і їх багів.",
      where: [
        "Меню ресторану, список замовлень, каталог — базовий хліб твого проєкту.",
        "Async-картинки страв + reuse: скасування завантаження в prepareForReuse (Kingfisher робить це через cancelDownloadTask).",
        "Home page із секціями «банери / категорії / рекомендації» — compositional layout з orthogonal scrolling (природно лягає на твій server-driven UI: секції з конфіга бекенда).",
        "Diffable + server-driven: прийшов новий конфіг сторінки → новий снапшот → секції красиво анімуються.",
      ],
      code: [
        "// Класичний фікс «чужих картинок» при reuse:",
        "final class DishCell: UITableViewCell {",
        "    override func prepareForReuse() {",
        "        super.prepareForReuse()",
        "        thumbView.kf.cancelDownloadTask()   // 1) скасувати стару загрузку",
        "        thumbView.image = placeholder       // 2) плейсхолдер одразу",
        "    }",
        "}",
        "// 3) у cellForRowAt — завантаження за URL САМЕ ЦІЄЇ моделі",
        "",
        "// Diffable:",
        "var snapshot = NSDiffableDataSourceSnapshot<Section, MenuItem.ID>()",
        "snapshot.appendSections([.promo, .dishes])",
        "snapshot.appendItems(promoIDs, toSection: .promo)",
        "dataSource.apply(snapshot, animatingDifferences: true)",
      ],
      traps: [
        "«Чужі» картинки при скролі — питання №1 по таблицях: причина — reuse + асинхронне завантаження, що завершилось для вже переюзаної клітинки. Фікс: три кроки в коді вище.",
        "reloadData посеред анімацій/скролу — смикання, втрата виділень; точкові оновлення або diffable.",
        "Важке в cellForRowAt (форматування, підрахунки) — виконується на кожен показ клітинки → лаги скролу; готуй дані заздалегідь у VM.",
        "Diffable вимагає УНІКАЛЬНИХ і стабільних identifiers; дублікати = креш. ID, а не цілі моделі, у снапшоті (швидше, менше памʼяті).",
        "Self-sizing: повний ланцюг вертикальних констрейнтів у contentView + estimatedRowHeight; розриви = нульова висота.",
      ],
      qs: [
        "Чому при скролі зʼявляються «чужі» картинки і які три кроки фіксу?",
        "Навіщо prepareForReuse і що в ньому робити/не робити?",
        "Чим diffable data source кращий за reloadData і performBatchUpdates?",
        "Як би ти зверстав home page з горизонтальними каруселями — compositional layout: item/group/section?",
      ],
    },
    {
      p: "P1", name: "UIView, CALayer, rendering",
      what: [
        "Кожен UIView — обгортка над CALayer: view обробляє події (touch, responder chain) і AutoLayout, layer — малювання, геометрію, анімації. frame — прямокутник у координатах СУПЕРВʼЮХИ; bounds — власна система координат (origin зазвичай 0,0). Не збігаються: при transform (frame стає undefined — не читай його), при скролі (UIScrollView просто рухає bounds.origin!).",
        "Кадр рендериться конвеєром: layout (layoutSubviews) → display (draw/вміст layer) → композиція на GPU. Offscreen rendering — GPU змушений малювати у проміжний буфер до екрана: тригери — masksToBounds + cornerRadius на складному вмісті, тінь БЕЗ shadowPath, маски. Багато offscreen у клітинках = просідання скролу.",
      ],
      problem: "Розуміння view/layer пояснює, чому тінь і скруглення «конфліктують» (тінь малюється ЗОВНІ, clipping ріже ВСЕРЕДИНІ — на одному layer несумісні) і як анімувати те, чого немає в UIView API (CABasicAnimation по шляху). Розуміння bounds пояснює весь UIScrollView одним реченням.",
      where: [
        "Картка страви з тінню і скругленням: два шари — зовнішній layer з shadow + shadowPath, внутрішній view з cornerRadius + masksToBounds.",
        "Градієнт кнопки: CAGradientLayer, frame оновлюється у layoutSubviews/viewDidLayoutSubviews (layer не в AutoLayout!).",
        "Дебаг скролу: Simulator → Debug → Color Offscreen-Rendered Yellow; Instruments → Core Animation.",
        "layoutSubviews викликається при зміні bounds, addSubview, setNeedsLayout — ручна верстка підвʼюх без констрейнтів.",
      ],
      code: [
        "// Тінь + скруглення БЕЗ offscreen rendering:",
        "containerView.layer.shadowColor = UIColor.black.cgColor",
        "containerView.layer.shadowOpacity = 0.15",
        "containerView.layer.shadowPath = UIBezierPath(   // явний шлях = без offscreen",
        "    roundedRect: containerView.bounds, cornerRadius: 16).cgPath",
        "",
        "contentView.layer.cornerRadius = 16",
        "contentView.layer.masksToBounds = true           // ріже ВНУТРІШНІЙ вміст",
        "// containerView НЕ має masksToBounds — тінь живе зовні",
      ],
      traps: [
        "shadowPath оновлюй при зміні розмірів (layoutSubviews) — інакше тінь відстане від вʼюхи.",
        "Після transform читати/писати frame не можна — працюй з bounds + center.",
        "drawRect дорогий (CPU-растеризація) — лише коли справді потрібне кастомне малювання; частіше вистачає шарів і картинок.",
        "UIStackView сам не малюється (non-rendering) — background до iOS 14 не працював.",
      ],
      qs: [
        "frame vs bounds — коли не збігаються? Як через bounds пояснити UIScrollView?",
        "Як зробити тінь + cornerRadius без offscreen rendering?",
        "Що тригерить layoutSubviews?",
        "Чим відрізняються view і layer за відповідальністю?",
      ],
    },
    {
      p: "P1", name: "Responder chain, hit testing, gestures",
      what: [
        "Два окремі механізми. Hit testing — ПОШУК вʼюхи під пальцем: рекурсивний обхід дерева ЗВЕРХУ вниз (subviews у зворотному порядку — верхні перші) через hitTest(_:with:), який викликає point(inside:). Вʼюха випадає з пошуку: isUserInteractionEnabled=false, isHidden, alpha<0.01, точка поза bounds.",
        "Responder chain — ДОСТАВКА події, якщо ніхто не обробив: view → superview → ... → UIViewController → UIWindow → UIApplication. UIGestureRecognizer-и мають пріоритет над raw touches; конфлікти вирішуються делегатом (shouldRecognizeSimultaneouslyWith, require(toFail:)).",
      ],
      problem: "Пояснює найчастіші «містичні» баги дотиків: кнопка, що стирчить за межі батька, НЕ тапається (hit test батька відсікає точку поза його bounds до перевірки дітей); прозорий оверлей зʼїдає тапи; жест таблиці конфліктує з жестом клітинки.",
      where: [
        "Збільшення тач-зони маленької кнопки: override point(inside:) з bounds.insetBy(dx: -12, dy: -12).",
        "Кнопка за межами батька: override hitTest у батька — перевіряти дітей до відсікання.",
        "«Пропускати» тапи крізь оверлей: hitTest повертає nil для себе, але дітей перевіряє.",
        "Тап по фону закриває клавіатуру, але не блокує кнопки: tap recognizer з cancelsTouchesInView = false.",
      ],
      code: [
        "// Збільшена тач-зона:",
        "final class BigTapButton: UIButton {",
        "    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {",
        "        bounds.insetBy(dx: -12, dy: -12).contains(point)",
        "    }",
        "}",
        "// Кнопка, що виступає за межі контейнера:",
        "override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {",
        "    if let v = super.hitTest(point, with: event) { return v }",
        "    let p = overflowButton.convert(point, from: self)",
        "    return overflowButton.point(inside: p, with: event) ? overflowButton : nil",
        "}",
      ],
      traps: [
        "Порядок обходу: ОСТАННЯ додана subview перевіряється ПЕРШОЮ — верхня вʼюха перехоплює тапи нижньої.",
        "alpha < 0.01 вимикає дотики — «майже невидима» кнопка перестає працювати.",
        "Жест на superview зʼїдає тапи по клітинках таблиці — delegate + touch.view перевірка.",
        "hitTest викликається двічі на дотик — не клади туди side effects.",
      ],
      qs: [
        "Кнопка стирчить за межі батьківської вʼюхи — чому не тапається і два способи фіксу?",
        "Опиши рекурсію hitTest: порядок, умови відсікання.",
        "Hit testing vs responder chain — що шукає, що доставляє?",
        "Як розвʼязати конфлікт двох жестів (скрол + свайп клітинки)?",
      ],
    },
    {
      p: "P1", name: "Navigation: push, present, координатори",
      what: [
        "UINavigationController — стек VC: push/pop, свайп назад безкоштовно, спільний navigation bar. present — модальний показ ПОВЕРХ (окремий флоу: оформлення, авторизація); стилі: pageSheet (шторка), fullScreen (важливо: fullScreen НЕ викликає viewWillAppear у батька після dismiss — сюрприз для оновлення даних), popover.",
        "Coordinator: обʼєкт, що ВОЛОДІЄ навігацією — створює VC, тримає navigationController, вирішує «куди далі». VC лише повідомляє про події (делегат/closure) і не знає про інші екрани. Дерево координаторів: AppCoordinator → TabCoordinator → OrderFlowCoordinator.",
      ],
      problem: "Вирішує зашитість флоу у VC: коли екран сам створює і пушить наступний — його неможливо перевикористати в іншому флоу, тестувати і міняти порядок кроків. Особливо боляче у твоєму випадку server-driven checkout: порядок кроків приходить з бекенда — отже, вирішувати «куди далі» має координатор за конфігом, а не екран.",
      where: [
        "Checkout-флоу: CheckoutCoordinator читає конфіг кроків (адреса → оплата → підтвердження) і пушить екрани за ним — твій робочий патерн у чистому вигляді.",
        "Передача результату назад: closure var onAddressSelected: ((Address) -> Void)? — простіше за delegate для одного колбека.",
        "Deep link з пуша: AppCoordinator розбирає маршрут, вибирає таб, будує стек екранів.",
        "UIHostingController усередині координатора — SwiftUI-екрани в тому ж флоу без винятків.",
      ],
      code: [
        "final class CheckoutCoordinator {",
        "    private let nav: UINavigationController",
        "    private let steps: [CheckoutStep]          // server-driven конфіг!",
        "    private var index = 0",
        "    func start() { show(steps[0]) }",
        "    private func show(_ step: CheckoutStep) {",
        "        let vc = makeViewController(for: step)",
        "        vc.onCompleted = { [weak self] in self?.next() }   // екран не знає, що далі",
        "        nav.pushViewController(vc, animated: true)",
        "    }",
        "    private func next() {",
        "        index += 1",
        "        index < steps.count ? show(steps[index]) : finishOrder()",
        "    }",
        "}",
      ],
      traps: [
        "Координатори ніхто не тримає — деініт і мертві колбеки; батько тримає дітей у масиві childCoordinators, прибирає по завершенню флоу.",
        "onCompleted-closure захоплює координатор, координатор тримає VC... — [weak self] у колбеках координатора.",
        "present поверх present — «Attempt to present ... which is already presenting»; презентуй з topmost VC.",
        "Passing data: синглтони/глобальний стан замість init injection — нетестовано і звʼязує все з усім.",
      ],
      qs: [
        "Чому «VC сам пушить наступний VC» — антипатерн? Три причини.",
        "Як екран Б повертає результат екрану А — delegate, closure, async? Тредофи?",
        "Спроєктуй координатор для server-driven checkout — як конфіг визначає флоу?",
        "push vs present — семантика вибору (не технічна різниця, а КОЛИ що)?",
      ],
    },
    {
      p: "P2", name: "RunLoop, main thread, Timer",
      what: [
        "RunLoop — цикл обробки подій потоку: чекає події (тач, таймер, DisplayLink) → обробляє → спить. Main RunLoop крутить весь UI. Modes: default — звичайна робота; tracking — під час скролу; common — обʼєднання. Timer, доданий у default mode, ЗАВМИРАЄ під час скролу — RunLoop у tracking mode його не бачить.",
      ],
      problem: "Пояснює класичний баг «таймер зупиняється при скролі» (каруселька банерів перестає гортатись, поки юзер скролить меню — твій прямий кейс!) і чому «UI лише з main» — не забобон, а наслідок однопотокової моделі RunLoop/UIKit.",
      where: [
        "Автогортання промо-банерів: RunLoop.main.add(timer, forMode: .common) — працює і під час скролу.",
        "CADisplayLink — «таймер кадрів» для власних анімацій (прогрес кільця).",
        "Main Thread Checker ловить UI-виклики з фонових потоків (фіолетові варнінги).",
      ],
      code: [
        "let timer = Timer(timeInterval: 3, repeats: true) { [weak self] _ in",
        "    self?.scrollToNextBanner()",
        "}",
        "RunLoop.main.add(timer, forMode: .common)   // не завмирає при скролі",
      ],
      traps: [
        "Timer.scheduledTimer додає в default mode — банерна каруселька «зависає» при скролі; додай у .common.",
        "Timer з target: self тримає self СИЛЬНО до invalidate — block-based API + [weak self] + invalidate у deinit/didDisappear.",
        "Таймер — не точний інструмент: спрацює після поточної ітерації RunLoop; для точних кадрів — CADisplayLink.",
      ],
      qs: [
        "Чому таймер зупиняється при скролі й як полагодити?",
        "Чому Timer(target: self) створює цикл і як уникнути?",
        "Що таке RunLoop mode і навіщо common?",
      ],
    },
    {
      p: "P2", name: "XIB / Storyboard vs код",
      what: [
        "XIB — XML-опис однієї вʼюхи/екрана, вантажиться в рантаймі (Bundle.loadNibNamed); File's Owner — обʼєкт-власник, до якого чіпляються IBOutlet. Storyboard — багато екранів + segue між ними. Верстка кодом — усе явно, найкращий diff/merge.",
        "Твій проєкт (XIB + програмна верстка, БЕЗ Storyboard) — усвідомлений компроміс: XIB дає візуальний огляд і швидкість для статичних екранів/клітинок, код — контроль для динаміки; відсутність Storyboard прибирає найгірші merge-конфлікти і повільний Interface Builder на великих файлах.",
      ],
      problem: "Вибір інструмента — типове питання «як влаштований ваш проєкт». Storyboard-и в команді конфліктують на кожному PR (один XML на десятки екранів), погано ревʼюються, стрінгові ідентифікатори segue падають у рантаймі. XIB локалізує конфлікт до одного екрана. Код — єдине джерело правди, але повільніше для простих форм.",
      where: [
        "Переюзабельна вʼюха з XIB: клітинки меню, банери — registerNib + dequeue, твій щоденний пайплайн.",
        "loadNibNamed у init кастомної вʼюхи + прикріплення contentView (owner-патерн).",
        "Нові екрани — SwiftUI (у тебе так і є) — XIB лишили legacy, нове пишеться декларативно.",
      ],
      code: [
        "// Реєстрація і використання клітинки з XIB:",
        "tableView.register(UINib(nibName: \"DishCell\", bundle: nil),",
        "                   forCellReuseIdentifier: \"DishCell\")",
        "let cell = tableView.dequeueReusableCell(withIdentifier: \"DishCell\",",
        "                                         for: indexPath) as! DishCell",
      ],
      traps: [
        "IBOutlet — сучасна рекомендація strong (weak — спадок часів viewDidUnload); але weak теж працює, головне розуміти чому.",
        "Забутий registerNib → креш dequeue; стрінгові ідентифікатори — винось у константи/SwiftGen (у вас він є!).",
        "XIB + кастомний init: awakeFromNib викликається ПІСЛЯ звʼязування outlets — конфігуруй там, не в init.",
      ],
      qs: [
        "Аргументуй ваш вибір XIB + код без Storyboard — плюси, мінуси, чому не інакше?",
        "Як влаштований пайплайн переюзабельної вʼюхи з XIB у вашому проєкті?",
        "Чому великі команди тікають від Storyboard?",
      ],
    },
    {
      p: "P0", name: "Основні UIViewController у UIKit",
      what: [
        "UIKit побудований навколо UIViewController — базового класу для будь-якого екрана. Усі інші «контролери» — це підкласи з додатковою спеціалізацією: UITableViewController (список), UICollectionViewController (сітка), UINavigationController (стек екранів), UITabBarController (вкладки), UISplitViewController (два екрани на iPad), UIPageViewController (сторінки свайпом). На співбесіді важливо розуміти не назви, а роль кожного: хто малює контент, а хто лише керує навігацією.",
        "Ієрархія успадкування: UIViewController → UITableViewController, UICollectionViewController, UINavigationController, UITabBarController, UISplitViewController, UIPageViewController, … Кожен має свою спеціалізацію, але 90% екранів у реальних проєктах — звичайний UIViewController всередині UINavigationController.",
      ],
      sections: [
        {
          title: "1. UIViewController — базовий екран",
          text: "UIViewController — найпоширеніший контролер. Використовуй, коли екран містить будь-яку комбінацію елементів: UILabel, UIButton, UIImageView, UITextField, UITableView, UICollectionView, Map, WebView. Приклади екранів: Login, Profile, Settings, Product Details, Chat, Forms, Camera. Ти повністю відповідаєш за: створення subviews, addSubview, Auto Layout constraints, delegate/dataSource, реєстрацію комірок. Це дає максимальну гнучкість — саме тому сучасні екрани майже завжди будуються на UIViewController, навіть якщо головний елемент — таблиця.",
          code: [
            "class ProfileViewController: UIViewController {",
            "    private let avatarView = UIImageView()",
            "    private let nameLabel = UILabel()",
            "    private let followButton = UIButton()",
            "    private let tableView = UITableView()",
            "",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
            "        view.addSubview(avatarView)",
            "        view.addSubview(nameLabel)",
            "        view.addSubview(followButton)",
            "        view.addSubview(tableView)",
            "        // constraints для кожного елемента",
            "        // tableView.delegate = self, dataSource = self",
            "        // tableView.register(...)",
            "    }",
            "}",
            "// Екран: Avatar → Name → Button → UITableView",
          ],
        },
        {
          title: "2. UIViewController + UITableView — ти сам створюєш таблицю",
          text: "Питання на співбесіді: «У чому різниця між let tableView = UITableView() і UITableViewController?» Відповідь: різниця не в самому рядку коду, а в тому, ХТО створює UITableView. У UIViewController ти сам створюєш таблицю і несеш повну відповідальність. Тобі потрібно: (1) створити UITableView, (2) додати її в view через addSubview, (3) налаштувати constraints (pin to edges або під search bar), (4) призначити delegate і dataSource, (5) зареєструвати комірки (register / registerNib). Вся відповідальність на тобі — але ти контролюєш розташування таблиці відносно інших елементів.",
          code: [
            "class UsersViewController: UIViewController {",
            "    let tableView = UITableView()",
            "",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
            "        view.addSubview(tableView)",
            "        // constraints: tableView.pin(to: view.safeAreaLayoutGuide)",
            "        tableView.delegate = self",
            "        tableView.dataSource = self",
            "        tableView.register(UITableViewCell.self, forCellReuseIdentifier: \"Cell\")",
            "    }",
            "}",
            "// ✅ Ти повністю контролюєш створення та розташування таблиці",
          ],
        },
        {
          title: "3. UITableViewController — таблиця вже створена",
          text: "UITableViewController — спеціалізований підклас для екранів, що майже повністю складаються зі списку (Users: John, Mike, Kate…). Тут НЕ потрібно писати let tableView = UITableView() і view.addSubview(tableView) — UITableViewController вже має готову tableView. Вона створюється автоматично при завантаженні контролера. Спрощено всередині це виглядає так: class UITableViewController: UIViewController { let tableView = UITableView() } — реальний код складніший (автоматичний layout, tableView займає весь view, contentInsetAdjustmentBehavior). Переваги: менше boilerplate, вбудований refreshControl для pull-to-refresh. Недолік: якщо потрібні інші елементи на екрані — складно, бо view контролера І Є tableView.",
          code: [
            "class UsersViewController: UITableViewController {",
            "    // let tableView = UITableView()  — НЕ потрібно!",
            "    // view.addSubview(tableView)     — НЕ потрібно!",
            "",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
            "        tableView.register(UITableViewCell.self,",
            "                           forCellReuseIdentifier: \"Cell\")",
            "        tableView.reloadData()",
            "    }",
            "}",
            "// ➡️ Таблиця вже існує. Ти просто працюєш з нею.",
          ],
        },
        {
          title: "4. Чому зараз частіше UIViewController + UITableView?",
          text: "Сучасний екран рідко складається лише з таблиці. Типова структура: Search Bar зверху → Banner → UITableView → Floating Button знизу. Таку композицію набагато простіше зробити через UIViewController, бо ти сам керуєш усіма елементами і їх constraints. UITableViewController заточений під «таблиця = весь екран». Для співбесіди: «UITableViewController — для простих full-screen списків; UIViewController + UITableView — для реальних екранів зі змішаним UI». У більшості production-проєктів (включно з food delivery) саме другий варіант.",
          code: [
            "// Сучасний екран (UIViewController):",
            "// ┌─────────────────────┐",
            "// │     Search Bar      │",
            "// ├─────────────────────┤",
            "// │       Banner        │",
            "// ├─────────────────────┤",
            "// │                     │",
            "// │     UITableView     │",
            "// │                     │",
            "// ├─────────────────────┤",
            "// │  [ Floating Cart ]  │",
            "// └─────────────────────┘",
            "",
            "class MenuViewController: UIViewController {",
            "    let searchBar = UISearchBar()",
            "    let bannerView = PromoBannerView()",
            "    let tableView = UITableView()",
            "    let cartButton = UIButton()",
            "    // кожен елемент — окремий subview з constraints",
            "}",
          ],
        },
        {
          title: "5. UICollectionViewController — сітки і галереї",
          text: "Аналог UITableViewController, але для UICollectionView. Таблиця — одна колонка рядків; collection view — grid (□ □ □), mosaic, horizontal scroll (📱 📱 📱), Pinterest layout. Має готову collectionView — не створюєш вручну. Використовується: Gallery, Photos, App Store, Netflix, Pinterest. Якщо на екрані grid + header + filter — краще UIViewController + UICollectionView (та сама логіка, що з таблицею).",
          code: [
            "class PhotosViewController: UICollectionViewController {",
            "    // collectionView вже є",
            "    override func collectionView(_ collectionView: UICollectionView,",
            "                                numberOfItemsInSection section: Int) -> Int {",
            "        photos.count",
            "    }",
            "}",
            "// Grid:  □ □ □",
            "//         □ □ □",
          ],
        },
        {
          title: "6. UINavigationController — стек екранів (push / pop)",
          text: "UINavigationController не малює контент — він керує переходами між екранами як стек (LIFO). Home → push → Profile → push → Settings. Back (кнопка або свайп) → pop → Profile. Методи: pushViewController(_:animated:) — додати екран зверху; popViewController(animated:) — повернутись; popToRootViewController — на початок стеку. Майже кожен UIKit-застосунок має UINavigationController. Сам navigation controller — це UIViewController-обгортка з navigation bar зверху; контент — твій UIViewController всередині.",
          code: [
            "let home = HomeViewController()",
            "let nav = UINavigationController(rootViewController: home)",
            "",
            "// Home → Profile → Settings",
            "nav.pushViewController(ProfileViewController(), animated: true)",
            "nav.pushViewController(SettingsViewController(), animated: true)",
            "",
            "// Back: Settings → Profile",
            "nav.popViewController(animated: true)",
          ],
        },
        {
          title: "7. UITabBarController — нижні вкладки",
          text: "Керує вкладками внизу екрана: Home | Search | Cart | Profile. Кожна вкладка — окремий UIViewController (зазвичай обгорнутий у UINavigationController, щоб усередині вкладки працював push/pop). Структура: TabBarController.viewControllers = [homeNav, searchNav, cartNav, profileNav]. Використовується: Instagram, YouTube, App Store, Facebook. selectedIndex — перемикання програмно. TabBar — корінь застосунку або один з рівнів ієрархії.",
          code: [
            "let tabBar = UITabBarController()",
            "",
            "let homeNav = UINavigationController(rootViewController: HomeVC())",
            "let searchNav = UINavigationController(rootViewController: SearchVC())",
            "let cartNav = UINavigationController(rootViewController: CartVC())",
            "let profileNav = UINavigationController(rootViewController: ProfileVC())",
            "",
            "tabBar.viewControllers = [homeNav, searchNav, cartNav, profileNav]",
            "// Home | Search | Cart | Profile",
          ],
        },
        {
          title: "8. UISplitViewController — два екрани (iPad)",
          text: "Показує два екрани одночасно: master (список) | detail (вміст). Переважно iPad: Mail (Folders | Email), Notes (Sidebar | Note), Files. На iPhone згортається — показує або master, або detail через navigation. Використовуй, коли на великому екрані потрібен постійний sidebar + контент.",
          code: [
            "let split = UISplitViewController(style: .doubleColumn)",
            "split.viewControllers = [",
            "    UINavigationController(rootViewController: FoldersVC()),  // master",
            "    UINavigationController(rootViewController: EmailDetailVC()), // detail",
            "]",
            "// iPad:  Folders | Email body",
            "// iPhone: спочатку Folders, tap → Email",
          ],
        },
        {
          title: "9. UIPageViewController — сторінки свайпом",
          text: "Дозволяє гортати сторінки горизонтально свайпом: ◀️ Page 1 ▶️ ◀️ Page 2 ▶️. Використовується: Onboarding (3–4 екрани вітання), Stories, PDF Reader, Tutorials. Ти надаєш масив UIViewController і керуєш переходами через dataSource (яка сторінка до/після) і delegate.",
          code: [
            "let pageVC = UIPageViewController(",
            "    transitionStyle: .scroll,",
            "    navigationOrientation: .horizontal)",
            "pageVC.dataSource = self",
            "pageVC.setViewControllers([onboardingPage1],",
            "                          direction: .forward, animated: true)",
          ],
        },
        {
          title: "10. Системні контролери (готові, не наслідуєш)",
          text: "Apple надає готові контролери для типових задач — ти їх present-иш, а не пишеш з нуля. UIImagePickerController — камера або photo library (для library застарілий). PHPickerViewController — сучасний вибір фото, рекомендований з iOS 14 (privacy-friendly, не потребує повного доступу до бібліотеки). SFSafariViewController — Safari всередині застосунку (оплата, terms of service). MFMailComposeViewController — написати email з app.",
          code: [
            "// PHPicker (рекомендований для фото):",
            "var config = PHPickerConfiguration()",
            "config.selectionLimit = 5",
            "let picker = PHPickerViewController(configuration: config)",
            "picker.delegate = self",
            "present(picker, animated: true)",
            "",
            "// Safari в app:",
            "let safari = SFSafariViewController(url: termsURL)",
            "present(safari, animated: true)",
          ],
        },
        {
          title: "11. Архітектура реального застосунку + шпаргалка",
          text: "Типова структура UIKit-app: UITabBarController (корінь) → кілька UINavigationController (по одному на вкладку) → UIViewController (контент екранів). Navigation і TabBar не малюють UI — вони керують навігацією та структурою. Усередині майже всі екрани — UIViewController. Шпаргалка для співбесіди: UIViewController — будь-який екран зі змішаним UI; UITableViewController — простий список на весь екран; UICollectionViewController — сітки/галереї; UINavigationController — push/pop; UITabBarController — нижні вкладки; UISplitViewController — два екрани (iPad); UIPageViewController — свайп-сторінки.",
          code: [
            "// UITabBarController",
            "// │",
            "// ├── UINavigationController",
            "// │      ├── HomeViewController",
            "// │      └── ProductViewController",
            "// │",
            "// ├── UINavigationController",
            "// │      ├── SearchViewController",
            "// │      └── ResultViewController",
            "// │",
            "// └── UINavigationController",
            "//        ├── ProfileViewController",
            "//        └── SettingsViewController",
            "",
            "// 90% екранів = UIViewController",
            "// Nav + TabBar = керують, не малюють",
          ],
        },
      ],
      problem: "Без розуміння ролі кожного контролера легко: (1) взяти UITableViewController для екрана з search bar і banner — і боротись з обмеженнями; (2) не знати різницю push vs present; (3) не вміти намалювати дерево TabBar → Nav → VC на співбесіді. Ця тема — карта UIKit-навігації: що обирати і чому.",
      where: [
        "UIViewController + UITableView — щоденна робота: search bar, банер, список страв, floating cart button (твій food-delivery проєкт).",
        "UINavigationController — push на деталі замовлення/страви, pop назад; present модально для login/checkout.",
        "UITabBarController — корінь app: Menu | Orders | Profile.",
        "UITableViewController — legacy-екрани «просто список налаштувань»; у нових фічах рідше.",
        "PHPickerViewController — вибір фото для аватара/відгуку замість UIImagePicker.",
        "UIPageViewController — onboarding нового користувача після реєстрації.",
      ],
      traps: [
        "UITableViewController: view контролера = tableView. Не додавай інші subviews у view без розуміння — краще UIViewController.",
        "Плутати UINavigationController (стек всередині вкладки) і UITabBarController (перемикання між розділами).",
        "Думати, що let tableView = UITableView() — це «погано»; ні, це стандарт для складних екранів.",
        "present fullScreen — viewWillAppear батька не викликається після dismiss; оновлюй дані в completion.",
        "UIImagePicker для photo library — застарілий; PHPicker з iOS 14+.",
        "UINavigationController і UITabBarController — контейнери, не екрани з контентом.",
      ],
      qs: [
        "У чому різниця між UIViewController + let tableView = UITableView() і UITableViewController? Що ти повинен зробити в кожному варіанті?",
        "Чому зараз частіше UIViewController + UITableView? Наведи приклад екрана з кількома елементами.",
        "Що всередині UITableViewController — чому не потрібен addSubview?",
        "Поясни UINavigationController як стек: push Home → Profile → Settings, потім Back.",
        "Як влаштований UITabBarController? Що в кожній вкладці і навіщо Nav всередині?",
        "Намалюй дерево UIKit-app: TabBar → Nav → VC для food-delivery.",
        "Коли UITableViewController, а коли UICollectionViewController?",
        "Чим PHPicker кращий за UIImagePicker для photo library?",
        "UIViewController vs UINavigationController vs UITabBarController — хто малює контент, хто керує навігацією?",
      ],
    },
    {
      p: "P0", name: "Механізми передачі даних у UIKit",
      what: [
        "Питання «як один обʼєкт передає інформацію іншому» в UIKit майже завжди зводиться до напрямку передачі та рівня звʼязності між обʼєктами. На співбесіді виграєш, якщо не просто перелічиш механізми, а швидко класифікуєш: вперед (A → B), назад (B → A), глобально (подія/стан для багатьох).",
        "Класифікація (зручна для співбесіди): передача даних вперед — property injection / dependency injection; передача назад — delegate / closure; глобальна передача подій — NotificationCenter; глобальний доступ до спільних даних — singleton/shared store. Нижче — коли що доречно, плюси/мінуси і приклади.",
      ],
      sections: [
        {
          title: "0. Ключова ідея: напрямок і життєвий цикл",
          text: "Перед тим як вибирати механізм, відповідай на 3 питання: (1) Хто «володіє» даними — батько чи дитина? (2) Це одноразова передача чи потік подій? (3) Хто кого знає (сильна залежність) і чи потрібна відписка (lifecycle)? Зазвичай: батько передає дані в дитину при створенні (forward), а дитина повертає результат батьку (back).",
          code: [
            "// Forward: Parent → Child (налаштовує перед показом)",
            "// Back: Child → Parent (повертає результат після дії користувача)",
            "// Global event: багато слухачів (не знають одне одного)",
            "// Shared state: один store, який читають/пишуть багато екранів",
          ],
        },
        {
          title: "1. Property injection (передача вперед)",
          text: "Ти створюєш екран і перед показом записуєш у його публічні властивості дані, які йому потрібні. Це просто і читабельно, але важливо: властивості мають бути встановлені ДО того, як екран їх використає (зазвичай до push/present). Добре для простих параметрів: userId, mode, початковий state.",
          code: [
            "final class UserDetailsVC: UIViewController {",
            "    var userID: String!          // встановлюється ззовні перед показом",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
            "        loadUser(id: userID)",
            "    }",
            "}",
            "",
            "final class UsersVC: UIViewController {",
            "    func openUser(_ id: String) {",
            "        let vc = UserDetailsVC()",
            "        vc.userID = id            // ✅ property injection (forward)",
            "        navigationController?.pushViewController(vc, animated: true)",
            "    }",
            "}",
          ],
        },
        {
          title: "2. Dependency injection (передача вперед + тестованість)",
          text: "DI — це передача залежностей (сервісів) у клас ззовні, щоб він не створював їх сам. У UIKit зазвичай роблять init-injection: залежності передаються в init і стають let-властивостями. Це робить код тестованим (можна підставити mock), зменшує звʼязність і прибирає синглтони «звідусіль».",
          code: [
            "protocol UsersService {",
            "    func fetchUsers() async throws -> [User]",
            "}",
            "",
            "final class UsersVC: UIViewController {",
            "    private let service: UsersService",
            "    init(service: UsersService) {",
            "        self.service = service",
            "        super.init(nibName: nil, bundle: nil)",
            "    }",
            "    required init?(coder: NSCoder) { fatalError(\"init(coder:) has not been implemented\") }",
            "}",
            "",
            "// Composition root (SceneDelegate/AppCoordinator):",
            "let vc = UsersVC(service: APIUsersService())",
          ],
        },
        {
          title: "3. Delegate (передача назад)",
          text: "Delegate — класичний UIKit-патерн для «дитина повідомляє батька». Дитина має protocol з методами, батько підписується і стає delegate. Важливо: delegate майже завжди weak (і протокол — AnyObject), щоб не створити retain cycle. Delegate зручний, коли подій кілька або вони мають сенс як «контракт».",
          code: [
            "protocol EditProfileDelegate: AnyObject {",
            "    func editProfile(_ vc: EditProfileVC, didSave name: String)",
            "    func editProfileDidCancel(_ vc: EditProfileVC)",
            "}",
            "",
            "final class EditProfileVC: UIViewController {",
            "    weak var delegate: EditProfileDelegate?",
            "    func saveTapped() {",
            "        delegate?.editProfile(self, didSave: nameTextField.text ?? \"\")",
            "    }",
            "    func cancelTapped() {",
            "        delegate?.editProfileDidCancel(self)",
            "    }",
            "}",
            "",
            "final class ProfileVC: UIViewController, EditProfileDelegate {",
            "    func openEdit() {",
            "        let vc = EditProfileVC()",
            "        vc.delegate = self          // ✅ back channel",
            "        present(vc, animated: true)",
            "    }",
            "    func editProfile(_ vc: EditProfileVC, didSave name: String) { updateUI(name) }",
            "    func editProfileDidCancel(_ vc: EditProfileVC) { dismiss(animated: true) }",
            "}",
          ],
        },
        {
          title: "4. Closure / Callback (передача назад)",
          text: "Closure — легший варіант delegate, коли подія одна (або 2–3 простих). Ти передаєш у дитину замикання, і дитина викликає його при завершенні. Перевага: менше шаблонного коду. Ризик: retain cycle, якщо захопити self сильно — у виклику часто потрібен [weak self].",
          code: [
            "final class ChooseCityVC: UIViewController {",
            "    var onChoose: ((City) -> Void)?",
            "    func didSelect(_ city: City) {",
            "        onChoose?(city)",
            "    }",
            "}",
            "",
            "final class CheckoutVC: UIViewController {",
            "    func openCityPicker() {",
            "        let vc = ChooseCityVC()",
            "        vc.onChoose = { [weak self] city in",
            "            self?.selectedCity = city",
            "            self?.updateUI()",
            "        }",
            "        navigationController?.pushViewController(vc, animated: true)",
            "    }",
            "}",
          ],
        },
        {
          title: "5. NotificationCenter (глобальна подія)",
          text: "NotificationCenter — pub/sub для подій, де відправник і слухачі не мають знати одне про одного. Підходить для крос-скрінних сигналів: «userLoggedOut», «orderUpdated». Мінуси: слабка типізація (name + userInfo), легко отримати хаос, і важливо управляти життєвим циклом підписки (особливо зі старим addObserver/removeObserver).",
          code: [
            "extension Notification.Name {",
            "    static let userLoggedOut = Notification.Name(\"userLoggedOut\")",
            "}",
            "",
            "// Publisher:",
            "NotificationCenter.default.post(name: .userLoggedOut, object: nil)",
            "",
            "// Subscriber (iOS 9+ токен-API):",
            "final class HomeVC: UIViewController {",
            "    private var token: NSObjectProtocol?",
            "    override func viewDidAppear(_ animated: Bool) {",
            "        super.viewDidAppear(animated)",
            "        token = NotificationCenter.default.addObserver(forName: .userLoggedOut, object: nil, queue: .main) { [weak self] _ in",
            "            self?.showLogin()",
            "        }",
            "    }",
            "    deinit { if let token { NotificationCenter.default.removeObserver(token) } }",
            "}",
          ],
        },
        {
          title: "6. Singleton / Shared store (глобальний доступ до стану)",
          text: "Singleton (shared) дає глобальну точку доступу до даних: Session.shared.user, CartStore.shared.items. Плюс: просто. Мінуси: глобальний мутабельний стан, складно тестувати, приховані залежності, ризик гонок (thread-safety). На співбесіді важливо вміти сказати: «так, інколи ок, але краще DI».\n\nShared store краще робити як окремий обʼєкт (store) з API (методи, нотифікації, Combine/closures), а не як набір глобальних змінних.",
          code: [
            "final class Session {",
            "    static let shared = Session()",
            "    private init() { }",
            "    private(set) var token: String? = nil",
            "    func updateToken(_ t: String?) { token = t }",
            "}",
            "",
            "// Використання:",
            "if let token = Session.shared.token { /* authorized */ }",
          ],
        },
        {
          title: "7. Dependency injection vs Singleton — як відповісти на співбесіді",
          text: "Шаблон відповіді: «Для даних вперед — property injection (прості параметри) або init-based DI (залежності/сервіси). Назад — delegate (контракт, багато подій) або closure (1 подія). Глобально — NotificationCenter (події між модулями) або shared store (стан, який читають багато екранів). Синглтони — крайній варіант; краще DI, бо тестованість і явні залежності».",
          code: [
            "// Forward:  init/props",
            "// Back:     delegate / closure",
            "// Global:   NotificationCenter (event) / Store (state)",
            "// Preferred: DI > Singleton",
          ],
        },
      ],
      problem: "Ця тема закриває типове інтервʼю-питання: «як передати дані між екранами/обʼєктами в UIKit». Без чіткої структури легко перетворити відповідь на список слів. Класифікація за напрямком (forward/back/global) допомагає швидко обрати правильний механізм і пояснити чому він доречний саме тут.",
      where: [
        "Forward (A → B): push на деталі (передати id), init-injection сервісів/VM у новий екран.",
        "Back (B → A): модалка «редагувати» повертає результат (delegate/closure).",
        "Global event: «userLoggedOut» змушує різні екрани показати login (NotificationCenter).",
        "Shared state: кошик/сесія користувача доступні з різних вкладок (store).",
      ],
      traps: [
        "Delegate має бути weak, а протокол — AnyObject, інакше retain cycle або неможливість weak.",
        "У closure легко захопити self сильно → retain cycle. Часто потрібен [weak self].",
        "NotificationCenter без контролю підписок = дублікати і memory leaks (особливо якщо не знімати observer/token).",
        "Singleton приховує залежності й ламає тести — якщо можеш, передавай через DI.",
        "Property injection небезпечний з implicit unwrap (var userID: String!) — краще let + init, якщо дані обовʼязкові.",
      ],
      qs: [
        "Класифікуй механізми передачі даних: forward / back / global event / shared state.",
        "Delegate vs closure — коли що? Які плюси/мінуси?",
        "Чому delegate зазвичай weak? Який протокол для цього потрібен?",
        "Коли NotificationCenter доречний, а коли це «code smell»?",
        "Чим DI кращий за Singleton? Як би ти передав UsersService у UsersVC?",
        "Як уникнути retain cycle у callback closure?",
      ],
    },
  ],
};
